### ISSUE TITLE
White space between header and row, using filter control and table-height

### ISSUE THREAD

**Issue by DataSupplier** [wenzhixin/bootstrap-table#5541] opened 2021-01-14 18:35 UTC
**Bootstraptable version(s) affected**:
Bootstrap 5 + Bootstrap-Table 1.81 and below.

**Description**  
Visually table is not showing correctly, having a white space between the column header and the row.
The last row is not readable. 

Using the same setup disabling the table-height option, the table works and shows fine.
Using the same setup disabling the filter-control extension, the table works and shows fine.

**Example**  
https://live.bootstrap-table.com/code/DataSupplier/6195

**Comment by UtechtDustin** [comment] 2021-01-19 18:06
For the developer which will fix this bug: the problem is the `table-sm` (Changes the heights).
Minimal example: https://live.bootstrap-table.com/code/UtechtDustin/6274

**Comment by fabiawrc** [comment] 2021-01-22 06:09
confirm the same problem

**Comment by djhvscf** [comment] 2021-03-04 23:35
Working on it

**Comment by djhvscf** [comment] 2021-04-18 00:48
Fixed in https://github.com/wenzhixin/bootstrap-table/pull/5583

**Comment by djhvscf** [comment] 2021-11-20 16:17
Example with fix: https://live.bootstrap-table.com/code/djhvscf/9665

**Comment by UtechtDustin** [comment] 2021-11-20 17:27
@djhvscf 
If i use the example from @DataSupplier and your branch the fix won't work: https://live.bootstrap-table.com/code/UtechtDustin/9668

**Comment by wenzhixin** [comment] 2021-11-26 00:53
I think the problem is `data-filter-control=""`.

**Comment by UtechtDustin** [comment] 2021-11-26 08:49
@wenzhixin i don't think so. If you change it to e.g. `data-filter-control="select"` there is still a space between the header and the table.
The footer also looks odd.

**Closed** 2022-02-10 11:49 UTC
Labels: confirmed, has PR, Bug
