### ISSUE TITLE
Dynamically format the editable column as password or plain text

### ISSUE THREAD

**Issue by rajeshbtlit** [wenzhixin/bootstrap-table#3433] opened 2017-10-31 15:54 UTC
Hi,
Appreciate your efforts for providing this framework,
I have a bootstrap table , with 3 columns, UserName ,UserInfo and Type(hidden which has value text/password) which has editable column UserInfo , i need to make the UserInfo  as type password, based on Type value, 
I added this to UserInfo data-editable-type="password" and i see all the values for UserInfo  becomes [hidden]

But i need to do this only for some values for UserInfo ,  request you to please help.

My actual code is
```
                <table id="attributeTable" style="table-layout: fixed; width: 100%" data-toggle="table" class="table order-list"
                       data-cache="false" data-height="300" data-striped="true"
                       data-pagination="true" data-sort-order="asc"
                       data-sort-name="UserName" data-response-handler="responseHandlerAttributes"
                       data-page-size="20" data-page-list='[20, 35, 50, 100, 200, 500]'>
                    <thead>
                    <tr>
                        <th style="width:25%" data-field="UserName" data-sortable="true">Name</th>
                        <th style="width:25%" data-field="UserInfo " data-editable="true" data-editable-type="password">Info</th>
                        <th style="width:25%" data-field="Type" data-sortable="true">Type</th>
                       </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
```

**Comment by rajeshbtlit** [comment] 2017-11-02 06:28
Hi could any one please help on this, appreciate your kind help.
@djhvscf @wenzhixin

**Comment by djhvscf** [comment] 2017-11-29 04:53
@rajeshbtlit do you have any jsfiddle?

**Comment by djhvscf** [comment] 2018-01-29 05:41
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR**. Thanks!

**Closed by djhvscf** 2018-01-29 05:41 UTC
Labels: editable, needs example
