### ISSUE TITLE
Header shifted after sorting

### ISSUE THREAD

**Issue by Loecha** [wenzhixin/bootstrap-table#2571] opened 2016-08-15 08:28 UTC
Hello all,

please use ["Large Columns"](http://issues.wenzhixin.net.cn/bootstrap-table/#options/large-columns.html) example to reproduce bug.
If i do scrolling to the last right column and then i do sorting, the header has wrong position after sorting.

This is my Hook, which i use, to fix this bug:

``` JavaScript
(function () {
    "use strict";
    // Zeiger auf Prototype hollen
    var prototype = $.fn.bootstrapTable.Constructor.prototype;


    /**
     * Hook für fitHeader. Aktualisieren von Headerposition nach dem "append"
     * @method fitHeader
     * @for BootstrapTable
     */
    var oldFitHeader    = prototype.fitHeader; // Alte Funktionzwischenspeichern
    prototype.fitHeader = function () {
        var result = oldFitHeader.apply(this, arguments);
        // Header verschieben
        this.$tableHeader.scrollLeft($(this.$tableBody).scrollLeft());
        return result;
    };
}());
```

**Comment by dabros** [comment] 2016-08-16 01:20
@Loecha - cant see any issues, ive sorted columns on both far sides and in middle, scrolled before, scrolled after, ect with many permutations but no issues noted

Please provide a Fiddle and we can help you more, dummy data from js array is fine (just needs to replicate core issue). For data-url use them from examples provided, if you need more custom server side then see http://stackoverflow.com/questions/7194408/how-can-i-use-the-jsfiddle-echo-feature-with-jquery

Examples and guide provided below:
- https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports
- #1765 

More clear description of current output vs desired ouput, your browser and environment details where this bug is seen and ideally a fiddle that on your machine replicates the issue should help us solve this

**Comment by Loecha** [comment] 2016-08-16 05:19
@dabros - i not need to create a Fiddle example, because example "Large Columns" has same issues, see above.
My Systems are Windows 7 / 10 (64Bit), i use Firefox 48.
And under "Crome Version 52.0.2743.116 m" Table Header is always shifted.

![unbenannt](https://cloud.githubusercontent.com/assets/13977919/17688664/8219ff24-6381-11e6-82ac-23f6829dad80.png)

I have solved this Problem, see my code snippet. It work for My.

**Comment by dabros** [comment] 2016-08-16 06:41
@Loecha 

Thank you for providing more detail, though i am completely unable to replicate this issue and i have tried in dozens of different ways

**using Chrome Version 52.0.2743.116 m**
![image](https://cloud.githubusercontent.com/assets/780783/17690052/5cf9e828-63cf-11e6-8a77-05d6cea46e04.png)

The screenshot shows something of interest to me, and that is the table cells dont wrap the text, which is why it is misaligned

You claim this is not the case in chrome but i cant see that, so something strange is happening.

Unless I can replicate this I really cannot help you much, perhaps @wenzhixin or @djhvscf have more thoughts

What i can say with absolute certainty is:

1. the TD not wrapping is the cause of the misalignment
2. That putting this rule in web developer on the demo was able to replicate it: `td { white-space: nowrap; }`
3. That `nowrap` is NOT the default being shown with the chrome version above, no idea why it is on yours
4. That a js fix is NOT the solution, look instead at just overwriting the `white-space` rule to overwrite any `nowrap`, also look at `word-wrap` and similar rules if still issues

**Comment by Loecha** [comment] 2016-08-16 06:43
This is my Modification for "bootstrap-table-fixed-columns" [Modification under jsFiddle](https://jsfiddle.net/g6w09w2y/2/) it work for my.

This Mode Fixed folown Isuse:
[Header shifted after sorting](https://github.com/wenzhixin/bootstrap-table/issues/2571)
[Sort under fixed columns does not work. ](https://github.com/wenzhixin/bootstrap-table-fixed-columns/issues/3)
[Scrollbar is hidden under fIxed columns. ](https://github.com/wenzhixin/bootstrap-table-fixed-columns/issues/2)

Tested under:
Windows 10 (64Bit)
Firefox 48.0, Chrome 52.0.2743.116 m, IE11.545, Edge 25.10586.0.0

**Comment by lalithsysvine** [comment] 2017-03-23 09:45
@dabros , I believe this issue can only be reproduced in Firefox. Since, I am also facing the similar issue only in Firefox (52.0.1 64-bit ) and not in chrome. 

I am using OS X Yosmite version 10.10.5
Snap of my code while creating table with data
```
$('#'+tableId).bootstrapTable({
	columns:header,
	data:tableData,
	height: '400',
	sortable: true,
	toolbar:'#'+tableId+'toolbar'
});
```
Hope, it might help you in finding the root cause of issue.
Please help me, if i am missing anywhere. Thank you

**Comment by wenzhixin** [comment] 2019-03-10 15:08
Fixed in the latest version. If the problem exists reopen it, thanks!

**Closed by wenzhixin** 2019-03-10 15:08 UTC
