### ISSUE TITLE
Cookie issue: data-url not loaded when using cookie extension

### ISSUE THREAD

**Issue by SystemF** [wenzhixin/bootstrap-table#2651] opened 2016-09-18 07:17 UTC
When I try to use the cookie extension the data-url request won't fire, so there are no rows. When I put the data attribute inline (no request) then it do work.

Setting the cookie extension to false, bootstrap table will show all rows as intended.

Please take a look at http://dev1.puntxl.nl/ for a minimized working example.

Edit: When I use an older version of the bootstrap-table-cookie.js it works like expected.

**Comment by cyberbobjr** [comment] 2016-11-04 21:25
Hi, same problem here

**Comment by SystemF** [comment] 2016-11-04 21:42
I took it from a older CDN that I found after some search on the web. Maybe you can look for some older release tags here on Github too. Success!

**Comment by mmerian** [comment] 2016-12-16 16:05
Hi guys,

Looks like this is a duplicate of issue #2582 

Cheers

**Comment by Falseee** [comment] 2019-03-25 22:18
Issue is resolved, see #2582

**Closed by Falseee** 2019-03-25 22:18 UTC
