### ISSUE TITLE
Table with fixed headers causes filters to reset and show duplicate options

### ISSUE THREAD

**Issue by jrpespisa** [wenzhixin/bootstrap-table#2595] opened 2016-08-26 21:09 UTC
I have implemented bootstrap-table v. 1.11.0 with the bootstrap-table-filter-control v 2.1.0 column filtering extension. It may also be worth mentioning that I am initializing the table using React.

I am experiencing and issue where, when selected, the filters will reset back to their original state and if I try to select a filter option again, four of each filter option show up instead. If I select one and repeat the process again, 16 show up, etc.

I believe the issue is being caused by bootstrap-table's "data-height" attribute because when I remove that attribute, everything works beautifully. 

After doing some research, it looks like this issue was fixed before:
https://github.com/wenzhixin/bootstrap-table/pull/977

For some reason this issue is persisting even with the apparent fix.

Any ideas on what could be causing an issue like this? Thanks in advance!

**Comment by mapcentia** [comment] 2016-09-14 09:48
It seems, that this bug also effects "input" filter. Filtering works alright, but it seems that the browser gets bloated and will crash after some typing. I guess it has to do with the duplication of data. Without a table height the issue disappear.

**Comment by pko** [comment] 2017-01-04 14:26
I encounter the same bug with bootstrap-table v1.11.0, filter-controle v2.1.0 and sticky-header.

**Comment by axheine** [comment] 2017-01-16 08:56
Same issue with bootstrap-table v1.11.0, filter-control and sticky-header. I try to use jquery.stickytableheaders instead of sticky-header with the same result.
That may caused by the duplication of the thead row ?

**Comment by zerox1212** [comment] 2018-01-26 22:58
My table still has this problem.

A fix is posted here https://github.com/wenzhixin/bootstrap-table/issues/3255#issue-241551104 but I have no idea what the solution is. The js fiddle is hundreds of lines long.

**Comment by zerox1212** [comment] 2018-01-26 23:18
After looking closer the solution is to edit `bootstrap-table-filter-control.js` just below line 42 in V2.1.1.

Below the line `var sortSelectControl = function (selectControl) {` add this code:
```javascript
selectControl = $(selectControl.get(selectControl.length - 1)); // this line solved the problem :: cause selectControl varibale has 2 object, one is from sticky header table, second one is from body table**
```
Now filter select works again.

**Comment by zerox1212** [comment] 2018-01-26 23:57
Found out if you change to DEVELOP branch and use the files from SRC everything is more or less working.

**Comment by wenzhixin** [comment] 2019-02-01 16:04
Fixed in the latest version.

**Closed by wenzhixin** 2019-02-01 16:04 UTC
