### ISSUE TITLE
When using the cookie plugin, the first ajax call isn't fired

### ISSUE THREAD

**Issue by erichelgeson** [wenzhixin/bootstrap-table#2582] opened 2016-08-19 02:41 UTC
When using the `cookie` extension it looks like the overridden `_initServer` in the extension returns too early and never tries to call the url here https://github.com/wenzhixin/bootstrap-table/blob/develop/src/extensions/cookie/bootstrap-table-cookie.js#L302-L305 I'm not sure what the logic is doing here, hence no patch :)

Example:
https://jsfiddle.net/spfgx18g/1/

When you load this you see the url is never called. If you comment out the cooke and re-run it will call the URL.

This also presents itself with serverside pagination, the first call is not sent but sorting will then send the ajax call.

May be related to https://github.com/wenzhixin/bootstrap-table/issues/2483 as well

**Comment by RadekVala** [comment] 2016-09-02 07:40
I had the same issue. But the example [here](http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/cookie.html) with similar scenario work well. I try to update the bootstrap-table plugin to version 1.11.0, it did not helped. Then I realized that after node update, the extension was still in v1.2.1, but examples are using v1.2.2. After manual update of bootstrap-table-cookie.js to v1.2.2. it is working also with server data.

**Comment by erichelgeson** [comment] 2016-09-03 18:06
It looks like 1.2.2 works, thanks. This is not currently in the release, but on the development branch.

**Comment by vingorius** [comment] 2016-09-06 02:21
Tks @RadekVala & @erichelgeson .

**Comment by vingorius** [comment] 2016-09-06 02:22
@wenzhixin , Could you update this module.

**Comment by pandomic** [comment] 2017-01-06 10:37
It seems that it is js's typecast issue.
In Cookie.js we have:
```js
cookiesPresent = function() {
    return bootstrapTable.options.cookie && bootstrapTable.getCookies(bootstrapTable);
};
// ...
if (cookiesPresent() && selectsWithoutDefaults.length === 0) {
    return;
}
```
If you try in console `false && []` you will got expected `false`, but unfortunately if you try `true && []` you'll got `Array` instead of `Boolean`, that;s why `return;` will be executed even if cookies are not presented.

So solution is pretty simple, we need just to change
```js
return bootstrapTable.options.cookie && bootstrapTable.getCookies(bootstrapTable);
```
to 
```js
return bootstrapTable.options.cookie && bootstrapTable.getCookies(bootstrapTable).length;
```

**Comment by pasztorpisti** [comment] 2017-06-09 00:44
### Reproducing the bug

http://jsfiddle.net/pasztorpisti/yvr6u93s/

- Open the fiddle link. When you load it first time the data in the table should appear as expected.
- Enter something into one of the filter controls (1 character is enough) and either leave it that way (if it doesn't filter out everything) or clear the filter textbox to blank. This forces saving the state even if the filter is blank. Clearing it to blank might be a good idea because that way we won't be able to blame filtering for an empty table.
- Either reload the whole fiddle page or press the "Play" button of jsfiddle to reload my example. You should see an empty table because the saved filters have been loaded (even if they are blank) and `initServer` returns without firing the first ajax request. By pressing the refresh tool button at the top-right of the table you can force reload the table.

In some browsers you might not be able to reproduce the bug in icognito mode (for me chrome worked but safari didn't).

### Possible fix

The current implementation of the `initServer` hook is quite fragile and difficult to understand.

I suggest something like the following:

```javascript
BootstrapTable.prototype.initServer = function () {
    if (hasSavedFilterValues() && !bootstrapTable.options.filterControlValuesLoaded) {
        return;
    }
    // calling the original hooked method
    origInitServer();
}
```

This `initServer` hook assumes that the `initCookieFilters` triggers an `initServer` call after loading the filter values and setting `bootstrapTable.options.filterControlValuesLoaded = true`.

**Comment by pasztorpisti** [comment] 2017-06-13 13:29
Note that a change (e56b8b2e5b09e840ae2c3fc10eddb4313c292b96) has been merged that solves the problem I described. However I'm not sure that it protects against double ajax requests in all cases (considering the implementation of `initCookieFilters` and `initServer`) so it might still worth checking out my PR that is a significant simplification to the `initServer` function.

**Comment by djhvscf** [comment] 2017-06-18 01:43
This issue is solved in https://github.com/wenzhixin/bootstrap-table/pull/3184

Example: https://jsfiddle.net/djhvscf/62wpstwb/1/

**Closed by djhvscf** 2017-06-18 01:43 UTC
Labels: cookie
