### ISSUE TITLE
DetailView and reorderableColumns have a bug

### ISSUE THREAD

**Issue by javieerrubio11** [wenzhixin/bootstrap-table#2674] opened 2016-09-28 06:35 UTC
When I use the detailView and reorderableColumns plugin It produces the next error.

Chrome console log：
bootstrap-table.js:2256 Uncaught TypeError: Cannot read property 'visible' of undefined

[Example jsfiddle](https://jsfiddle.net/javierIntegra/gn78ozxh/11/)

In order to reproduce the error, you have to reorder some column and after that, you tray to order one column asc or desc for example.

Thanks for all.

**Comment by pozuelog** [comment] 2017-02-10 11:50
Same bug is affecting me. Did yout find a solution?

**Comment by javieerrubio11** [comment] 2017-02-10 12:02
Sorry, but I don't find a solution.

**Comment by UtechtDustin** [comment] 2019-11-02 18:52
Cant reproduce it, also its almost 2 1/2 so i close the issue.
If this issue still exists please reopen the issue.

**Closed by UtechtDustin** 2019-11-02 18:52 UTC
Labels: confirmed, js, reorder-columns
