### ISSUE TITLE
 "data-height" attribute confilict with "data-filter-control" attribute

### ISSUE THREAD

**Issue by EdQzz** [wenzhixin/bootstrap-table#4937] opened 2020-03-18 01:46 UTC
in this example page [filter control](https://live.bootstrap-table.com/example/extensions/filter-control.html), when I add "data-height='460'" to table, "data-filter-control='true'" doesn't work anymore and it's a blank gap between table-header and table-data

**Comment by UtechtDustin** [comment] 2020-03-18 08:33
duplicate of #4869

**Closed by UtechtDustin** 2020-03-18 08:33 UTC
