### ISSUE TITLE
Tables do not respect server sort anymore

### ISSUE THREAD

**Issue by drummer73** [wenzhixin/bootstrap-table#4919] opened 2020-02-28 20:00 UTC
Hi,

using 1.16.0, server-sort will be overridden by client-sort even if sidePagination is set to "server" and serverSort is set to true;

"initSort" is called even if both settings above are set and therefore the client will resort the responded server data.

**Comment by wenzhixin** [comment] 2020-03-22 02:35
Sorry, I don't know what you mean: https://live.bootstrap-table.com/code/wenzhixin/2220.

**Comment by drummer73** [comment] 2020-03-22 08:35
> Sorry, I don't know what you mean: https://live.bootstrap-table.com/code/wenzhixin/2220.

@wenzhixin I modified your example data and added a date col with german date format (dd.mm.yyyy): https://live.bootstrap-table.com/code/drummer73/2221

The data form server is sorted by date asc, so that the table should display the items from #0 to #5 ascending. But bootstrap-tables resorting the data and sorts by the date as string.

As a (very) quick and dirty fix, I inserted 
`} else if (this.options.sidePagination === 'server' && this.options.serverSort) {`
at line https://github.com/wenzhixin/bootstrap-table/blob/8045d0812b4666556abab0b8867520f038df566d/src/bootstrap-table.js#L418

**Comment by wenzhixin** [comment] 2020-03-22 09:20
Thanks for your online example, I think this bug is caused by #4832.
Fixed in #4940.

**Comment by drummer73** [comment] 2020-03-22 10:00
Thank you!

**Closed** 2020-03-23 04:49 UTC
Labels: confirmed, has PR, js
