### ISSUE TITLE
UpdateRow and UpdateByUniqueId refresh the whole table

### ISSUE THREAD

**Issue by macharius40** [wenzhixin/bootstrap-table#4721] opened 2019-11-28 15:40 UTC
when we try to update a row by its index or its unique id, the whole table is re rendered, when the table has lot of data and use custom formatter for some columns, it can make a long time to refresh the table (in particular on Internet Explorer).

Here you can see an example of a formatter recalled every time we click on "update row" button : https://live.bootstrap-table.com/code/macharius40/1267

In my case, I use boostrap table with a table of 6 collumns (with 4 custom formatters) and around 150 rows. It take around 2 seconds on Chrome and 5 seconds on IE with a freeze of the whole interface for update only one row.

I don't no if it's possible to refresh only the updated row. But, I think it's a solution to improve performance.

**Comment by wenzhixin** [comment] 2019-12-13 16:30
Duplicate of #3612, close this one.

**Closed by wenzhixin** 2019-12-13 16:30 UTC
