### ISSUE TITLE
How can one use updateCell after sorting?

### ISSUE THREAD

**Issue by kwagdy** [wenzhixin/bootstrap-table#6592] opened 2023-01-05 19:04 UTC
### Description

I am not sure if I haven't read enough of the docs or is it hard to wrap my head around how to use UpdateCell after sorting the table? 
When attempting to update a cell after user sorts the table by one of the columns, the underlying table data get updated correctly, however the HTML table updates the wrong cell! 

```
$("#myTable").bootstrapTable('updateCell', {
  index: row_index, //<-- This refers to the correct underlying table data, however it seems to update the wrong cell on the HTML if the table is sorted by the user
  field: 'payment',
  value: new_val,
  reinit: false
});
```

**Comment by UtechtDustin** [comment] 2023-02-11 20:30
Please provide us an example using our [editor](https://live.bootstrap-table.com/) ?

**Comment by UtechtDustin** [comment] 2023-02-28 22:41
I'm going to close this issue, because we got no example from you.
If you still need help, please let us know and provide us an example.

**Closed by UtechtDustin** 2023-02-28 22:41 UTC
Labels: help-wanted, needs example

**Comment by wooly** [comment] 2023-11-02 04:09
@UtechtDustin here is a simple example: https://live.bootstrap-table.com/code/wooly/16445

If you click 'Run' then 'updateCell', you'll see the row with id of 5 starts counting. If you then hit 'Run' again and change the item name column sort (so that the row with id of 5 is not in row 5 any more) and click updateCell, it updates a different cell this time.

The issue I'm facing is that I want to update multiple cells at a time, but the rows do not have a unique identifier so I'm trying to find the index of a particular row in my dataset as it applies to the _current state_ of the table to update. Basically my table has a name column, with some names repeated multiple times. The user can perform an action that results in having to update all cells in one column for each row matching a name.

I thought I could do this by:

1. Calling 'getData' on the table.
2. Finding the index of all of the rows whose name matches the desired name
3. For each of these indices, call updateCell with that index.

The problem is that the order the data is returned by the getData call isn't the order that the table is currently rendered in.

Any thoughts would be much appreciated!

Cheers
W
