### ISSUE TITLE
Feature Request: Need header formatter similar to footer formatter

### ISSUE THREAD

**Issue by akkivarma10** [wenzhixin/bootstrap-table#4778] opened 2020-01-01 12:49 UTC
Need header formatter to format the header title.

In my case, I want to be able to add break tags in header title to make it more compact. So it would be great to have a header formatter to achieve this. Currently I am doing this in onPostHeader function hook where I am using the element selector to change the title. It would be helpful to have a header title formatter where I am just returning the formatted header title.

Thanks.

**Comment by UtechtDustin** [comment] 2020-01-01 16:26
Duplicate of #4611 
Is implemented in the PR #4737

**Closed by UtechtDustin** 2020-01-01 16:26 UTC
