### ISSUE TITLE
is there an option to hide cell content when it's too long?

### ISSUE THREAD

**Issue by bambooom** [wenzhixin/bootstrap-table#2476] opened 2016-07-16 15:26 UTC
Hi all,

I'd like to know how to show only the first several characters, and hide (not wrap) the text/string afterwards when the cell content is too long, like Excel?

[a jsFiddle example](https://jsfiddle.net/bambooom/a63Ltxd4/)

Thanks.

**Comment by DustinUtecht** [comment] 2016-07-17 00:33
Is this a way for you ? 
http://jsfiddle.net/e3nk137y/7635/

**Comment by bambooom** [comment] 2016-07-17 07:23
@DustinUtecht  thanks! that's great.

**Comment by bambooom** [comment] 2016-07-18 07:16
@DustinUtecht sorry, i found another problem about your suggested solution, which is, when I want to export the table, it will only download table with the partial display not the full content.......

**Comment by djhvscf** [comment] 2016-07-18 12:49
@bambooom Provide an example with that issue related to export the table, please

**Comment by wenzhixin** [comment] 2016-07-18 14:04
Try this:
```
white-space: nowrap;
overflow: hidden;
text-overflow: ellipsis;
```

**Comment by bambooom** [comment] 2016-07-18 14:46
https://jsfiddle.net/bambooom/a63Ltxd4/5/

tried, it won't wrap the content, also won't hidden....
and, I can't make export function working on jsFiddle .... refused to execute

**Comment by dabros** [comment] 2016-08-01 05:34
@bambooom  - you need to define a maximum width for the td themselves, as noted in the doco

http://bootstrap-table.wenzhixin.net.cn/documentation/#column-options

`max-width: 50px;`

> width	
> data-width
> Number {Pixels or Percentage}	
> undefined	
> The width of column. If not defined, the width will auto expand to fit its contents. Though if the table is left responsive and sized too small this 'width' might be ignored (use min/max-width via class or such then). Also you can add '%' to your number and the bootstrapTable will use the percentage unit, otherwise, leave as number (or add 'px') to make it use pixels.

**Comment by djhvscf** [comment] 2017-12-29 08:17
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR**. Thanks!

**Closed by djhvscf** 2017-12-29 08:17 UTC
Labels: awaiting reply, help wanted
