### ISSUE TITLE
dbl-click-row.bs.table event

### ISSUE THREAD

**Issue by francescomeloni** [wenzhixin/bootstrap-table#2633] opened 2016-09-09 16:48 UTC
HI, 
is there a way to avoid 'dbl-click-row.bs.table'  event to trigger two times  'click-row.bs.table' event ?

thanks

**Comment by wenzhixin** [comment] 2019-02-22 04:59
Duplicate of #3393

**Closed by wenzhixin** 2019-02-22 04:59 UTC
