### ISSUE TITLE
Problems filtering through javascript, with "filterBy" method

### ISSUE THREAD

**Issue by luisapuyen** [wenzhixin/bootstrap-table#1985] opened 2016-02-10 15:00 UTC
I'm trying to apply my own date range filter by using the "filterBy" method, but it's not working. The workaround I implemented to use it was to pass each and every date from the start date to the end date to the filter.

My own code filters out everything whenever I change the date. I've tried it in the jsFiddle below, but it's behaving different. It doesn't filter anything, despite the filter is receiving the selected range of dates in both cases.

The code [here](https://jsfiddle.net/luis_apuyen/hp909mtg/)

**Comment by dabros** [comment] 2016-02-11 06:01
@luisapuyen - this really issnt a bug report nor a feature request.

If you want a custom search feature that can support something like this, look at #1956

But if you want help fixing your custom code, post to SO and post that link here before closing (https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#using-the-issue-tracker)

**Comment by luisapuyen** [comment] 2016-02-11 07:26
But there is an issue here actually. Yes, it's most surely not the best way to do it, to pass all the dates in a range as an argument, but the filterBy method is getting data in a format like this:

```
{
   date: [
    '2016-02-01',
    '2016-02-02',
    '2016-02-03',
    ]
}
```

just like said in the documentation for OR conditions. If I remove the array and try only one date, like this:

```
{
   date: '2016-02-01'
}
```

the filter works without problems.

**Comment by tannermccoleman** [comment] 2016-02-11 23:47
I played around with the fiddle for quite a while, and it definitely appears that filtering with arrays isn't working. As well, the `Loading, please wait...` text appears to be stuck

**Comment by wenzhixin** [comment] 2016-02-17 06:38
Merged the PR, please check whether the problem persists.

**Comment by luisapuyen** [comment] 2016-02-22 16:16
I think I found the bug. I was using the Accent Neutralise plugin, and it seems to ignore arrays for filters.

This is the code within the **initSearch()** method overridden in this plugin: 


            ```
            // Check filter
            this.data = f ? $.grep(this.options.data, function (item, i) {
                for (var key in f) {
                    if (item[key] !== f[key]) {
                        return false;
                    }
                }
                return true;
            }) : this.options.data;
```

This is how I changed it just as the original code:

            ```
// Check filter
            this.data = f ? $.grep(this.options.data, function (item, i) {
                for (var key in f) {
                    if ($.isArray(f[key])) {
                        if ($.inArray(item[key], f[key]) === -1) {
                            return false;
                        }
                    } else if (item[key] !== f[key]) {
                        return false;
                    }
                    return true;
                }
            }) : this.options.data;
```

**Comment by djhvscf** [comment] 2017-12-29 08:21
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR**. Thanks!

**Closed by djhvscf** 2017-12-29 08:21 UTC
Labels: awaiting reply
