### ISSUE TITLE
Quotes in table cell causing issues with filter-control

### ISSUE THREAD

**Issue by valoukh** [wenzhixin/bootstrap-table#5201] opened 2020-07-23 08:53 UTC
**Bootstraptable version(s) affected**:
1.17.1

**Description**  
When a table cell contains quotes, e.g. an anchor link `<a href="#">My Link</a>`, or a _fontawesome_ icon `<i class="fas fa-home"></i>`, the filter-control 'select' box 'breaks' (looks strange). Is some escaping required on my part, or is there an option for cleansing HTML content that I haven't seen?

**Example**  
https://live.bootstrap-table.com/code/valoukh/4093

**Comment by UtechtDustin** [comment] 2020-07-23 15:01
duplicate of #5076

**Closed** 2020-07-23 15:01 UTC
Labels: Bug, duplicate
