### ISSUE TITLE
GroupBy-V2 + Editable Row (Dropdown)

### ISSUE THREAD

**Issue by airtonjr** [wenzhixin/bootstrap-table#3419] opened 2017-10-22 16:28 UTC
Hello ALL, 

The extension GroupByV-2 has issues to work with the Editable extension?

Instead to show the text for the dropdown it shows the value. (image).

Is it has any working around?

Thank you. 

![groupcapture](https://cloud.githubusercontent.com/assets/7409463/23112001/2da91ccc-f6f2-11e6-973f-593cc4d2ed85.PNG)

**Comment by wenzhixin** [comment] 2017-12-01 14:33
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by djhvscf** [comment] 2018-01-29 05:43
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR** with an [example](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports). Thanks!

**Closed by djhvscf** 2018-01-29 05:43 UTC
Labels: needs example
