### ISSUE TITLE
initTable error with HTML table

### ISSUE THREAD

**Issue by gohanman** [wenzhixin/bootstrap-table#2785] opened 2016-11-23 17:13 UTC
I'm trying to get fixed headers on a table and on page load bootrap-table crashes on this line: https://github.com/wenzhixin/bootstrap-table/blob/develop/dist/bootstrap-table.js#L718
The error in the browser console is `that.columns[x] is undefined`.

JSFiddle: http://jsfiddle.net/e3nk137y/9965/

Removing the first row of `<thead>` eliminates the problem. Are multi-row `<thead>`s not supported? I can see `that.columns` has indexes -1 through 4 instead of 0 through 12

**Comment by caxilomo** [comment] 2017-01-24 18:07
I think that the problem is the 'colspan' property.
In your example if you add all the values of colspan the total is 11 and in the following row have 14 rows.

I had the same problem and it was caused beacues the number of rows in the head wasn't the same that in the body

**Comment by gohanman** [comment] 2017-01-24 18:26
That makes sense, but unfortunately doesn't seem to help.

Updated fiddle w/ colspan=14 in the first row: http://jsfiddle.net/e3nk137y/11334/

I still see the same javascript error at the same line.

**Comment by wenzhixin** [comment] 2019-03-30 08:17
Fixed in the latest version: http://jsfiddle.net/wenyi/e3nk137y/44358/.

**Comment by UtechtDustin** [comment] 2019-06-22 06:33
There is just a little small typo which cause the issue.
In line 4 (jsfiddle) you use a `td` instead of a `th`, with a `th` it works fine.
Demo: https://live.bootstrap-table.com/code/UtechtDustin/56

**Comment by UtechtDustin** [comment] 2019-06-22 06:36
There is just a little small typo which cause the issue.
In line 4 (jsfiddle) you use a `td` instead of a `th`, with a `th` it works fine.
Demo: https://live.bootstrap-table.com/code/UtechtDustin/57

**Closed by UtechtDustin** 2019-06-22 06:36 UTC
Labels: confirmed
