### ISSUE TITLE
.fixed-table-loading元素 v1.17升级到v1.18的影响

### ISSUE THREAD

**Issue by sunwe** [wenzhixin/bootstrap-table#5322] opened 2020-09-23 00:56 UTC
在v1.17中，.fixed-table-loading的样式是display:none，到了v1.18，.fixed-table-loading的样式改为了display:flex,visibility: hidden;
虽然初始都不显示，但1.18中该元素还是会占用预置的宽度。
直接的影响就是，我的列特别多，为了在界面中不让列挤在一起，使用了
`<table style="table-layout: fixed;word-break:break-all;"></table>`
去让列宽能严格按照设置的宽度显示。
列宽总宽度实际超出了表格宽度，这会让.fixed-table-loading获得的真实宽度同样大于表格宽度，所以，一个隐藏但有宽度影响的.fixed-table-loading会让页面出现了多余的滚动条。

**Comment by sunwe** [comment] 2020-09-25 01:27
> 
> 
> 在v1.17中，.fixed-table-loading的样式是display:none，到了v1.18，.fixed-table-loading的样式改为了display:flex,visibility: hidden;
> 虽然初始都不显示，但1.18中该元素还是会占用预置的宽度。
> 直接的影响就是，我的列特别多，为了在界面中不让列挤在一起，使用了
> `<table style="table-layout: fixed;word-break:break-all;"></table>`
> 去让列宽能严格按照设置的宽度显示。
> 列宽总宽度实际超出了表格宽度，这会让.fixed-table-loading获得的真实宽度同样大于表格宽度，所以，一个隐藏但有宽度影响的.fixed-table-loading会让页面出现了多余的滚动条。


`<link rel="stylesheet" href="https://unpkg.com/placeholder-loading/dist/css/placeholder-loading.min.css">


<style>
  .ph-item,
  .ph-picture {
    width: 100%;
    height: 100%;
    padding: 0;
    margin: 0;
  }
</style>

<div id="toolbar" class="select">
  <select id="type" class="form-control">
    <option value="fa">Font Awesome Loading</option>
    <option value="pl">Placeholder Loading</option>
  </select>
</div>

<table
  style="table-layout: fixed;"
  id="table"
  data-toggle="table"
  data-height="460"
  data-toolbar="#toolbar"
  data-loading-template="loadingTemplate">
  <thead>
    <tr>
      <th data-field="a" data-width="100">a</th>
      <th data-field="b" data-width="100">b</th>
      <th data-field="c" data-width="100">c</th>
      <th data-field="d" data-width="100">d</th>
      <th data-field="e" data-width="100">e</th>
      <th data-field="f" data-width="100">f</th>
      <th data-field="g" data-width="100">g</th>
      <th data-field="h" data-width="100">h</th>
      <th data-field="i" data-width="100">i</th>
      <th data-field="j" data-width="100">j</th>
      <th data-field="k" data-width="100">k</th>
      <th data-field="l" data-width="100">l</th>
      <th data-field="m" data-width="100">m</th>
      <th data-field="n" data-width="100">n</th>
      <th data-field="o" data-width="100">o</th>
      <th data-field="p" data-width="100">p</th>
      <th data-field="q" data-width="100">q</th>
      <th data-field="r" data-width="100">r</th>
      <th data-field="s" data-width="100">s</th>
      <th data-field="t" data-width="100">t</th>
      <th data-field="u" data-width="100">u</th>
      <th data-field="v" data-width="100">v</th>
      <th data-field="w" data-width="100">w</th>
      <th data-field="x" data-width="100">x</th>
      <th data-field="y" data-width="100">y</th>
      <th data-field="z" data-width="100">z</th>
    </tr>
  </thead>
</table>

<script>
  var type = 'fa'

  function loadingTemplate(message) {
    if (type === 'fa') {
      return '<i class="fa fa-spinner fa-spin fa-fw fa-2x"></i>'
    }
    if (type === 'pl') {
      return '<div class="ph-item"><div class="ph-picture"></div></div>'
    }
  }

  function rebuild() {
    $('#table').bootstrapTable('destroy')
      .bootstrapTable()
      //.bootstrapTable('showLoading')
  }

  $(function() {
    $('#type').change(function () {
      type = $(this).val()
      rebuild()
    })
    rebuild()
  })
</script>`

**Comment by sunwe** [comment] 2020-09-25 01:37
Please run this code on [https://live.bootstrap-table.com/example/options/loading-template.html](url)
The bottom scrollbar is redundant.

```<link rel="stylesheet" href="https://unpkg.com/placeholder-loading/dist/css/placeholder-loading.min.css">

<style>
  .ph-item,
  .ph-picture {
    width: 100%;
    height: 100%;
    padding: 0;
    margin: 0;
  }
</style>

<div id="toolbar" class="select">
  <select id="type" class="form-control">
    <option value="fa">Font Awesome Loading</option>
    <option value="pl">Placeholder Loading</option>
  </select>
</div>

<table
  style="table-layout: fixed;"
  id="table"
  data-toggle="table"
  data-height="460"
  data-toolbar="#toolbar"
  data-loading-template="loadingTemplate">
  <thead>
    <tr>
      <th data-field="a" data-width="100">a</th>
      <th data-field="b" data-width="100">b</th>
      <th data-field="c" data-width="100">c</th>
      <th data-field="d" data-width="100">d</th>
      <th data-field="e" data-width="100">e</th>
      <th data-field="f" data-width="100">f</th>
      <th data-field="g" data-width="100">g</th>
      <th data-field="h" data-width="100">h</th>
      <th data-field="i" data-width="100">i</th>
      <th data-field="j" data-width="100">j</th>
      <th data-field="k" data-width="100">k</th>
      <th data-field="l" data-width="100">l</th>
      <th data-field="m" data-width="100">m</th>
      <th data-field="n" data-width="100">n</th>
      <th data-field="o" data-width="100">o</th>
      <th data-field="p" data-width="100">p</th>
      <th data-field="q" data-width="100">q</th>
      <th data-field="r" data-width="100">r</th>
      <th data-field="s" data-width="100">s</th>
      <th data-field="t" data-width="100">t</th>
      <th data-field="u" data-width="100">u</th>
      <th data-field="v" data-width="100">v</th>
      <th data-field="w" data-width="100">w</th>
      <th data-field="x" data-width="100">x</th>
      <th data-field="y" data-width="100">y</th>
      <th data-field="z" data-width="100">z</th>
    </tr>
  </thead>
</table>

<script>
  var type = 'fa'

  function loadingTemplate(message) {
    if (type === 'fa') {
      return '<i class="fa fa-spinner fa-spin fa-fw fa-2x"></i>'
    }
    if (type === 'pl') {
      return '<div class="ph-item"><div class="ph-picture"></div></div>'
    }
  }

  function rebuild() {
    $('#table').bootstrapTable('destroy')
      .bootstrapTable()
      //.bootstrapTable('showLoading')
  }

  $(function() {
    $('#type').change(function () {
      type = $(this).val()
      rebuild()
    })
    rebuild()
  })
</script>
```

**Comment by djhvscf** [comment] 2020-09-25 02:24
What do you mean by the bottom scrollbar? I can't see such scrollbar

**Comment by sunwe** [comment] 2020-09-25 03:17
![](http://jdtx.fun:8088/manager/assets/img/1.png)
If you can see this external link picture, please refer to this picture. The problem has been marked in the picture. When it is necessary to ensure the true width of each column, and the total column width is greater than the width of the parent element, additional scroll bars will appear. The reason is that the css style version of the .fixed-table-loading element has changed.
1.17.1 style {display:none}
1.18.0 style {display:flex,visibility: hidden;}
  [Translated from Google]

**Comment by UtechtDustin** [comment] 2020-10-03 10:54
Duplicate of #5348

**Closed by UtechtDustin** 2020-10-03 10:54 UTC
Labels: Bug, awaiting reply
