### ISSUE TITLE
footer row sum

### ISSUE THREAD

**Issue by shengkinng** [wenzhixin/bootstrap-table#4010] opened 2018-10-16 10:56 UTC
How can I achieve this?
footer row sum
![2018-10-16_185235](https://user-images.githubusercontent.com/40712030/47011690-17793b80-d175-11e8-9153-34552ec58993.png)

I am a newbie....help me

**Comment by shengkinng** [comment] 2018-10-18 12:00
hi..Can a master help?

**Comment by wenzhixin** [comment] 2019-02-23 02:06
Duplicate of #4017

**Closed by wenzhixin** 2019-02-23 02:06 UTC
