### ISSUE TITLE
Grouped columns not displaying when other column hidden

### ISSUE THREAD

**Issue by LlamaLasagna** [wenzhixin/bootstrap-table#4110] opened 2019-01-14 00:18 UTC
When columns are grouped under a column heading using colspan, and one of the columns is hidden, it hides the data of the next column as well but leaves the heading.

See this JS Fiddle for an example: http://jsfiddle.net/kr7s5zth/

Column B is hidden and column C should be visible, but only the header is, the data showing below it is from column D.

I think this might relate to [this issue](https://github.com/wenzhixin/bootstrap-table/issues/3817) but it seems slightly different.

**Comment by UtechtDustin** [comment] 2019-06-24 17:30
duplicate of #3817

**Closed by UtechtDustin** 2019-06-24 17:30 UTC
Labels: confirmed, js
