### ISSUE TITLE
Optional expand sign for detailed view

### ISSUE THREAD

**Issue by JosephRe** [wenzhixin/bootstrap-table#3153] opened 2017-05-24 10:01 UTC
Optional expand sign for detailed view only on selected rows

All I want is to certain rows in my detailed table to be expandable and certain rows not.
I have done the screenshot not with the default "data-detail-view="true", because certain rows must not have a "+" sign informant of them, because there is nothing to expand.

![image](https://cloud.githubusercontent.com/assets/20334613/26397954/3c9a6d24-4078-11e7-962e-4057f1790247.png)

**Comment by wenzhixin** [comment] 2018-01-02 06:28
Duplicate of #2511

**Closed by wenzhixin** 2018-01-02 06:28 UTC
