### ISSUE TITLE
 make multiple-filter with data-filter-control it possible? 

### ISSUE THREAD

**Issue by rostyslavnikitin** [wenzhixin/bootstrap-table#2872] opened 2017-01-22 01:32 UTC
i need filter data by multiple values of one field.

**Comment by Megido6** [comment] 2017-01-22 07:12
at least disable search name from data-filter-data in table :/
```
<script>
  var tf = {'True': "YES", 'False': "No"};
</script>
```
`<th  data-field="b" data-search="false" data-sortable="false" data-filter-control="select" data-filter-data="var:tf">b</th>`

this filter show rows with some_var>0 and some_var=0 
but my table no have field values with "True"/False" and my table empty after filtering



my table 
id|name|b
1 | xxxx | 654
1 | xxxx | 122
1 | xxxx | 0
1 | xxxx | 12313



how to disable table search on filtering?

**Comment by velkyel** [comment] 2017-01-22 13:43
Yes it's possible.  I think v2.1.1 of bootstrap-table-filter-control.js is broken.  Try v2.1.0.

**Comment by velkyel** [comment] 2017-01-22 15:26
respectively take bootstrap-table-filter-control.js dist/extensions/filter-control directory.  File in src/extensions/filter-control is newer but buggy.

**Comment by Megido6** [comment] 2017-01-22 15:48
my current version work, but i dnt understand how make this search multiple.
i try use multiple-select.js  , but  select not unfold in table->th

**Comment by Megido6** [comment] 2017-01-22 17:11
or if i add custom select form to <th>  how to disable sorting on this select click?

**Comment by djhvscf** [comment] 2017-02-02 21:04
I'm not sure if I understood your question @Megido6 do you want to have select control in every column of your table?

@velkyel do you have any example of the issues related to filter-control??

**Comment by Megido6** [comment] 2017-02-02 23:14
djhvscf, no just multiple select for one column.

**Comment by djhvscf** [comment] 2017-06-19 06:19
@Megido6 this is not supported in this moment.

**Comment by djhvscf** [comment] 2017-06-19 06:19
@velkyel do you have any example of the issues related to filter-control??

**Comment by pmichna** [comment] 2018-03-05 10:50
@djhvscf Are there any plans to implement multiple select filter in near future?

I'm using server side pagination and filtering, so it would be enough to just send the multiple values in params and let backend do the work.

**Comment by rmarzocchi84** [comment] 2018-06-08 15:07
Yes this is a nice function
Here an example using a different library: http://koalyptus.github.io/TableFilter/deep-linking.html

**Comment by UtechtDustin** [comment] 2019-04-16 08:55
Duplicate of #3298

**Closed by UtechtDustin** 2019-04-16 08:55 UTC
Labels: feature, filter-control
