### ISSUE TITLE
bootstrap-table v1.15.5 锁定首行与 colspan 列显示异常

### ISSUE THREAD

**Issue by Jshf** [wenzhixin/bootstrap-table#4677] opened 2019-11-02 06:46 UTC
bootstrap-table v1.15.5 锁定首行与 colspan 列显示异常

使用合并列时出现问题 

环境 : 谷歌  77.0.3865.90  和 IE 11

附件中 我重现了我的问题。

[table.zip](https://github.com/wenzhixin/bootstrap-table/files/3800200/table.zip)

@wenzhixin

**Comment by Jshf** [comment] 2019-11-02 07:13
![image](https://user-images.githubusercontent.com/10703553/68067541-49ab0a80-fd83-11e9-80a1-35f9519651d9.png)

**Comment by UtechtDustin** [comment] 2019-11-03 10:20
Please provide us an example with our [Editor](https://live.bootstrap-table.com/) and explain the issue in english.

**Comment by Jshf** [comment] 2019-11-06 01:06
example : https://live.bootstrap-table.com/code/Jshf/1042.
version : bootstrap-table v1.15.5
env: chrome 77.0.3865.90 & IE 11 (and so on)

When I use “colspan” to merge columns, extra columns appear on the right。

thanks for your reply.

**Comment by UtechtDustin** [comment] 2019-11-06 10:45
duplicate of #4562

**Closed by UtechtDustin** 2019-11-06 10:45 UTC
Labels: needs example, needs translation
