### ISSUE TITLE
Resizable handlebar height isn't reduced after reducing pageSize

### ISSUE THREAD

**Issue by Moutard3** [wenzhixin/bootstrap-table#5857] opened 2021-09-06 14:46 UTC
**Bootstraptable version(s) affected**: 1.18.3

**Description**  
When using the Resizable extension, showing more lines (10 -> 25) then showing less lines (25 -> 10) causes blank space to appear with a scrollbar.
Clicking an handlebar to resize fixes the bug.

**Example**  
The official example has this bug
https://live.bootstrap-table.com/example/extensions/resizable.html

![Bug](https://snipboard.io/YPuSQD.jpg)

**Possible  (optional)**  
Handlebars height is not reduced after reducing page size.

**Additional context**  
Chrome 92 / W10

**Comment by UtechtDustin** [comment] 2021-10-01 19:16
I gues this issue is fixed in the current version, maybe it was chrome bug.
I can't reproduce it in Chrome 94 and Firefox 92.
If you think this bug still exists please let us know.

https://user-images.githubusercontent.com/13292481/135674510-507bace3-2eb8-4307-9860-00058b426090.mp4

**Comment by Moutard3** [comment] 2021-10-04 15:09
Just tried with Chrome 94 & Firefox 92 and I still got the bug. On your video, we can see a scroll bar on the table, so it seems that you still have it too.

**Comment by UtechtDustin** [comment] 2021-10-04 17:55
@Moutard3 you're right !
I switched from 10 to 25 and back, after that i checked your screenshot and my table.
I don't had the space between entries and pagination, but i overlooked the scroll bar!

**Comment by UtechtDustin** [comment] 2021-10-04 18:03
Tested it again and it seems it is already fixed in your develop Branch, so it should be fixed in the next version.
Example: https://live.bootstrap-table.com/code/UtechtDustin/9170

**Closed by UtechtDustin** 2021-10-04 18:03 UTC
Labels: confirmed, resizable, Bug
