### ISSUE TITLE
The Columns button tag has the wrong title text

### ISSUE THREAD

**Issue by earlseay** [wenzhixin/bootstrap-table#4324] opened 2019-04-25 13:39 UTC
### The Columns button tag has the wrong title text

A summary of the issue and the browser/OS environment in which it occurs. If suitable, include the steps required to reproduce the bug.

All browsers. View source on the columns and see that the columns button (inside the div for the dropdown) has the title text as "Fullscreen". This should say "Columns". It looks like a copypasta mistake where you just included the wrong text formatter method in the title text of the button.

Bonus feature:

It would also be nice to have an option to show the button text on the toolbar buttons. Our UI/UX designer says it's always helpful to have text with an icon as icons aren't always easy to deduce their meaning.

**Comment by UtechtDustin** [comment] 2019-04-25 14:59
Thank you for the bug report!

Its a duplicate of #4291 #4289 and fixed in https://github.com/wenzhixin/bootstrap-table/commit/78465c7eac29a51645a6e4917fb5e5d58a63dc21.
Will be fixed in the next version of the bootstrap-table.

Consider to implement an option to show the `title`-text next/under the icons. @wenzhixin @djhvscf 
In my opinion its a nice to have.

**Comment by wenzhixin** [comment] 2019-04-25 15:42
Do you mean @UtechtDustin ?
```js
$table.bootstrapTable({
  formatRefresh: function () {
    return 'Refresh Title'
  }
})
```

**Comment by UtechtDustin** [comment] 2019-04-25 15:52
I think help mean something like that: http://jsfiddle.net/m8wjzc75/ (quick and dirty example)

**Comment by wenzhixin** [comment] 2019-06-06 00:15
@UtechtDustin Consider this as a new feature. We can add an option in the future version.

**Closed** 2019-06-08 22:45 UTC
Labels: feature, has PR, js
