### ISSUE TITLE
onReorderRow not working

### ISSUE THREAD

**Issue by Kenzo800** [wenzhixin/bootstrap-table#6375] opened 2022-09-06 10:19 UTC
### Description

When I am working on bootstrap-table online editor, the onReorderRow function works.
https://live.bootstrap-table.com/code/Kenzo800/12712

But it dosen't on my own application.

below is my work (I am not showing all the code)

```
<link rel="stylesheet" href="https://XXX.com/css/bootstrap.css">
<link rel="stylesheet" href="https://XXX.com/css/dist/bootstrap-table.css" />
<link rel="stylesheet" href="https://XXX.com/css/dist/extensions/reorder-rows/bootstrap-table-reorder-row.css" />
```
//......
```
<table 
  id="table" 
  class="table table-bordered table-striped"
  data-toggle="table" 
  data-pagination="true"
  data-side-pagination="client"
  data-page-size="10"
  data-page-list="[10, 30, All]"
  data-use-row-attr-func="true"
  data-reorderable-rows="true">
    <thead>
        <tr>
            <th data-field="id">ID</th>
            <th data-field="item_name">item</th>
            <th data-formatter="updateFormatter" data-events="updateEvents" data-width="80">update</th>
            <th data-formatter="deleteFormatter" data-events="deleteEvents" data-width="80">delete</th> 
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>
```
//......
```
<script src="https://XXX.com/js/jquery/node_modules/jquery/dist/jquery.js"></script>
<script src="https://XXX.com/js/bootstrap.js"></script>
<script src="https://XXX.com/js/dist/bootstrap-table.min.js"></script>
<script src="https://XXX.com/js/dist/extensions/reorder-rows/bootstrap-table-reorder-rows.min.js"></script>
<script src="https://XXX.com/js/tablednd/node_modules/tablednd/dist/jquery.tablednd.min.js"></script>
```
//......
```
$(document).ready(function() {
    var data = <?php echo $item_json; ?>;
    $('#table').bootstrapTable({
        onReorderRow: function(newData) {
            alert("haha")
            return true;
        }
    });
    $('#table').bootstrapTable('load', data);
});
```

//- The data from php server looks like this 
`[{"id":"1","item_name":"A"},{"id":"2","item_name":"B"},{"id":"3","item_name":"C"}]`

It is find for generating the table and make it reorderable. However, the onReorderRow function not triggered.

### Example(s)

https://live.bootstrap-table.com/code/Kenzo800/12712

**Comment by UtechtDustin** [comment] 2022-10-01 12:53
Can't reproduce the issue on my locally.
I copied your example (but removed the `data-events`, because there are missing on your example.

Maybe you are using a not up to date cdn ?
Please provide us an full example (which can be c&p without modifications).

https://user-images.githubusercontent.com/13292481/193410482-7b5c10f7-0d36-4d62-b352-22cab29fb5b1.mp4

**Comment by wenzhixin** [comment] 2022-10-07 13:15
Have you solved your problem? @Kenzo800

**Comment by UtechtDustin** [comment] 2022-12-21 23:07
I'm going to close this issue, because we don't got any response from you.
If you still need help, let us now.

**Closed by UtechtDustin** 2022-12-21 23:07 UTC
Labels: help-wanted, needs example
