### ISSUE TITLE
Trim text in cell on column resize

### ISSUE THREAD

**Issue by faruk77** [wenzhixin/bootstrap-table#1134] opened 2015-07-06 06:17 UTC
Hi, 
I'm using colresizer plugin please tell me how to trim text in cell on column resize..can please provide a example ?

**Comment by djhvscf** [comment] 2015-07-06 13:38
Well I think you can bind this event 'onResizableResize' and add your logic

**Comment by dabros** [comment] 2015-07-07 03:19
duplicate of #1126

**Comment by djhvscf** [comment] 2015-07-07 04:04
Thanks @dabros

**Closed by djhvscf** 2015-07-07 04:04 UTC
Labels: extension
