### ISSUE TITLE
fail to render editable columns after 'refreshOptions'

### ISSUE THREAD

**Issue by luryson** [wenzhixin/bootstrap-table#2120] opened 2016-03-28 15:08 UTC
https://github.com/wenzhixin/bootstrap-table/blob/develop/src/extensions/editable/bootstrap-table-editable.js#L63
When first time initializing the table here, `column.formatter` has been  overrode.'refreshOptions' method still call initTable function while column.formatter is no longer the function I defined. 
So I got this:
 
![image](https://cloud.githubusercontent.com/assets/7643503/14080743/8658dfe4-f539-11e5-983a-34cde7d015af.png)
for the first time, and this after 'refreshOptions': 
![image](https://cloud.githubusercontent.com/assets/7643503/14080773/a41fb480-f539-11e5-8aa4-22fa674ca1fc.png)
check this: https://github.com/luryson/bootstrap-table/commit/761f8517100b95a2df4952f35f5b0dfd3a7a9e8f

**Comment by djhvscf** [comment] 2016-03-28 19:36
sounds good.. can you provide an example?

**Comment by airtonjr** [comment] 2016-03-29 01:52
Maybe same thing here:

Export And Editable Plugin can't work together. Possible bug? #2116

**Comment by luryson** [comment] 2016-03-29 03:23
@airtonjr If you have better way to solve this problem, please let me know

**Comment by airtonjr** [comment] 2016-03-29 03:34
@luryson I am trying with no success.

**Comment by luryson** [comment] 2016-03-29 03:44
@airtonjr  I solved my problems temporarily  https://github.com/luryson/bootstrap-table/commit/761f8517100b95a2df4952f35f5b0dfd3a7a9e8f .I am not sure your problem is exactly the  same one, just try it. I store the formatter function I defined in `column` as  `column._formatter`. When 'refreshOptions' method is called, `column._formatter` will be checked and called firstly.

**Comment by luryson** [comment] 2016-03-29 05:23
@djhvscf http://runjs.cn/detail/jod6mf1k here is the example. Every time I press 'press me' button I got this:
![image](https://cloud.githubusercontent.com/assets/7643503/14098671/01188910-f5b1-11e5-90d6-fd1e51c0bd6b.png)  
![image](https://cloud.githubusercontent.com/assets/7643503/14098681/12d73f66-f5b1-11e5-9049-3db9866b4e1b.png)

**Comment by djhvscf** [comment] 2016-03-29 06:32
ok, but can you provide an example of your solution?

**Comment by luryson** [comment] 2016-03-29 06:51
@djhvscf  Sorry.  The example above has been modified with my solution.http://runjs.cn/detail/jod6mf1k

**Comment by djhvscf** [comment] 2016-03-29 06:55
great... lets create a new **PR**

**Comment by airtonjr** [comment] 2016-03-29 14:17
@luryson Thank you for this information, but my problem still there. Every time when I select an option in the dropdown to export it brings to me the error. 

Seems the problem is in this piece of code (line 63 - 80) :

 ```
 var _formatter = column.formatter;
            column.formatter = function (value, row, index) {
                var result = _formatter ? _formatter(value, row, index) : value;

                $.each(column, processDataOptions);

                $.each(editableOptions, function (key, value) {
                    editableDataMarkup.push(' ' + key + '="' + value + '"');
                });

                return ['<a href="javascript:void(0)"',
                    ' data-name="' + column.field + '"',
                    ' data-pk="' + row[that.options.idField] + '"',
                    ' data-value="' + result + '"',
                    editableDataMarkup.join(''),
                    '>' + '</a>'
                ].join('');
            };
```

**Comment by airtonjr** [comment] 2016-04-02 00:25
@djhvscf  Hi, just to let you know.

When I am using just "refresh" the table would refresh even with editable data but when I am using "refreshOptions" and start list the options inside the refresh would bring the error. 

```
 $('#toolbar').find('select').change(function () {                
                $table.bootstrapTable('refreshOptions', {
                exportDataType: $(this).val()
            });
            });
```

**Comment by djhvscf** [comment] 2016-04-02 01:42
See this: https://github.com/wenzhixin/bootstrap-table/pull/2123

**Comment by airtonjr** [comment] 2016-04-02 04:03
@djhvscf  I have seen that. 

If you just go in the column name and put "editable: true" and press the button the error will show and the age will show in the right format because in that code he is using: 

`formatter: function (value, row, index) { return value - 1; }`

So, if I use:

`formatter: function (value, row, index) { return value ; }`

In the column "name" it will bring to me the value but without that the error will pop.

**Comment by luryson** [comment] 2016-04-03 11:46
@airtonjr can you provide an example like mine?

**Comment by airtonjr** [comment] 2016-04-03 16:35
@luryson You can use your own example and see. (http://runjs.cn/code/jod6mf1k) 

You just need to add the line "editable: true" (line 20).

```
field: 'name',
			title: 'Name',
			editable: true
```

And press the button and you will se the error.

**Comment by luryson** [comment] 2016-04-04 04:00
@airtonjr yeah, thanks for pointing it out. It's really a little tricky and actually the same problem. Here is an attempt, 
![image](https://cloud.githubusercontent.com/assets/7643503/14237871/59ff31aa-fa5c-11e5-99a0-afe250d8d8a0.png)
@djhvscf I have closed my pr for this problem. It seems that I didn't solve this problem exactly.

**Comment by airtonjr** [comment] 2016-04-04 17:49
@luryson Yep, and when I try to use two or more formatter the table didn't load. It will load if I have just one formatter. 

@wenzhixin Some idea about it? Thanks.

**Comment by luryson** [comment] 2016-04-05 02:24
@airtonjr I think every column needs a `formatter` here, which means if we don't define `formatter`, it should be defined by default, such as (before line 63: https://github.com/luryson/bootstrap-table/blob/develop/src/extensions/editable/bootstrap-table-editable.js#L63)
```
if (! column.formatter) {
    column.formatter = function (value, row, index) {
        return value;
    }
}
```
here is the example: http://runjs.cn/detail/xl9ndtds. I would prefer if you provide your own example in case that I misunderstand what you mean.

**Comment by airtonjr** [comment] 2016-04-19 03:25
@wenzhixin Sorry for bother you, but do you have any news about this issue? 

Thank you.

**Comment by wenzhixin** [comment] 2016-07-02 03:10
Merged the PR, I think the problem should be solved: http://jsfiddle.net/e3nk137y/7505/

**Closed by wenzhixin** 2016-07-02 03:10 UTC
Labels: confirmed, export, extension
