### ISSUE TITLE
data-side-pagination="server" not working

### ISSUE THREAD

**Issue by AnThO16** [wenzhixin/bootstrap-table#863] opened 2015-05-12 14:20 UTC
Hello, i'm new on Github

i have to make a boostrap table with sorting/pagin/filtering lot of datas in ASP MVC application.

i found boostrap-table and it look great !

i have a problem when i add data-pagination="true" and data-side-pagination="server" but the table is empty or "No matching records found". without paging it working.

this is my controller 

  public JsonResult JsonGrid()
        {
            List<Resultat> resultats = uow.Repository<Resultat>().GetAlls().OrderByDescending(e => e.DateResultat).ToList();

            List<ResultatViewModel> ListeResultatViewModel = new List<ResultatViewModel>();
            foreach (var result in resultats)
            {

                ResultatViewModel resultatViewModel = new ResultatViewModel();

                resultatViewModel.PMRQTOTM = result.PMRQTOTM;
                resultatViewModel.PMID = result.PMID;
                resultatViewModel.PMRQ = result.PMRQ;
                
                ListeResultatViewModel.Add(resultatViewModel);
            }

            return Json(ListeResultatViewModel, JsonRequestBehavior.AllowGet);
}

My PartialView with my tab 

 table id="gridTable" data-toggle="table" data-url="/Resultats/JsonGrid"
       data-pagination="true"
       data-page-list="[5, 10, 20, 50, 100, 200]"
       data-search="true"
       data-height="300">
    thead
        tr
            th data-sortable="true" data-field="Flag">PEC th>
            th data-field="PMRQTOTM">PMRQTOTM th>
            th data-field="PMRQ">PMRQ th>
        tr
    thead
table>

and my main view 

 div id="Render">@Html.Partial("Grille", Model)div

Thanks !!

**Comment by jtrumbull** [comment] 2015-05-17 16:08
See answer on issue # 876:
https://github.com/wenzhixin/bootstrap-table/issues/876

**Comment by AnThO16** [comment] 2015-05-19 08:49
i test his solution but still not work for me..

**Comment by AnThO16** [comment] 2015-05-19 09:05
my json result 
![jsonresult](https://cloud.githubusercontent.com/assets/12412756/7699243/d94e7378-fe16-11e4-8846-4230758835b5.PNG)

and my controller
![list](https://cloud.githubusercontent.com/assets/12412756/7699249/e229bdcc-fe16-11e4-990e-bf3b88b58f74.PNG)


Thanks for your help

**Comment by AnThO16** [comment] 2015-05-19 09:10
Controller 
![controller](https://cloud.githubusercontent.com/assets/12412756/7699366/a99ff0c4-fe17-11e4-9f75-8bd5e46fc18b.PNG)

**Comment by AnThO16** [comment] 2015-05-19 10:11
this work in Javascript like this 
![jquery](https://cloud.githubusercontent.com/assets/12412756/7700560/f2d541d8-fe1f-11e4-92b5-4b384cf998d3.PNG)

but not like this 
![data-table](https://cloud.githubusercontent.com/assets/12412756/7700612/3c4b7e0e-fe20-11e4-8908-4478bb87850f.PNG)

**Comment by jtrumbull** [comment] 2015-05-19 15:09
I don't have an ASP instance on this machine, but I ran the same configuration on my side (using a JSON file) and is working fine. Your JSON response appears to be correct. Installing via `html` is simply creating the settings array from the `data` attributes, so both examples are essentially doing the same thing -weird that it would work on one and not the other.

1) Could you inspect the table and tell me the result of `@Url.Action('JsonGrid')`
2) Could you confirm that you get the JSON result (as shown above) when installing via `data` attributes.

**Comment by AnThO16** [comment] 2015-05-19 16:00
Thanks for your help 

1) ![captureactionresult](https://cloud.githubusercontent.com/assets/12412756/7707540/96ccede2-fe50-11e4-92f7-6a6bafe4d894.PNG)

this is  my table...
![datatable-view](https://cloud.githubusercontent.com/assets/12412756/7707557/b36bf844-fe50-11e4-8d82-11e525202c3e.PNG)

2)
![capturejson](https://cloud.githubusercontent.com/assets/12412756/7707629/fdca264a-fe50-11e4-9dc4-d63e561a6974.PNG)

**Comment by jtrumbull** [comment] 2015-05-19 18:02
A few more things to check:

1) I am trying to figure out what the end result of `data-url` is. Making sure `@Url.Action('JsonGrid')` isn't outputting unexpected results. The original table with `data` attributes is nested within the `div.fixed-table-body`. Could you provide the value of `data-url`?

2) Can you confirm nothing on your page, besides `$('#tableab')`, is triggering `JsonGrid?order=asc` from the server. If something else is: would it be possible to isolate your html install for debugging purposes?

3) Are there any errors being thrown at the console?

4) If not done already, run the following at the bottom of your page, and let us know the results (if any):
```javascript
$(document).ready(function() {
				
	$('#tableab').on('load-success.bs.table', function(e, data){
		console.log('Success', data);
	});
				
	$('#tableab').on('load-error.bs.table', function(e, status){
		console.log('Error', status);
	});
			
});
```

**Comment by AnThO16** [comment] 2015-05-19 18:31
1) the table is in a partial view which is load on my main view 
![capturemainview](https://cloud.githubusercontent.com/assets/12412756/7710573/1df7a35c-fe65-11e4-80d1-274ca108ffc0.PNG)

![captureform](https://cloud.githubusercontent.com/assets/12412756/7710682/bbd15640-fe65-11e4-8b00-49243e8f9b36.PNG)

about Url : Resultats is my controller and Jsongrid my action

3) i don't see errors

4) nothing append

**Comment by jtrumbull** [comment] 2015-05-19 20:22
I see the rendered table above says "Showing 1 to 10". Try running this at the bottom of your code:

```javascript
console.log( $('#tableab').data('bootstrap.table') );
```

Are the `data` or `options.data` properties empty arrays?

**Comment by AnThO16** [comment] 2015-05-20 07:02
no there are 50 objects 
![data](https://cloud.githubusercontent.com/assets/12412756/7720556/ebd72d06-fece-11e4-8f54-958302ebfe75.PNG)

![console](https://cloud.githubusercontent.com/assets/12412756/7720559/f1fbafcc-fece-11e4-835b-99e938b5a7ec.PNG)

**Comment by AnThO16** [comment] 2015-05-20 07:23
with server side pagination, sort and filters work ?

**Comment by jtrumbull** [comment] 2015-05-20 12:17
What is the length of your JSON response?

**Comment by AnThO16** [comment] 2015-05-20 12:41
where can i see that?

**Comment by jtrumbull** [comment] 2015-05-20 13:46
The network response from `JsonGrid?order=asc`, what is the length of `rows`?

**Comment by AnThO16** [comment] 2015-05-20 14:11
44k

![capturelength](https://cloud.githubusercontent.com/assets/12412756/7727700/c92d6248-ff0a-11e4-9c9c-7a0c04e26d81.PNG)

**Comment by jtrumbull** [comment] 2015-05-20 14:17
No, the count of the `rows` array. I.e. `10` or `50`?

**Comment by AnThO16** [comment] 2015-05-20 14:19
ah sorry 50

**Comment by jtrumbull** [comment] 2015-05-20 15:01
Hmmmm.... So your server is responding with 50 `rows`, your table `data` is an array of 50 `rows`, and you say `load-success.bs.table` and `load-error.bs.table` does not trigger -that makes absolutely no sense, from my understanding, the response has to either succeed or fail. Unless it is breaking before the trigger, or if you have something else on your page injecting 50 rows into your `$('#tableab')`.

1) Confirm that no other scripts on your page are modifying `$('#tableab').bootstrapTable()`.

2) Include the following code, right after you include your `bootstrap-table.js` file. I modified the request handler to output (to the console) the server response and some text about what it is doing. You can inspect the console of the jsFiddle (below) to see what the response should look like (note that the table is to your exact configuration, and working as expected). Let us know the result.

jsFiddle: http://jsfiddle.net/joeycakes/e3nk137y/1688/

```javascript
(function ($) {
    
    'use strict';
    
    var calculateObjectValue = function (self, name, args, defaultValue) {
        if (typeof name === 'string') {
            // support obj.func1.func2
            var names = name.split('.');

            if (names.length > 1) {
                name = window;
                $.each(names, function (i, f) {
                    name = name[f];
                });
            } else {
                name = window[name];
            }
        }
        if (typeof name === 'object') {
            return name;
        }
        if (typeof name === 'function') {
            return name.apply(self, args);
        }
        return defaultValue;
    };
    
    var BootstrapTable = $.fn.bootstrapTable.Constructor;
    
    BootstrapTable.prototype.initServer = function (silent, query) {
        var that = this,
            data = {},
            params = {
                pageSize: this.options.pageSize === this.options.formatAllRows() ?
                    this.options.totalRows : this.options.pageSize,
                pageNumber: this.options.pageNumber,
                searchText: this.searchText,
                sortName: this.options.sortName,
                sortOrder: this.options.sortOrder
            },
            request;

        if (!this.options.url && !this.options.ajax) {
            return;
        }

        if (this.options.queryParamsType === 'limit') {
            params = {
                search: params.searchText,
                sort: params.sortName,
                order: params.sortOrder
            };
            if (this.options.pagination) {
                params.limit = this.options.pageSize === this.options.formatAllRows() ?
                    this.options.totalRows : this.options.pageSize;
                params.offset = this.options.pageSize === this.options.formatAllRows() ?
                    0 : this.options.pageSize * (this.options.pageNumber - 1);
            }
        }

        if (!($.isEmptyObject(this.filterColumnsPartial))) {
            params['filter'] = JSON.stringify(this.filterColumnsPartial, null);
        }

        data = calculateObjectValue(this.options, this.options.queryParams, [params], data);

        $.extend(data, query || {});

        // false to stop request
        if (data === false) {
            return;
        }

        if (!silent) {
            this.$loading.show();
        }
        request = $.extend({}, calculateObjectValue(null, this.options.ajaxOptions), {
            type: this.options.method,
            url: this.options.url,
            data: this.options.contentType === 'application/json' && this.options.method === 'post' ?
                JSON.stringify(data) : data,
            cache: this.options.cache,
            contentType: this.options.contentType,
            dataType: this.options.dataType,
            success: function (res) {
                console.log(res);
                console.log('Calculating Object Value of Response...');
                res = calculateObjectValue(that.options, that.options.responseHandler, [res], res);
                console.log('Loading response to Table...');
                that.load(res);
                console.log('Triggering `load-success`...');
                that.trigger('load-success', res);
            },
            error: function (res) {
                console.log(res);
                console.log('Triggering `load-error`...');
                that.trigger('load-error', res.status);
            },
            complete: function () {
                if (!silent) {
                    that.$loading.hide();
                }
            }
        });

        if (this.options.ajax) {
            calculateObjectValue(this, this.options.ajax, [request], null);
        } else {
            $.ajax(request);
        }
    };
    
})(jQuery);
```

**Comment by AnThO16** [comment] 2015-05-20 15:56
i test again your load-success.bs.table and load-error.bs.table and this is the result 
![capturesucces](https://cloud.githubusercontent.com/assets/12412756/7730257/7f0e16e4-ff19-11e4-815e-31ecbd1eb8ce.PNG)

**Comment by AnThO16** [comment] 2015-05-20 17:09
this is the result with your function 
![capture](https://cloud.githubusercontent.com/assets/12412756/7731854/c26324a2-ff23-11e4-9339-70f25559caa9.PNG)

**Comment by jtrumbull** [comment] 2015-05-20 17:14
I'm struggling to recreate this issue. if you are getting a successful load, the `data-side-pagination="server"` is working properly -problem seems to be with the render. Couple more things to try:

1) Confirm you are using the most up to date [`bootstrap-table.js`](https://github.com/wenzhixin/bootstrap-table/blob/master/src/bootstrap-table.js) and [`bootstrap-table.css`](https://github.com/wenzhixin/bootstrap-table/blob/master/src/bootstrap-table.css) files.

2) List every extension or locale that you are using (if any).

3) Add the `data-page-size="50"` attribute. Confirm you get the text `Showing 1 to 50 of 50 rows`.

4) Instead of logging the server response, try to re-initialize the body on `load-success.bs.table`
```javascript
$(document).ready(function() {

    $('#tableab').on('load-success.bs.table', function(e, data){
        var table = $('#tableab').data('bootstrap.table');
        table.initBody();
    });

});
```

**Comment by AnThO16** [comment] 2015-05-20 17:29
1) yes i use the lastest file and the table load correctly in Javascript..

2) 
![capturefiles](https://cloud.githubusercontent.com/assets/12412756/7732067/54dcdd22-ff25-11e4-93b6-4c9709522565.PNG)

3)i confirm the showing text !

4) nothing append

**Comment by AnThO16** [comment] 2015-05-20 17:39
In Javascript i have this but sort and filter don't work (cause of server side pagination i guess..)
![capturejavascript](https://cloud.githubusercontent.com/assets/12412756/7732345/93fa6946-ff27-11e4-95be-4a7d7e81b42b.PNG)

this is crazy ..

**Comment by jtrumbull** [comment] 2015-05-20 18:49
Crazy indeed. 

Looks like your controller needs some additional logic to handle sorting and searching. The client sends the following keys to the server when using `data-query-params="Else"`: `pageSize`, `pageNumber`, `searchText`, `sortName`, `sortOrder`. I'm not too familiar with the `bootstrap-table-filter` extension, but I thought it was client-side only -filtering rows presently in the html. You may want to post an issue in [that](https://github.com/lukaskral/bootstrap-table-filter) repository, about using in conjunction with server pagination, for more clarity.

I hate unsolved problems, but need to get back to my real job for a little bit, then come back with a fresh set of eyes.

My biggest struggle is not being able to see the issue for myself. Would it be possible for you to create a repository including: 
1) `index.html` with your table configuration
2) `assets/` directory including all `css/` and `js/` files being used by your view
3) `data.json` (saved from `JsonGrid?order=asc` response)
\* Confirm that the issue is still happening when isolated.

This way I can branch and play around, instead of blindly suggesting debugging scenarios.

**Comment by AnThO16** [comment] 2015-05-21 08:47
i maked a html with my js and css and dataJson

the table is empty with the jquery 1.10.2 but the 1.11.3 works

the pagination don't work (in each page there are the complete list)

i share this file in my DropBox

https://www.dropbox.com/s/nc9mp1nngqmdle3/Index%20HTML.rar?dl=0

**Comment by jtrumbull** [comment] 2015-05-21 13:07
Perfect, I will play with that for a time.

The pagination doesn't work because your controller is returning `total: 50` and `rows: [Array 50]`. `total` should describe the total number of records in your model. and `rows` should describe the rows you want to display on that particular page. You would use the `pageSize` and `pageNumber` parameters to buid your list. See [this controller](https://cloud.githubusercontent.com/assets/12445390/7656002/b0824b5a-faf5-11e4-9e47-3fefd00b27c9.png) taken from [Issue # 876](https://github.com/wenzhixin/bootstrap-table/issues/876) -looks like you guys are using the same framework.

**Comment by jtrumbull** [comment] 2015-05-21 14:11
Your dropbox file is working fine on my side with both jquery versions (`1.10.2` and `1.11.3`). Did you confirm that your `index.html` isn't working?

**Comment by AnThO16** [comment] 2015-05-21 14:21
yes it's work only with firefox.

But still not working on my mvc application..

**Comment by djhvscf** [comment] 2015-05-21 14:25
Did you already review the errors console?

**Comment by AnThO16** [comment] 2015-05-21 14:45
succes .. but empty table..

**Comment by wenzhixin** [comment] 2015-05-21 15:33
Do you open index.html in a server @AnThO16 ?

**Comment by AnThO16** [comment] 2015-05-21 15:36
no, it was just for test, i used a controller MVC to pass the json data to my table but..

**Comment by wenzhixin** [comment] 2015-05-21 15:42
But your index.html is working fine. Maybe you can use firebug to debug your table and find the problem.

**Comment by AnThO16** [comment] 2015-05-21 16:16
i used it ... but i don't find errors..

the controller send json ( with pagination)
![capturecontent](https://cloud.githubusercontent.com/assets/12412756/7753368/4aca13ac-ffe5-11e4-9f88-defa773b3044.PNG)

The json seems correct
![capturearray](https://cloud.githubusercontent.com/assets/12412756/7753367/436172fe-ffe5-11e4-8065-13df793d25f3.PNG)

But display data is empty..
![capturetable](https://cloud.githubusercontent.com/assets/12412756/7753363/3fa7d356-ffe5-11e4-80c0-1b0220b30501.PNG)

**Comment by jtrumbull** [comment] 2015-05-21 17:15
What do we know?
1) No errors are being thrown
2) The server request is working as expected
3) The data is properly loaded into the `bootstrapTable` instance (`data` and `options.data`)
4) The issue is resolved when installing via javascript -isolated to lazy-load install
5) Problem is not easily recreated on other machines
(scratching my head)

**Comment by AnThO16** [comment] 2015-05-21 18:22
you think, this is ASP MVC issue ?

**Comment by wenzhixin** [comment] 2015-05-21 23:53
I think it maybe the css problem, check the dom data use firebug please.

**Comment by AnThO16** [comment] 2015-05-22 06:41
this my html render 

https://www.dropbox.com/s/nbj2t3vjfld5ymz/Table.html?dl=0

**Comment by wenzhixin** [comment] 2015-05-27 10:25
Have you solved this problem @AnThO16 ?

**Comment by AnThO16** [comment] 2015-05-27 10:37
no :'(

**Comment by jtrumbull** [comment] 2015-05-27 22:28
Your `#tableab` is a `<ul>` element.

**Comment by AnThO16** [comment] 2015-05-28 10:42
I don't understand why...

**Comment by jtrumbull** [comment] 2015-05-28 11:25
Me neither, but I don't believe this I something bootstrap-table is doing. A quick way to check is removing the data-toggle=table, and see if you have a ul or table element.

**Comment by djhvscf** [comment] 2015-06-29 03:39
Have you solved this problem @AnThO16 ?

**Comment by wenzhixin** [comment] 2015-07-17 01:49
Let's close this issue, OK?

**Closed by wenzhixin** 2015-07-17 01:49 UTC
Labels: help wanted

**Comment by torisoft** [comment] 2016-07-10 09:19
Hi
I have same issue too

**Comment by gaurav22031987** [comment] 2017-02-13 16:33
Hi,
Table is binding, but not showing pagination on UI.

**Comment by gaurav22031987** [comment] 2017-02-13 16:34
![image](https://cloud.githubusercontent.com/assets/3023558/22892377/5b6cca1e-f238-11e6-99bb-ebcb3624bd79.png)

   public JsonResult JsonGrid(string sort,string direction,int pageNumber,int pageSize)
        {
            int total = 3;
            var skip = (pageNumber - 1) * pageSize;
            List<Employee> employees = new List<Employee>();
            employees.Add(new Employee() { firstName = "A", lastName = "Gupta", Stars = 1, Description = "Test" });
            employees.Add(new Employee() { firstName = "B", lastName = "Gupta", Stars = 1, Description = "Test" });
            employees.Add(new Employee() { firstName = "C", lastName = "Gupta", Stars = 1, Description = "Test" });

            var list= employees.Select(m => new Employee
            {
                firstName=m.firstName,
                lastName=m.lastName,
                Description=m.Description
            }).ToList().Skip(skip).Take(pageSize);
            return Json(new { total = total, rows = list }, JsonRequestBehavior.AllowGet);
        }

**Comment by RavinderSandhu** [comment] 2017-06-15 22:30
Hi @gaurav22031987, @AnThO16 ,
I am using MVC, check this, working for me

var UserPageSetting=30;
$(document).ready(function () {
       ConfigTable();
	LoadData();
});

function ConfigTable() {
    $(#myTable").bootstrapTable({
        sidePagination: 'server',
        pagination: true,
        pageSize: UserPageSetting,
        pageList: [UserPageSetting],
        paginationDetailHAlign: 'left',
        undefinedText: '-',
        paginationHAlign: 'left',
        smartDisplay: false,
        striped: true,
        cache: false,
        sortable: true,
        silentSort: true
    });
}
function LoadData(){
	 $.ajax({
        type: 'POST',
        url: '/your url',
        data: JSON.stringify({ 'search': searchDTO, 'page': page, 'pageSize': pageSize, "sort": sort, "direction": direction }),
        contentType: 'application/json; charset=utf-8',
        dataType: 'json',
        success: function (result) {
			 // result is my json class
                var data = result.Data;
                var totalCount = parseInt(result.Data.TotalRecords);
                $$(#myTable").bootstrapTable('load', { total: totalCount, rows: data });
        },
        error: function (xhr, textStatus, errorThrown) {
           
        }
    });
}

**Comment by aimensasi** [comment] 2018-03-23 03:45
I am having the same trouble on Laravel. I am receiving the response but the data is not loaded. The `onLoadSuccess` function returns the following::

![res2](https://user-images.githubusercontent.com/13252355/37810533-8bd06988-2e8f-11e8-9558-ba2fca499ee3.jpeg)


I have tried the following, but with no luck 

```
$table.on('load-success.bs.table', function(e, data){
    console.log(data, e);
    var table = $(this).data('bootstrap.table');
    table.initData();
    table.initBody();
  });

```
The method is called and the data is received but nothing is loading to the table.

**Comment by aimensasi** [comment] 2018-03-23 03:54
never mind, I fixed it

**Comment by jimgit** [comment] 2018-03-23 18:59
Post your fix - others may have the same problem.

**Comment by aimensasi** [comment] 2018-07-11 21:29
just return a response like the following

```
['rows' => ResultList, 'total' => listCount]
```

I can give you a sample code in php

**Comment by snomula-idc** [comment] 2018-07-11 21:35
@aimensasi: Thanks for quick reply. That would be great, if you provide me the sample.

**Comment by aimensasi** [comment] 2018-07-11 21:36
This is a sample code in php/Laravel

```
public function all($request){
    $sort = $request->sort ? $request->sort : 'created_at';
    $order = $request->order ? $request->order : 'desc';
    $limit = $request->limit ? $request->limit : 10;
    $offset = $request->offset ? $request->offset : 0;
    $query = $request->search ? $request->search : '';

		$generalManagers = GeneralManager::where('ic', 'like', "%{$query}%")->orderBy($sort, $order);
    $listCount = $generalManagers->count();

    $generalManagers = $generalManagers->limit($limit)->offset($offset)->get();

    return respond(['rows' => $this->transformCollection($generalManagers), 'total' => $listCount]);
  }
```

This will take care of all, from sorting, pagination to search

Hope this can help.

**Comment by snomula-idc** [comment] 2018-07-11 21:38
Thank you:)

**Comment by aimensasi** [comment] 2018-07-11 21:39
Not a problem

**Comment by kongcheeping** [comment] 2019-06-27 07:09
@aimensasi 
why is it im having this error? where does the function come from?
Call to undefined function App\Http\Controllers\API\transformCollection()
