### ISSUE TITLE
Problem using orderColumns method. 

### ISSUE THREAD

**Issue by gui55gui** [wenzhixin/bootstrap-table#5243] opened 2020-08-07 15:06 UTC
**Bootstraptable version(s) affected**:
1.17.1

**Description**  
When I order the columns using the method it orders everything right, however, after some iteration within the table the values are lost and returned to the old places where the columns were, and only the title of the columns remain in place.

**Example**  
https://live.bootstrap-table.com/code/gui55gui/4296

**Additional context**  
It occurs by generating the table from the side of the javascript.

**Comment by gui55gui** [comment] 2020-08-07 19:22
Hello @UtechtDustin , do you have an estimated date to review reported bugs? Just to know

**Comment by UtechtDustin** [comment] 2020-08-07 19:33
No sorry, we will check it as soon we have time for it.

**Comment by gui55gui** [comment] 2020-08-07 19:35
Okay, I'll be waiting, thanks for the feedback.

**Comment by UtechtDustin** [comment] 2020-09-13 17:43
@gui55gui do you have a way to reproduce it ?
Currently im not able to reproduce it..

**Comment by djhvscf** [comment] 2020-09-17 03:51
I'm able to reproduce it. Marked as bug

**Comment by UtechtDustin** [comment] 2020-09-17 06:46
> I'm able to reproduce it. Marked as bug

Could you please describe how ?

**Comment by djhvscf** [comment] 2020-09-17 15:55
If you search for '0' and then play with the buttons you will see the error

**Comment by UtechtDustin** [comment] 2020-09-17 16:21
Maybe its browser dependent ?
I still can't reproduce it, im searching for `0` and quickly/random click on the reorder buttons.

**Comment by djhvscf** [comment] 2020-09-17 20:53
Oh..let me try it in different browsers

**Comment by ryanp2317** [comment] 2020-12-22 18:12
Is this possibly related to the issue I'm seeing here? Table is using server side processing, reorder works, cookie stores everything including the reorder, but on page refresh only the column titles remain in the correct order.
![image](https://user-images.githubusercontent.com/76492619/102919739-63138800-4457-11eb-9804-53141e4df66d.png)

**Comment by UtechtDustin** [comment] 2020-12-23 18:58
@ryanp2317 It maybe could be related to the issue.
Could you please provide us an example using our [editor](https://live.bootstrap-table.com/) ?

@djhvscf Do you tested it on different browsers ?

**Comment by djhvscf** [comment] 2020-12-23 20:10
@UtechtDustin yes sir, same behavior

**Comment by UtechtDustin** [comment] 2020-12-23 20:13
@wenzhixin could you maybe record a video?
I'm not able to reproduce it on firefox (84.0) and chrom(ium) (Version 87.0.4280.88).

**Comment by ryanp2317** [comment] 2020-12-23 22:01
https://user-images.githubusercontent.com/76492619/103040073-6afb2700-4540-11eb-9a4f-2aaba488fc56.mp4

My dataset is server side, but here's a video if at all helpful. It shows 1) everything working great, 2) a discontinuity after page refresh, 3) restoration of normal functioning after moving any single column following that page refresh.

**Comment by gui55gui** [comment] 2021-01-12 18:30
An easy way to simulate would be to follow the following steps:

1 - Click the "Order by Price, Name, ID" button.
2 - Click on the title of any column to make the default sort.

After these two steps, note that the values have returned to their initial location, losing their order.

**Comment by Viewtrader** [comment] 2021-03-18 22:14
Still no solution for this problem?

**Comment by djhvscf** [comment] 2021-11-25 17:12
I think this is fixed with the latest version. See this example: https://live.bootstrap-table.com/code/djhvscf/9727

**Comment by UtechtDustin** [comment] 2022-03-13 11:43
We got no response since nov 2021, we will close this issue for now.
If you still need help, please reopen the issue and provide us an example if the issue still persists.

**Closed by UtechtDustin** 2022-03-13 11:43 UTC
Labels: confirmed, awaiting reply, reorder-columns, Bug
