### ISSUE TITLE
how can i synchronize query sql with pagination in back end ?  help wanted

### ISSUE THREAD

**Issue by B1LIE** [wenzhixin/bootstrap-table#3549] opened 2018-01-17 06:43 UTC
i need your help please,

i am struggling when i want to query from my table (mysql table) synchronize in the backend with pagination limit. please give me example code for fix this.

thanks all

**Comment by wenzhixin** [comment] 2018-01-17 14:33
Duplicate of #25 #1070 #1863

**Closed by wenzhixin** 2018-01-17 14:33 UTC
