### ISSUE TITLE
Checkbox gain focus and data is filtered

### ISSUE THREAD

**Issue by Victor-Severino** [wenzhixin/bootstrap-table#3122] opened 2017-05-08 19:33 UTC
I have a table with multiple searchable columns and one checkbox column to select all the items.
The problem is when I hit tab and this checkbox gain focus the data is filtered resulting in "No matching records found". 
I tried to set searchable false but that doesn't work.

Here is my <a href="https://jsfiddle.net/vhss/ood9tbct/">jsfiddle</a>.

**Comment by Falseee** [comment] 2019-03-23 22:39
Cant reproduce this issue with a newer version(check demo), might be already fixed in an newer version.
So the issue and the old Mergerequest #3356 @wenzhixin @djhvscf 

Demo: https://jsfiddle.net/vuyr5791/1/

**Comment by djhvscf** [comment] 2019-03-24 07:20
This is fixed in latest version

**Closed by djhvscf** 2019-03-24 07:20 UTC
Labels: filter-control
