### ISSUE TITLE
[Need Example]Checkboxes Event

### ISSUE THREAD

**Issue by DustinUtecht** [wenzhixin/bootstrap-table#2474] opened 2016-07-16 01:15 UTC
Hello,

is it possible to use [Bootstrap toggle](http://www.bootstraptoggle.com/) with 'check.bs.table' event ?
If i use bootstrap toggle the Events are not fired, i think its because bootstrap toggle change the Checkboxes...

greetings,
Dustin

**Comment by djhvscf** [comment] 2016-07-16 02:37
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by DustinUtecht** [comment] 2016-07-16 09:31
https://jsfiddle.net/30sx4h3t/130/

Dirty Code just for a preview.
The check event not working, if you remove or comment out line 5 the event work

**Comment by dabros** [comment] 2016-07-18 00:21
@DustinUtecht 

Issue seems to be the `bootstrapToggle` call, see https://jsfiddle.net/30sx4h3t/131/

Doesnt matter if js init or data-toggle, whenever the toggle ui call is made it stops receiving `check.bs.table` events. 

That is likely due to it replacing the html checkbox element or similar step that loses the event handler mapped to it. 

Im not sure a solution for it, its a third party plugin so up to you to look into what it does and see why `check.bs.table` not picked up.

One thought though is maybe try attaching event handler to each checkbox direct inside the `onPostBody` handler. There are a number of `checkBy` type [methods](http://bootstrap-table.wenzhixin.net.cn/documentation/#methods) that you could call to make that handler trigger, or place code from `check.bs.table` inside custom checkbox handler, param can be reached using `data-id` and ect printed on each tr.

http://www.bootstraptoggle.com/
http://www.bootstraptoggle.com/#api

**Comment by djhvscf** [comment] 2017-12-29 08:17
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR**. Thanks!

**Closed by djhvscf** 2017-12-29 08:17 UTC
Labels: awaiting reply, needs example
