### ISSUE TITLE
Uncaught TypeError: Cannot read property 'state' of undefined

### ISSUE THREAD

**Issue by ljw1264654273** [wenzhixin/bootstrap-table#3532] opened 2018-01-05 09:43 UTC
I want use filterControl, but the error occured in my project.
![image](https://user-images.githubusercontent.com/18202970/34603663-da842ae2-f23f-11e7-8f20-12aa4f9736db.png)

**Comment by jimgit** [comment] 2018-01-05 11:50
Please submit a jsfiddle to demonstrate your problem ([fiddle template](https://github.com/wenzhixin/bootstrap-table/issues/1765)).

**Comment by ljw1264654273** [comment] 2018-01-05 12:42
![image](https://user-images.githubusercontent.com/18202970/34609765-f7f6bba8-f258-11e7-8f73-9a241b91985b.png)

**Comment by wenzhixin** [comment] 2018-01-06 02:03
Duplicate of #3533

**Closed by wenzhixin** 2018-01-06 02:03 UTC
