### ISSUE TITLE
When I hide my row but can't hide the 'checkbox'（隐藏列的时候不能隐藏那一列的checkbox）

### ISSUE THREAD

**Issue by NiuGui8** [wenzhixin/bootstrap-table#3305] opened 2017-08-08 09:12 UTC
Short and descriptive example bug report title
It can't hide the row's checkbox when i hide a row,who can help me ?
It's a b-t's bug?
A summary of the issue and the browser/OS environment in which it occurs. If suitable, include the steps required to reproduce the bug.

This is the first step
This is the second step
Further steps, etc.

[jsfiddle]() - a link to the reduced test case([fiddle template](https://github.com/wenzhixin/bootstrap-table/issues/1765)).

Any other information you want to share that is relevant to the issue being reported. This might include the lines of code that you have identified as causing the bug, and potential solutions (and your opinions on their merits).

**Comment by NiuGui8** [comment] 2017-08-08 09:13
my e-mail : Liu_CL8888@163.com

**Comment by NiuGui8** [comment] 2017-08-08 09:22
![f7934810](https://user-images.githubusercontent.com/25051862/29065245-0bcbecaa-7c5e-11e7-9fe9-6117214dee66.png)

**Comment by NiuGui8** [comment] 2017-08-08 09:42
help me , thanks!(看到的帮个忙啊，谢谢！)

**Comment by wenzhixin** [comment] 2017-12-17 06:14
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!
没有 jsfiddle 例子，帮补了你。

**Comment by djhvscf** [comment] 2017-12-29 01:07
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR**. Thanks!

**Closed by djhvscf** 2017-12-29 01:07 UTC
Labels: awaiting reply, needs example
