### ISSUE TITLE
clickEdit bug

### ISSUE THREAD

**Issue by sundemeng** [wenzhixin/bootstrap-table#3268] opened 2017-07-17 06:21 UTC
I used the method 
$("#table").bootstrapTable('refreshOptions',{clickEdit:false});	
to change table edit state.
but if i clicked the 'submit' or 'cancel'	 button.this edit is all can click.

update code initTable() at 111 line and initBody() at 123 line.
```
if (!this.options.clickEdit) {    
     that.editing=false;//this line is my add
    return;
}
```

**Comment by djhvscf** [comment] 2017-12-19 07:26
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your contribution, thanks!

**Comment by djhvscf** [comment] 2017-12-29 01:09
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR**. Thanks!

**Closed by djhvscf** 2017-12-29 01:09 UTC
Labels: awaiting reply, click-edit-row, needs example
