### ISSUE TITLE
updateRowByUniqueId

### ISSUE THREAD

**Issue by mwatz122** [wenzhixin/bootstrap-table#1312] opened 2015-08-18 19:50 UTC
Is there a way to do this? I know we can get the row and remove the row, but how to update it?

http://jsfiddle.net/djhvscf/e3nk137y/2113/

**Comment by mwatz122** [comment] 2015-08-19 13:58
Update: I think I've found a way to do this.

                    // update description
                    var row = $('#table').bootstrapTable('getRowByUniqueId', uniqueId);
                    var data = $('#table').bootstrapTable('getData');
                    var index = data.indexOf(row);
                    row.description = 'New Description';
                    $('#table').bootstrapTable('updateRow', { index: index, row: row });

**Comment by dabros** [comment] 2015-08-21 07:35
In my case i just made my changes in a modal, then refreshed list - seemed easiest especially as most websites inherently support parrallel sessions - so its worth updating the data to reflect any other changes at same time, instead of trying to be tricky, as you already sending data to server for saving anyway.

But i cant say much without more context as to Why and When you want to do this.

**Comment by djhvscf** [comment] 2015-08-23 02:30
It seems the issue is solved. Close this issue

**Closed by djhvscf** 2015-08-23 02:30 UTC
