### ISSUE TITLE
Select filter control + Cookie localestorage + refresh browser = lost filter

### ISSUE THREAD

**Issue by manukieli** [wenzhixin/bootstrap-table#4598] opened 2019-09-22 10:08 UTC
BootstrapTable: V1.15.4
Plugin: filter-control and cookie
Cookie configure like localstorage

Good: When I filter with an input value and refresh the browser it work well.
Issue: When I filter with select option the filter is apply well, but if I refresh the browser, the select option to localstorage is deleted and the filter is not apply.

You can see the issue to this link: https://live.bootstrap-table.com/code/manukieli/619

![Select filter lost](https://user-images.githubusercontent.com/14294794/65385636-8c63d680-dd31-11e9-8e54-20cba8ca892e.gif)

**Comment by UtechtDustin** [comment] 2019-09-28 23:50
Thank you very much for reporting the issue, also that gif is a great help to understand it!
I can confirm the issue, also it fails on saving with cookies.

**Comment by manukieli** [comment] 2019-10-20 12:29
I've update this example to version 1.15.5: https://live.bootstrap-table.com/code/manukieli/917
And the problem persist.

**Comment by UtechtDustin** [comment] 2019-11-03 20:26
This issue was hard to debug....
I figured out that `data-url` is the issue.

Before the data is loaded the cookie extension tries to set the values (which dont work on selects because no options existing, but for input its it works fine).
This will trigger some events and the cookie extension tries to fetch the values and saves them, so it will only fetch the input value and saves for the selects nothing.
After the data from the `data-url` was loaded the values of the selects are already gone.

Currently i cant figure out how to solve it.

**Comment by wenzhixin** [comment] 2019-12-20 00:31
Fixed in #4729

**Closed by wenzhixin** 2019-12-20 00:31 UTC
Labels: confirmed, cookie, filter-control, has PR
