### ISSUE TITLE
Reset the offset to 0 on Table refresh? ('refresh')

### ISSUE THREAD

**Issue by anupalhub** [wenzhixin/bootstrap-table#2188] opened 2016-04-14 06:55 UTC
How can i reset the offset to 0 on Table refresh? ('refresh')

**Comment by djhvscf** [comment] 2016-04-14 13:26
This option is not supported but any **PR** is welcome

**Comment by wenzhixin** [comment] 2019-04-04 15:43
Duplicate of #2584, close this one.

**Closed by wenzhixin** 2019-04-04 15:43 UTC
Labels: feature
