### ISSUE TITLE
表格放置在一些可关闭的选项卡中,remove掉后重新打开找不到引用对象

### ISSUE THREAD

**Issue by shekang** [wenzhixin/bootstrap-table#2822] opened 2016-12-15 06:51 UTC
最后将源码遍历表格获取引用对象时更改为如下， 这样是否可行
this.each(function () {
           
        var $this = $(this)  --》 var $this = $("#"+this.id),

**Comment by wenzhixin** [comment] 2016-12-25 06:44
请提供 jsfiddle 说明问题。

**Comment by djhvscf** [comment] 2017-06-19 06:26
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR**. Thanks!

**Closed by djhvscf** 2017-06-19 06:26 UTC
Labels: needs example
