### ISSUE TITLE
Sorting button not working

### ISSUE THREAD

**Issue by SuperBoy17** [wenzhixin/bootstrap-table#6912] opened 2023-07-24 09:20 UTC
### Bootstraptable version(s) affected

1.21.1

### Description

Hi, regarding issue #6809, I submitted another issue on the last message, please check:

Hello again, regarding last time already guided me how to solve this issue, maybe I misguided which sorting I was on trouble, what I'm using is this sorting button, sorry and please help to check again, much appreciated.

![image](https://github.com/wenzhixin/bootstrap-table/assets/112933534/c62fb435-5cec-44b2-995e-e78ed34f8b96)

**Comment by wenzhixin** [comment] 2023-07-27 00:08
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem. Thanks!

**Comment by UtechtDustin** [comment] 2023-10-01 19:27
We don't got an example from you, so we have to close this issue.  
Please let us know if you still have this issue, i also can't reproduce it.

**Closed by UtechtDustin** 2023-10-01 19:27 UTC
Labels: help-wanted, awaiting reply, needs example
