### ISSUE TITLE
Filter control with multi select

### ISSUE THREAD

**Issue by sebastiangehrt** [wenzhixin/bootstrap-table#4964] opened 2020-04-07 05:38 UTC
It would be a nice feature if the filter control also had the option for multi-select

e.g.  I would like two or more categories : 
https://live.bootstrap-table.com/code/sebastiangehrt/2412

**Comment by wenzhixin** [comment] 2020-04-07 05:45
Duplicate of #3298

**Closed by wenzhixin** 2020-04-07 05:45 UTC
