### ISSUE TITLE
The number of headers exceeds the current screen width, and when the table's height property is set, two horizontal scroll bars appear

### ISSUE THREAD

**Issue by wangchengxin** [wenzhixin/bootstrap-table#5486] opened 2020-12-16 07:10 UTC
**Bootstraptable version(s) affected**:1.18.1

**Description**  
The number of headers exceeds the current screen width, and when the table's height property is set, two horizontal scroll bars appear, all blank on the right side of the screen

**Example**  
https://live.bootstrap-table.com/example/extensions/fixed-columns.html

**Possible  (optional)**  

**Additional context**  
when the table's height property is set
![image](https://user-images.githubusercontent.com/15154825/102316394-cbbeb880-3fb0-11eb-9999-2347629e7c31.png)
when the table's height property is not set
![image](https://user-images.githubusercontent.com/15154825/102316926-bd24d100-3fb1-11eb-89eb-404fdf2069f3.png)

**Comment by wangchengxin** [comment] 2020-12-23 02:31
I set the html style to overflow-x: hidden and solved it, but I don’t know why this problem occurs.

**Comment by wenzhixin** [comment] 2021-03-02 07:24
Duplicate of #5598

---

与 #5598 为同个问题

**Closed by wenzhixin** 2021-03-02 07:24 UTC
Labels: Bug
