### ISSUE TITLE
Cookie extension: searchText (data-search-text) does't showing if bs.table.searchText cookiesEnabled is not enabled

### ISSUE THREAD

**Issue by duongthien** [wenzhixin/bootstrap-table#5264] opened 2020-08-18 05:02 UTC
**Bootstraptable version(s) affected**:

1.17.1 & 1.16.0

**Description**  

option searchText does't work when the 'bs.table.searchText' is not enabled in cookiesEnabled option.

I dont want to save search text so I set option: cookiesEnabled:['bs.table.sortOrder', 'bs.table.sortName',  'bs.table.columns'].
Problem: when my table has searchText option set. it does't work.

**Possible  (optional)**  

**Additional context**

**Comment by djhvscf** [comment] 2020-09-05 17:37
Please provide an [Online Example](https://live.bootstrap-table.com/) to show your problem, thanks!

**Comment by UtechtDustin** [comment] 2020-09-05 17:41
@djhvscf i think this is a duplicate of #4984, or not ?

**Comment by djhvscf** [comment] 2020-09-05 17:44
It is! Marked as duplicate then. Thanks @UtechtDustin

**Closed** 2020-09-05 17:44 UTC
Labels: Bug, duplicate, needs example
