### ISSUE TITLE
value of checkbox sets to false when Sorted, Filtered, Paginated or Display per page is changed. 

### ISSUE THREAD

**Issue by thesid66** [wenzhixin/bootstrap-table#2804] opened 2016-11-29 11:11 UTC
Hello there,
I like this plugin. somehow i am stuck on these checkbox issue.

value of checkbox sets to false when Sorted, Filtered, Paginated or Display per page is changed. initially, when page loads for the first time the checkbox will have the value on page 1. 

but when navigated to page 2 or we use filter or sorting or display of page is changed the value turns to FALSE. i have followed every instruction discussed for this plugin.
```
<table 
					data-toggle="table" 
					data-url="tables/district.php"  
					data-show-refresh="true" 
					data-show-toggle="true" 
					data-show-columns="true" 
					data-search="true" 
					data-select-item-name="txtDistrictID[]" 
					data-pagination="true" 
					data-sort-name="" 
					data-sort-order=""
					data-id-field="DistrictID">
						    <thead>
						    <tr>
						        <th data-field="DistrictID" data-checkbox="true" >DistrictID</th>
						        <th data-field="DistrictName" data-sortable="true">District</th>
						        <th data-field="StateID" data-sortable="true">State</th>
						    </tr>
						    </thead>
						</table>
```
Please get me out of this

**Comment by GuilhermeHideki** [comment] 2017-03-27 14:19
Hi, I have the same problem, but I'm using the JS mode.

[jsfiddle](http://jsfiddle.net/e3nk137y/12636/)

**Comment by GuilhermeHideki** [comment] 2017-03-27 14:36
``maintainSelected: true`` worked for me

**Comment by djhvscf** [comment] 2017-03-27 19:03
@thesid66 ``maintainSelected: true`` works for you

**Comment by djhvscf** [comment] 2017-12-29 08:14
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR**. Thanks!

**Closed by djhvscf** 2017-12-29 08:14 UTC
Labels: awaiting reply
