### ISSUE TITLE
Row attributes not updating when searching

### ISSUE THREAD

**Issue by WCCBrewCrew** [wenzhixin/bootstrap-table#3124] opened 2017-05-09 05:03 UTC
I have a table with a number of rowAttributes (id, data-unique-id, etc) that don't seem to be updating when you do a search. It seems to keep the existing attributes but display the correct cell data. 

My table data is loading dynamically via an ajax function that gets a JSON object (below is a snipet):
```
success: function(data) {
         json = JSON.parse(data);
         table.bootstrapTable(
               'load', json
         );
 },
```

I'm using the following snippet to add the row attributes to the table: 
```
rowAttributes: function(row, index) {
            return {
                'id': json[index].studentID,
                'data-year': json[index].yearType,
                'data-student': json[index].studentID
            };
}
```

Cheers,
Luke

**Comment by wenzhixin** [comment] 2018-01-06 02:16
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by djhvscf** [comment] 2018-01-29 05:46
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR** with an [example](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports). Thanks!

**Closed by djhvscf** 2018-01-29 05:46 UTC
Labels: awaiting reply, needs example
