### ISSUE TITLE
search in multiple rows

### ISSUE THREAD

**Issue by alenget** [wenzhixin/bootstrap-table#3850] opened 2018-06-18 13:59 UTC
i have a json table with this format
IP , NAME
8.8.8.8 go1
8.8.4.4 go2
1.1.1.1 dns1
2.2.2.2 dns2
etc

What is/(if possible) the best way to search for multiple ip's and have them saved with a cookie, so that the only one searched are shown?

thanks

**Comment by jimgit** [comment] 2018-06-18 17:52
Regarding the bootstrapTable portion of the work - [You might want to look at the filterBy method - here is an example](http://issues.wenzhixin.net.cn/bootstrap-table/#methods/filterBy.html)

**Comment by djhvscf** [comment] 2018-07-23 14:00
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR** with an [example](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports). Thanks!

**Closed by djhvscf** 2018-07-23 14:00 UTC
