### ISSUE TITLE
filterBy does not work using Filter Control plugin

### ISSUE THREAD

**Issue by francogp** [wenzhixin/bootstrap-table#6381] opened 2022-09-08 15:47 UTC
### Bootstraptable version(s) affected

1.21.0

### Description

using the function filterBy trigger a refresh but does not send the filters

### Example(s)

https://live.bootstrap-table.com/code/francogp/12776

**Comment by UtechtDustin** [comment] 2022-09-15 20:48
It's not related to the `filterControl` extension.
Please check the duplicate issue.

Duplicate of #5989

**Closed by UtechtDustin** 2022-09-15 20:48 UTC
Labels: Bug
