### ISSUE TITLE
onCheck时间循环触发问题

### ISSUE THREAD

**Issue by sysecho** [wenzhixin/bootstrap-table#3188] opened 2017-06-09 11:20 UTC
你好：
    我在使用onCheck事件选中其他行时同时会触发其它行触发该事件导致死循环，请问有什么方式可以避免此类情况？谢谢！

**Comment by wenzhixin** [comment] 2017-12-28 05:50
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by djhvscf** [comment] 2018-01-29 05:45
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR** with an [example](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports). Thanks!

**Closed by djhvscf** 2018-01-29 05:45 UTC
Labels: needs example
