### ISSUE TITLE
Angular with Server Side Pagination

### ISSUE THREAD

**Issue by talatbaig** [wenzhixin/bootstrap-table#2223] opened 2016-04-26 14:57 UTC
Hi,

Could you please give an example of an angular version with server side pagination enabled using angular's $http and not the jquery $ajax.

Thank You

**Comment by antonyboom** [comment] 2016-05-17 16:49
```
$http({
            method: "GET",
            url: "http:/address:8080/with/your/api/call"
        }).then(function success(response) {
            $scope.yourVar = response.data;
        }, function error(response) {
            $scope.yourVar = response.statusText;
        });
```

table in your controller: 

```
  $(function () {
            $('#table').bootstrapTable('refreshOptions', {
data: $scope.yourVar
});
})
```
html
` <table id="table"> </table`

**Comment by dabros** [comment] 2016-05-31 23:48
@talatbaig - if this worked, please provide some more description on how it helped you and possibly some of your own code for the next wanderer, then close this issue

thanks

**Comment by djhvscf** [comment] 2017-12-29 08:22
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR**. Thanks!

**Closed by djhvscf** 2017-12-29 08:22 UTC
Labels: angular, awaiting reply, extension
