### ISSUE TITLE
Multiple select for filter-control

### ISSUE THREAD

**Issue by rickbarnsley** [wenzhixin/bootstrap-table#1870] opened 2016-01-11 15:22 UTC
Hi, feature request from me: the filter control extension works great, one useful enhancement would be to have a similar control that allows multiple selections in that value list.

**Comment by dabros** [comment] 2016-01-11 23:32
@rickbarnsley - duplicate of #1124

please close this and post there

**Closed** 2016-01-12 14:29 UTC
Labels: help wanted
