### ISSUE TITLE
vue component table check box looses its status when filter applied

### ISSUE THREAD

**Issue by dathor-ghub** [wenzhixin/bootstrap-table#5086] opened 2020-06-12 05:25 UTC
using bootstrap-table vue component.  When a column has a check box the status of this check box is lost when any filter is applied.

You can see this even in the vue component example provided.  To re create the problem simply check a check box and then go and type something in the search bar.  you will see the check box looses its status.

Thank you

**Comment by wenzhixin** [comment] 2020-06-13 07:52
You need to save your checkbox state: https://examples.bootstrap-table.com/#issues/987.html
Duplicate of #987

**Closed by wenzhixin** 2020-06-13 07:52 UTC
