### ISSUE TITLE
editable not work in andriod with  keyboard's input

### ISSUE THREAD

**Issue by Eastcloudsea** [wenzhixin/bootstrap-table#3577] opened 2018-01-30 09:52 UTC
when in andriod phone with editable plugins ,the editable-shown triggered , when keyboard show the table will trigger pre-body even then the most evens is triggered until the input box hidden .

but in iphone it work only only with event editable-shown. it work ok.

because the case happen on andriod phone ,so the jsfiddle could't show the sample.

the case happed in huawei phone.

do you have some advice.  

Thanks

Short and descriptive example bug report title

A summary of the issue and the browser/OS environment in which it occurs. If suitable, include the steps required to reproduce the bug.

This is the first step
This is the second step
Further steps, etc.

[jsfiddle]() - a link to the reduced test case([fiddle template](https://github.com/wenzhixin/bootstrap-table/issues/1765)).

Any other information you want to share that is relevant to the issue being reported. This might include the lines of code that you have identified as causing the bug, and potential solutions (and your opinions on their merits).

**Comment by Eastcloudsea** [comment] 2018-01-30 10:40
maybe some could tell me how to off the  table resize or resetwidth even. I guess is the even be triggered

**Comment by Eastcloudsea** [comment] 2018-01-30 16:40
issue is found . the mobile plugin is bug.  the mobile plugins would force that the table to keep to toggleview . so that I have to remove the mobile plugins.  

hope some one could fix that.

**Comment by UtechtDustin** [comment] 2019-06-23 12:12
I close this issue because the issue create found the issue and resolved it, also the issue is older than a year.
If you still need help please reopen the issue.

**Closed by UtechtDustin** 2019-06-23 12:12 UTC
Labels: mobile
