### ISSUE TITLE
Updating table by Unique id

### ISSUE THREAD

**Issue by wpanderson** [wenzhixin/bootstrap-table#2526] opened 2016-08-01 22:25 UTC
Hi,

I'm developing a web application utilizing the bootstrap table and I'm having issues updating specific values in a table. Namely I have a table called system-table in which I select a number of rows send the data to my Python backend and return an updated version of the same data which will update rows which I had selected. Since there is no convenient way of getting the selected index of the rows I have been attempting to update the rows by a unique id which doesn't change when the values get updated. The code I used to update the table is the code from the example:

`$("system-table").bootstrapTable('updateByUniqueId', { id: idValue, row: rowData})`

I also added:
`data-unique-id="blah"`
into my table initialization in the html where blah is the td I wish to use as my unique id.

What happens when I run this is, depending on the value I select in my table the result is either nothing happens aside from a color change in the table row, or a new row is added to the table with the updated row data. 

Is there a specific way in which I need to specify the unique id I wish to compare my incoming row data with?

Thanks.

**Comment by dabros** [comment] 2016-08-03 23:35
As long as approach matches that in examples i cant see why there is an issue, if there is it would possibly be logged in console as error (F12) and you should `console.log(..)` to ensure your `idValue` and `rowData` match as expected, and inspect generated html to ensure the rows are printed with the right `data-unique-id` (basic debugging, always always always debug using F12)

http://issues.wenzhixin.net.cn/bootstrap-table/#methods/updateByUniqueId.html

If you see no issue, then you need to replicate. The actual update cant be replicated using jsfiddle `echo` (see below) as you just need to use F12 and watch network requests on your live code then mimic something similar so you can replicate core issue. There is also a good chance that simplifying your code so you can replicate JUST the core issue you will solve this yourself, but its needed anyway for us to help you.

Please provide a Fiddle and we can help you more, dummy data from js array is fine (just needs to replicate core issue). For data-url use them from examples provided, if you need more custom server side then see http://stackoverflow.com/questions/7194408/how-can-i-use-the-jsfiddle-echo-feature-with-jquery

Examples and guide provided below:
- https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports
- #1765

**Comment by wpanderson** [comment] 2016-08-16 00:24
Thanks for the reply @dabros and sorry for the late reply. I ended up doing a roundabout way of finding the index of the selected rows and using that to update the indicated rows using https://github.com/wenzhixin/bootstrap-table-examples/blob/master/issues/415.html as an example. Straight forward enough, though it would have been nice to have updateByUniqueId work, or a built method to return the selected index.

**Comment by dabros** [comment] 2016-08-16 00:36
@wpanderson - there are methods to do both of those things that work great, if you dont share a fiddle and replicate your original issue cant help you anymore though, except to point you to the many working examples both in official doco and in closed and open issues here and on SO.

**Comment by djhvscf** [comment] 2017-12-29 08:15
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR**. Thanks!

**Closed by djhvscf** 2017-12-29 08:15 UTC
Labels: awaiting reply
