### ISSUE TITLE
Filter Control issue on Ipad - drop-down list appears again after choosing an option in select filter 

### ISSUE THREAD

**Issue by franzis** [wenzhixin/bootstrap-table#5802] opened 2021-07-21 12:46 UTC
**Bootstraptable version(s) affected**:
v1.18.3

**Description**  
This issue is related with Filter Control extension usage on Ipad, more specifically with data-filter-control="select" filter. When i choose an option in the drop-down select list, filter applies, drop-down list dissapears for a second, but then appears again without any actions from user. 

This issue occurs even on Filter Contol example page (https://examples.bootstrap-table.com/#extensions/filter-control.html) in "Item Price" column filter.

The problem does not appear when you choosing an empty option in select filter or choosing an option that is currently chosen.

It was checked in two browsers - Safari and MS Edge, both with last versions.

Also, two Ipad versions was checked - Ipad Mini and Ipad Pro.

I also attached an example video.

https://user-images.githubusercontent.com/3996725/126490575-a8534451-8e08-4976-9e85-8ea42469df6e.mp4

**Example**  
https://live.bootstrap-table.com/example/extensions/filter-control.html

**Comment by franzis** [comment] 2021-08-16 08:37
@UtechtDustin , are you sure this bag is "browser dependent"? I caught it in 2 different browsers - Safari and MS Edge. 

Unfortunately i can't check the bag in any other browser cause i can't install any apps on my Ipad due to corporate policies.

**Comment by djhvscf** [comment] 2021-11-25 17:01
I have tested this in multiple browser and OS but I can't reproduce it. Please double check if the latest version fixes this problem @franzis

**Comment by UtechtDustin** [comment] 2021-11-28 01:15
I also can't reproduce it on the folling browser:

- Firefox 94
- Chromium 96.0(.4664.45)
- Safari 15.0 (Ipad & Iphone)

I'm going to close this issue, because we can't reproduce it.
Please check your IOS/Safari version for a new update, also please check if you maybe have a plugin installed which is the cause of that issue.

If you think this is still an issue and the cause is the bootstrap-table itself, please provide us more information!

**Closed by UtechtDustin** 2021-11-28 01:15 UTC
Labels: browser dependent, awaiting reply, filter-control, Bug
