### ISSUE TITLE
Bootstrap-Table in ajax partial view is not working

### ISSUE THREAD

**Issue by robertovanoli** [wenzhixin/bootstrap-table#2612] opened 2016-09-01 09:05 UTC
I'm developing a web app with aspnet core and bootstrap and I need to sort a simple table hosted in a partial view named 'mytable.cshtml'. bootstrap-table is not working if the partial view is loaded dinamically with an Ajax call (while it works if the partial view is loaded statically)

here my table: 

```
   <table id="table" data-toggle="table" class="table">
            <thead>
                <tr>
                    <th data-sortable="true">column 1</th>
                    <th data-sortable="true">column 2</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>aaa</td>
                    <td>111</td>
                </tr>
                <tr>
                    <td>bbb</td>
                    <td>222</td>
                </tr>
                <tr>
                    <td>ccc</td>
                    <td>333</td>
                </tr>
            </tbody>
        </table>

```

step 1) First I tested that all it's fine, loading the partial view in this way

```
@Html.Partial("mytable");
```

The view is loaded, the table is correcty formatted, column headers have icons for sorting, clicking on header the content is ordered.

step 2) Now I try to load the partial view with an Ajax call when a link is clicked : 

```
<a href=@Url.Action("GetMyTable"})  onclick="LoadMyTable()"/>
//LoadMyTable() script omitted ...
```

as before the partial view is loaded correctly, the table is shown and formatted, but columns cannot be sorted: the sorting icon is not shown and clicking on column headers nothing happens

**Comment by huanhuashengling** [comment] 2017-05-15 03:46
guy. I also searching the problem, finally i found the answer.

You can use Javascript way to reach the goal.

First make sure added id="table" to you table tag, like

<table id="table" class='table' data-toggle="table">

Second add js to under your partial file (may be this is not strict)

<script type="text/javascript">
     $('#table').bootstrapTable();
</script>
Then you can test the code. Good luck!

**Comment by djhvscf** [comment] 2017-05-15 03:56
@robertovanoli  can you test the solution provided by @huanhuashengling ?

**Comment by djhvscf** [comment] 2017-12-29 08:14
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR**. Thanks!

**Closed by djhvscf** 2017-12-29 08:14 UTC
Labels: awaiting reply, help wanted
