### ISSUE TITLE
tableGroups is undefined when using server side pagination for group-by-v2

### ISSUE THREAD

**Issue by LostIndie** [wenzhixin/bootstrap-table#3250] opened 2017-07-06 06:36 UTC
Hi,

i am using the group-by-v2 extension for the bootstrap table with server side pagination. The records cannot be load in table and has the error of tableGroups is undefined. How to fix it?

**Comment by fatis17** [comment] 2017-07-26 06:59
Hi, 
I have the same problem.
Solution ?

**Comment by Bighamster** [comment] 2017-11-25 06:20
+1

**Comment by mr-pupu** [comment] 2017-11-28 14:44
+1

**Comment by djhvscf** [comment] 2017-11-29 02:05
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by djhvscf** [comment] 2018-01-29 05:44
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR** with an [example](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports). Thanks!

**Closed by djhvscf** 2018-01-29 05:44 UTC
Labels: needs example

**Comment by Prezi2907** [comment] 2018-08-08 10:54
+1
I have problem with this same one... Any solution?
This section of code is not executed that, why we have this problem:
`BootstrapTable.prototype.initSort = function () {
        _initSort.apply(this, Array.prototype.slice.apply(arguments));

        var that = this;
        tableGroups = [];`

**Comment by taylorwood** [comment] 2022-04-20 04:36
I spent some time with the bootstrap-table source and found a workaround for this by overriding `initData` instead of `initSort` in the extension. You can do a simple find/replace `s/initSort/initData` in the source, e.g.:
```js
BootstrapTable.prototype.initData = function (...args) {
  _initData.apply(this, Array.prototype.slice.apply(args))
```
Why I think this works:
When server-side pagination is enabled, the data gets rendered through a different code path (via `load`, via XHR success handler); `initSort` is never called in this case, which is why `this.tableGroups` is undefined in the current extension.

**Comment by LiMoon** [comment] 2025-03-07 02:27
> I spent some time with the bootstrap-table source and found a workaround for this by overriding instead of in the extension. You can do a simple find/replace in the source, e.g.:`initData``initSort``s/initSort/initData`
> 
> BootstrapTable.prototype.initData = function (...args) {
>   _initData.apply(this, Array.prototype.slice.apply(args))
> Why I think this works: When server-side pagination is enabled, the data gets rendered through a different code path (via , via XHR success handler); is never called in this case, which is why is undefined in the current extension.`load``initSort``this.tableGroups`

is work
