### ISSUE TITLE
bootstrap-table-filter-control.js 2.1.2 Error

### ISSUE THREAD

**Issue by Luke7810** [wenzhixin/bootstrap-table#3501] opened 2017-12-13 09:16 UTC
Firstly, I using this version code to fix the error about can not show the filter data-filter-control="select",
but when I using this version , I can not get the data from server, the error is : Uncaught TypeError: Cannot read property 'id' of undefined,
the error line is 196
 var column = that.columns[that.fieldsColumnsIndex[field]],
My HTML code just using the example code:

<table id="table"
           data-toggle="table"
           data-url="../json/data1.json"
           data-filter-control="true"
           data-filter-show-clear="true">
        <thead>
        <tr>
            <th data-field="id">ID</th>
            <th data-field="name" data-filter-control="input">name </th>
            <th data-field="price" data-filter-control="select">Item Price </th>
        </tr>
        </thead>
    </table>

**Comment by Luke7810** [comment] 2017-12-13 09:18
`<table id="table"
           data-toggle="table"
           data-url="../json/data1.json"
           data-filter-control="true"
           data-filter-show-clear="true">
        <thead>
        <tr>
            <th data-field="id">ID</th>
            <th data-field="name" data-filter-control="input">name </th>
            <th data-field="price" data-filter-control="select">Item Price </th>
        </tr>
        </thead>
    </table>`

**Comment by wenzhixin** [comment] 2017-12-13 10:36
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by djhvscf** [comment] 2017-12-29 01:04
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR**. Thanks!

**Closed by djhvscf** 2017-12-29 01:04 UTC
Labels: filter-control, needs example

**Comment by Lucipher** [comment] 2018-02-21 03:16
The same error!
