### ISSUE TITLE
Secondary Columns Slipping into Another Primary Column Using Group Columns

### ISSUE THREAD

**Issue by frankroeske** [wenzhixin/bootstrap-table#5554] opened 2021-01-20 06:28 UTC
**Bootstraptable version(s) affected**:
1.18.1

**Description**  
Disabling visibility of a column in a table with group columns does not behave properly. The columns of the second row slip into another primary column when disabling the secondary column of primary this column which has only one secondary column.

**Example**  
https://live.bootstrap-table.com/code/frankroeske/6281

**Possible** 
The primary column with only one secondary column shall be hided.
By the way it is not possible for the user distinguish between the "SubItem1" entries inside the show selecting dropdown. It would be nice if at least the primary column names are listed between the switchable items in this list. For the user it would be the best if he could toggle a complete primary column including all secondary columns, but currently data-visible and data-switchable are ignored at the primary column (@see https://github.com/wenzhixin/bootstrap-table/issues/5368).

**Additional context**  
any browser, any operating system

**Comment by UtechtDustin** [comment] 2021-01-23 17:01
Thank you for the report, i close this issue because its a duplicate of #3213.

**Closed by UtechtDustin** 2021-01-23 17:01 UTC
Labels: Bug
