### ISSUE TITLE
Filter control : select box with name containing "&"

### ISSUE THREAD

**Issue by sdespont** [wenzhixin/bootstrap-table#6251] opened 2022-07-08 10:45 UTC
### Bootstraptable version(s) affected

1.20.2

### Description

When rows have name containing "&", the select list show the name without the "&" char, which doesn't permit to filter by this name.

In this example, the name should be "Z&B", but "ZB" is listed. Selecting "ZB" doens't permit to display the "Z&B" rows:

![image](https://user-images.githubusercontent.com/646632/177977497-3ae41bda-a87e-46fe-b69d-868c54c20a6b.png)

### Example(s)

https://live.bootstrap-table.com/code/sdespont/12051

**Comment by UtechtDustin** [comment] 2022-07-09 17:15
Duplicate of #6130

**Closed by UtechtDustin** 2022-07-09 17:15 UTC
Labels: filter-control, Bug
