### ISSUE TITLE
Horizontal scrollbar does not appear

### ISSUE THREAD

**Issue by PiGi78** [wenzhixin/bootstrap-table#3493] opened 2017-12-10 16:12 UTC
Horizontal scrollbar does not appear.

I have an html table that I convert to BootstrapTable from it.
The conversion works, but no horizontal scrollbar appears, also if the grid has a column of 5000px.

[jsfiddle]() - Example in fiddle ([fiddle template](https://jsfiddle.net/pa0363f0/)).

**Comment by djhvscf** [comment] 2017-12-19 06:39
See this examples: http://jsfiddle.net/e3nk137y/17956/ http://jsfiddle.net/e3nk137y/17957/

**Comment by djhvscf** [comment] 2017-12-29 01:04
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR**. Thanks!

**Closed by djhvscf** 2017-12-29 01:04 UTC
Labels: awaiting reply

**Comment by PiGi78** [comment] 2017-12-29 11:37
Well...

**Comment by PiGi78** [comment] 2017-12-29 11:39
Well..

The example that you put has the same problem: in JsFiddler the grid doesn't show the horizontal scrollbar. For now it's no more a problem for me (I decided to place two rows for any data, so people doesn't need to scroll).

The other problem (but I don't know if it is a problem of Git or of your reposiotry) is that the email about the comment (when you posted the example) is sent the same day you closed the issue (10 days after).
So I didn't know there was a new comment to check...

Thank you very much
