### ISSUE TITLE
How to show the result of ajax json in bootstrap table

### ISSUE THREAD

**Issue by oscarruz** [wenzhixin/bootstrap-table#2847] opened 2017-01-04 15:17 UTC
I'm search the solution about this issue. I have a json array after of execute a php script and it's working fine. I get this:
```
{
  "estado":"PE",
  "id_usuario":"20",
  "nombre":"Irene",
  "apellido1":"Munn\u00e9",
  "id_addtime_horario":"7",
  "fecha":"2016-12-30",
  "dia_semana":"friday   ",
  "hora_ini":"10:00:00",
  "hora_fin":"15:09:26",
  "jornada":"05:42:12",
  "jornada_flexibilidad":"00:02:46",
  "jornada_deficit":"00:00:00",
  "extra_jornada":"00:00:00",
  "extra_autorizado":null,
  "id_fichaje":"1766",
  "id_fichaje_detalle":"44071"
}
```
The bootstrap table have definition this data-fields and I try to load the data:

```
$.ajax({					
             dataType: 'json',
             url: 'queryFitxatgesTest.php',
             success: function(response) {

                $('#consulta').modal('hide');

                var myData = [];
                myData.push(response);

                console.log(myData);

                $('#tableprod').bootstrapTable('load', myData);
             }
          });
```

But I do not know to how do it to load the result of json :(

Please Could you help me?

**Comment by wenzhixin** [comment] 2017-02-22 02:07
Have you solved your problem?

**Comment by djhvscf** [comment] 2017-12-29 08:14
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR**. Thanks!

**Closed by djhvscf** 2017-12-29 08:14 UTC
Labels: awaiting reply
