### ISSUE TITLE
Problem Integrating Table Filter 

### ISSUE THREAD

**Issue by rajeshbtlit** [wenzhixin/bootstrap-table#728] opened 2015-04-10 16:10 UTC
Hi,
I have followed the steps @ https://github.com/wenzhixin/bootstrap-table-examples/blob/master/561.html

But am unable to get this working, please correct me if am doing anything wrong here

Using Version: bootstrap-table-1.6.0

```
HTML Content:
//css
<link rel="stylesheet" href="resources/admingui/css/bootstrap.min.css">
<link rel="stylesheet" href="resources/admingui/css/bootstrap-table.css">
<link rel="stylesheet" href="resources/admingui/css/main.css">
<link rel="stylesheet" href="resources/admingui/css/bootstrap-theme.min.css">

//js
<script src="resources/admingui/js/jquery-1.11.2.js"></script>
<script src="resources/admingui/js/jquery-1.11.2.min.js"></script>
<script src="resources/admingui/js/bootstrap.min.js"></script>
<script src="resources/admingui/js/bootstrap-table.js"></script>
<script src="resources/admingui/js/jsoneditor.js"></script>
<script src="resources/admingui/js/bootstrap-table-filter.js"></script>

//html table
				<div class="bs-example">
					<div id="filter-bar"> </div>
					<table id="tableWorkflow" data-toggle="table" data-single-select="true"
						data-url="wf/Admin/simplifiedProcesses" data-cache="false"
						data-height="600" data-click-to-select="true" data-striped="true"
						data-pagination="true" data-search="true" data-sort-order="desc"
						data-sort-name="creationTime" data-show-columns="true" data-show-filter="true"
						data-show-refresh="true" data-page-size="50"
						data-page-list='[50, 75, 100, 200, 300, 500'>
						<thead>
							<tr>
								<th data-field="state" data-checkbox="true"></th>
								<th data-field="wfdName" data-sortable="true">Workflow Name</th>
								<th data-field="wfdVersion" data-sortable="true" data-searchable="false">Version</th>
								<th data-field="description" data-sortable="true" >Description</th>
								<th data-field="username" data-sortable="true">Deployed By</th>
								<th data-field="creationTime" data-sortable="true" data-searchable="false">Deployed
									On</th>
							</tr>
						</thead>
					</table>
				</div>


//java script function:
 $('#filter-bar').bootstrapTableFilter({
								connectTo: '#tableWorkflow',
								onAll: function(name, args) {
									var d = new Date();
									$('#log').prepend(d.toLocaleString() + ': ' + name + "\n");
								},
								onSubmit: function(data) {
									var data = $('#filter-bar').bootstrapTableFilter('getData');
									var d = new Date();
									$('#log').prepend(d.toLocaleString() + ': ' + JSON.stringify(data) + "\n");
								}
							});
```

I get error in bootstrap-table-filter.js  Uncaught TypeError: undefined is not a function at line 24
$(that.options.toolbar).bootstrapTableFilter({
                    connectTo: that.$el
                });

**Comment by djhvscf** [comment] 2015-04-10 18:14
I see you don't have the complete reference. Check it again:

<script src="assets/jquery.min.js"></script>
<script src="assets/bootstrap/js/bootstrap.min.js"></script>
<script src="assets/bootstrap-table/src/bootstrap-table.js"></script>
<script src="assets/bootstrap-table-filter/extension/bootstrap-table-filter.js"></script>
<script src="assets/bootstrap-table-filter/bootstrap-table-filter.js"></script>
<script src="assets/bootstrap-table-filter/bs-table.js"></script>

**Comment by djhvscf** [comment] 2015-04-10 18:15
I see you don't have the complete reference. Check it again:

```html
<script src="assets/jquery.min.js"></script>
<script src="assets/bootstrap/js/bootstrap.min.js"></script>
<script src="assets/bootstrap-table/src/bootstrap-table.js"></script>
<script src="assets/bootstrap-table-filter/extension/bootstrap-table-filter.js"></script>
<script src="assets/bootstrap-table-filter/bootstrap-table-filter.js"></script>
<script src="assets/bootstrap-table-filter/bs-table.js"></script>
```

**Comment by achaffman** [comment] 2015-04-10 20:42
Dennis, Can you shed some light on the differences between table-filter and table-filtercontrol?  the comments say you are the author.  I'm trying to implement filter control and keep getting results like this:

![filtercontrol-issue1](https://cloud.githubusercontent.com/assets/10375994/7096985/c84f54ba-df9f-11e4-8f90-186370044a44.png)

If i use the top drop down, then that entire 2nd row disappears (it does filter though).  I know i should be opening another ticket (and I will), but I wanted some idea about the future of this extension vs the table-filter extension.

**Comment by rajeshbtlit** [comment] 2015-04-13 07:08
Thanks Dennis,

I have the distribution of bootstrap-table-1.6.0 and I have used the script here
bootstrap-table-1.6.0\src\extensions\filter, and under this directory we have only bootstrap-table-filter.js.

I see only these two things are missing , 
<script src="assets/bootstrap-table-filter/bootstrap-table-filter.js"></script>
<script src="assets/bootstrap-table-filter/bs-table.js"></script>

And am not able to find these in the distribution, could you please help

**Comment by rajeshbtlit** [comment] 2015-04-13 14:04
Dennis, could you please help, I downloaded the bs-table.js from https://github.com/lukaskral/bootstrap-table-filter/blob/master/src/ext/bs-table.js but didn't get 
assets/bootstrap-table-filter/bootstrap-table-filter.js

**Comment by achaffman** [comment] 2015-04-14 01:17
if anyone is curious about my issue with double rows, it appears to be unrelated to filtering and all related to the fact this table is in a bootstrap-modal.  When the modal resizes the browser to remove the scrollbars, the table needs to be refreshed.  After i put resetView in the shown.bs.modal event, my problems are gone - though there is blip everytime the table has to refresh itself.  It would be better if the table didn't get populated with data until after the Modal was visible.  I'll probably go that route.

**Comment by rajeshbtlit** [comment] 2015-04-17 14:24
Hi Dennis and Wen,

I progressed on this and see the filter icon, but i see errors on console on bs-table.js

Uncaught TypeError: Cannot read property 'externals' of undefined at line 75 on bs-table.js
```
$.fn.bootstrapTableFilter.externals.push(function() {
        if (this.options.connectTo) {
```

My code::
```
<!-- jQuery -->
<script src="resources/admingui/js/jquery-1.11.2.js"></script>
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="resources/admingui/js/jquery-1.11.2.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="resources/admingui/js/bootstrap.min.js"></script>
<script src="resources/admingui/js/bootstrap-table.js"></script>
<script src="resources/admingui/js/jsoneditor.js"></script>
<script src="resources/admingui/js/bs-table.js"></script>
<script src="resources/admingui/js/extensions/bootstrap-table-filter.js"></script>
<script src="resources/admingui/js/bootstrap-table-filter.js"></script>

<link rel="stylesheet" href="resources/admingui/css/bootstrap.min.css">
<link rel="stylesheet" href="resources/admingui/css/bootstrap-table.css">
<link rel="stylesheet" href="resources/admingui/css/main.css">
<link rel="stylesheet" href="resources/admingui/css/bootstrap-table-filter.css">

<div class="bs-example posR">
					<button id="createInstance" type="button"
						class="btn btn-success btn-md createInstance">Create
						Instance</button>
					<div id="filter-bar"> </div>
					<table id="tableWorkflow" data-toggle="table"
						data-single-select="true" data-url="wf/Admin/simplifiedProcesses"
						data-cache="false" data-height="600" data-click-to-select="true"
						data-striped="true" data-pagination="true" data-search="true"
						data-sort-order="desc" data-sort-name="creationTime"
						data-show-columns="true" data-show-filter="true" data-show-refresh="true"
						data-page-size="50" data-page-list='[50, 75, 100, 200, 300, 500'>
						<thead>
							<tr>
								<th data-field="state" data-checkbox="true"></th>
								<th data-field="wfdName" data-sortable="true" data-order="asc">Workflow Name</th>
								<th data-field="wfdVersion" data-sortable="true"
									data-searchable="false">Version</th>
								<th data-field="description" data-sortable="true">Description</th>
								<th data-field="username" data-sortable="true"
									data-searchable="false">Deployed By</th>
								<th data-field="creationTime" data-sortable="true"
									data-searchable="false">Deployed On</th>
							</tr>
						</thead>
					</table>
				</div>



$(function() {
								$('#filter-bar').bootstrapTableFilter({
									connectTo: '#tableWorkflow',
									onAll: function(name, args) {
										var d = new Date();
										$('#log').prepend(d.toLocaleString() + ': ' + name + "\n");
									},
									onSubmit: function(data) {
										var data = $('#filter-bar').bootstrapTableFilter('getData');
										var d = new Date();
										$('#log').prepend(d.toLocaleString() + ': ' + JSON.stringify(data) + "\n");
									}
								});
							});

```

**Comment by djhvscf** [comment] 2015-04-17 14:54
@rajeshbtlit Double check the references order

**Comment by rajeshbtlit** [comment] 2015-04-22 16:01
Thanks Dennis,

now no errors on console but after clicking the filter i  just see remove filters and no columns to filter.

```
<!-- Bootstrap -->
<link rel="stylesheet" href="resources/admingui/css/bootstrap.min.css">
<link rel="stylesheet" href="resources/admingui/css/bootstrap-table.css">
<link rel="stylesheet" href="resources/admingui/css/main.css">

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="resources/admingui/js/jquery-1.11.2.min.js"></script>
<!-- jQuery -->
<script src="resources/admingui/js/jquery-1.11.2.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="resources/admingui/js/bootstrap.min.js"></script>
<script src="resources/admingui/js/bootstrap-table.js"></script>
<script src="resources/admingui/js/extensions/bootstrap-table-filter.js"></script>
<script src="resources/admingui/js/bootstrap-table-filter.js"></script>
<script src="resources/admingui/js/bs-table.js"></script>
<script src="resources/admingui/js/jsoneditor.js"></script>

			<div role="tabpanel" class="tab-pane active" id="workflow">
				<div class="bs-example posR">
					<button id="createInstance" type="button"
						class="btn btn-success btn-md createInstance">Create
						Instance</button>
						<div id="filter-bar"> </div>
					<table id="tableWorkflow" data-toolbar="#filter-bar"  data-toggle="table"
						data-single-select="true" data-url="wf/Admin/simplifiedProcesses"
						data-cache="false" data-height="600" data-click-to-select="true"
						data-striped="true" data-pagination="true" data-show-filter="true" data-search="true"
						data-sort-order="desc" data-sort-name="creationTime"
						data-show-columns="true" data-show-refresh="true"
						data-page-size="50" data-page-list='[50, 75, 100, 200, 300, 500'>
						<thead>
							<tr>
								<th data-field="state" data-checkbox="true"></th>
								<th data-field="wfdName" data-sortable="true">Workflow Name</th>
								<th data-field="wfdVersion" data-sortable="true"
									data-searchable="false">Version</th>
								<th data-field="description" data-sortable="true">Description</th>
								<th data-field="username" data-sortable="true"
									data-searchable="false">Deployed By</th>
								<th data-field="creationTime" data-sortable="true"
									data-searchable="false">Deployed On</th>
							</tr>
						</thead>
					</table>
				</div>

			</div>


// script:
$(function() {
								$('#filter-bar').bootstrapTableFilter({
									connectTo: '#tableWorkflow',
									onAll: function(name, args) {
										var d = new Date();
										$('#log').prepend(d.toLocaleString() + ': ' + name + "\n");
									},
									onSubmit: function(data) {
										var data = $('#filter-bar').bootstrapTableFilter('getData');
										var d = new Date();
										$('#log').prepend(d.toLocaleString() + ': ' + JSON.stringify(data) + "\n");
									}
								});
							});
```

Request your kind help.

**Comment by rajeshbtlit** [comment] 2015-04-24 07:33
Hi Dennis, could you please help on this, I am struggling to integrate this filter. request your kind help.
![table_filter](https://cloud.githubusercontent.com/assets/11829880/7314457/4ba5629a-ea82-11e4-996f-80e6ab1af18e.png)

**Comment by djhvscf** [comment] 2015-04-24 13:41
http://issues.wenzhixin.net.cn/bootstrap-table/#561.html

**Comment by rajeshbtlit** [comment] 2015-04-26 10:58
Thanks Dennis,

I upgraded the bootstrap table framework to 1.7 and i got it working. But see the following behaviors:

1) All the column filter shows  less than, more than and equals. Doesn't show the actual data.
2) When added the filter in another tab which also contains the table, first filter(in first tab) doesn't work 
3) Filter shows the empty select box as well.

Code:
```
//css
<link rel="stylesheet" href="resources/admingui/css/bootstrap.min.css">
<link rel="stylesheet" href="resources/admingui/css/bootstrap-table.css">
<link rel="stylesheet" href="resources/admingui/css/example.css">
<link rel="stylesheet" href="resources/admingui/css/main.css">

//js
<script src="resources/admingui/js/jquery-1.11.2.min.js"></script>
<script src="resources/admingui/js/jquery-1.11.2.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="resources/admingui/js/bootstrap.min.js"></script>
<script src="resources/admingui/js/bootstrap-table.js"></script>
<script src="resources/admingui/js/extensions/bootstrap-table-filter.js"></script>
<script src="resources/admingui/js/bootstrap-table-filter.js"></script>
<script src="resources/admingui/js/bs-table.js"></script>
<script src="resources/admingui/js/jsoneditor.js"></script>

//html:
<div id="tabPanelId" role="tabpanel">

		<!-- Nav tabs -->
		<ul class="nav nav-tabs" role="tablist" id="adminTab">
			<li role="presentation" class="active" id="workflowLi"><a
				href="#workflow" aria-controls="workflow" role="tab"
				data-toggle="tab">Workflows</a></li>
			<li role="presentation" id="instanceLi"><a href="#instance"
				aria-controls="instance" role="tab" data-toggle="tab">Instances</a></li>
		</ul>


		<!-- Tab panes -->
		<div id="tabContent" class="tab-content">
			<div role="tabpanel" class="tab-pane active" id="workflow">
				<div class="bs-example posR">
					<button id="createInstance" type="button"
						class="btn btn-success btn-md createInstance">Create
						Instance</button>
						<div id="filter-bar" class="tableFilterWorkflow"> </div>
					<table id="tableWorkflow" data-toggle="table"
						data-single-select="true" data-url="wf/Admin/simplifiedProcesses"
						data-cache="false" data-height="600" data-click-to-select="true"
						data-striped="true" data-pagination="true" data-search="true"
						data-sort-order="desc" data-sort-name="creationTime"
						data-show-columns="true" data-show-filter="true" data-show-refresh="true"
						data-page-size="50" data-page-list='[50, 75, 100, 200, 300, 500'>
						<thead>
							<tr>
								<th data-field="state" data-checkbox="true"></th>
								<th data-field="wfdName" data-sortable="true">Workflow Name</th>
								<th data-field="wfdVersion" data-sortable="true"
									data-searchable="false">Version</th>
								<th data-field="description" data-sortable="true">Description</th>
								<th data-field="username" data-sortable="true"
									data-searchable="false">Deployed By</th>
								<th data-field="creationTime" data-sortable="true"
									data-searchable="false">Deployed On</th>
							</tr>
						</thead>
					</table>
				</div>

			</div>
			<div role="tabpanel" class="tab-pane" id="instance">
				<div class="bs-example">
				<div id="filter-bar-instance" class="createInstance"> </div>
					<table id="tableInstance" data-toggle="table"
						data-url="wf/Admin/simplifiedInstances" data-cache="false"
						data-height="600" data-click-to-select="true" data-striped="true"
						data-pagination="true" data-search="true" data-sort-order="desc"
						data-sort-name="createTime" data-show-columns="true"
						data-show-refresh="true" data-page-size="50"
						data-page-list='[50, 75, 100, 200, 300, 500]'>
						<thead>
							<tr>
								<th data-field="check" data-checkbox="true"></th>
								<th data-field="id" data-sortable="true">Id</th>
								<th data-field="process" data-sortable="true">Workflow Name</th>
								<th data-field="version" data-sortable="true"
									data-searchable="false">Version</th>
								<th data-field="state" data-sortable="true">State</th>
								<th data-field="createdBy" data-sortable="true">Created By</th>
								<th data-field="createTime" data-sortable="true"
									data-searchable="false">Created At</th>

								<th data-field="endTime" data-sortable="true"
									data-searchable="false">Completed At</th>
							</tr>
						</thead>
					</table>
				</div>

				<button id="continueInstance" type="button"
					class="btn btn-default btn-primary">Continue</button>
				<button id="terminateInstance" type="button"
					class="btn btn-default btn-warning">Terminate</button>
				<button id="deleteInstance" type="button"
					class="btn btn-default btn-danger">Delete</button>
			</div>
		</div>

	</div>

//script
$(function() {
								$('#filter-bar').bootstrapTableFilter({
									connectTo: '#tableWorkflow',
									onSubmit: function(data) {
										var data = $('#filter-bar').bootstrapTableFilter('getData');
										 console.info(data);
									}
								});
							});
						 
						 $(function() {
								$('#filter-bar-instance').bootstrapTableFilter({
									connectTo: '#tableInstance',
									onSubmit: function(data) {
										var data = $('#filter-bar-instance').bootstrapTableFilter('getData');
										 console.info(data);
									}
								});
							});
```





Thanks for you kind help always.
![emptyselectbox](https://cloud.githubusercontent.com/assets/11829880/7336917/09f88ff6-ec31-11e4-8328-3fa62f30c559.png)


![samefilter](https://cloud.githubusercontent.com/assets/11829880/7336918/0ebd6a84-ec31-11e4-81a3-c16c851d6d0f.png)

**Comment by djhvscf** [comment] 2015-04-26 19:55
Double check the version of the plugin

**Comment by rajeshbtlit** [comment] 2015-04-27 06:54
Hi Dennis,
Could you please let me know which plugin you are taking about, did you mean bootstrap-table-filter.js ?

Appreciate your kind help.

**Comment by josedeyvi** [comment] 2015-05-29 21:33
Hi this is one solution. but I think it's not too late for an answer http://jsfiddle.net/maxgrass/d9e9y5k1/

**Comment by djhvscf** [comment] 2015-05-29 21:45
Great @josedeyvi 

Close this issue, if this is no the solution reopen it again, @rajeshbtlit

**Comment by rajeshbtlit** [comment] 2015-06-01 10:56
Hi,
Looks like when filter is enabled, search doesn't work .

**Comment by djhvscf** [comment] 2015-06-01 13:57
The problem is in the bootstrap-table-filrer.js on this line https://github.com/wenzhixin/bootstrap-table/blob/master/src/extensions/filter/bootstrap-table-filter.js#L36

**Comment by djhvscf** [comment] 2015-06-10 05:58
Ref to https://github.com/lukaskral/bootstrap-table-filter please go to the plugin repo to discuss the problem

**Closed by djhvscf** 2015-06-10 05:58 UTC
Labels: confirmed, extension
