### ISSUE TITLE
Filter in ASP.Net

### ISSUE THREAD

**Issue by migueldev** [wenzhixin/bootstrap-table#214] opened 2014-11-04 23:08 UTC
Hi, i've got problem with the code here: https://github.com/lukaskral/bootstrap-table-filter , im using the links who provide the example and  nothing appear. Mu project is on Visual Studio 2013.
What i need, is use a query on a oracle database and show the data in the bootstraptable, i need than the dropdown filters in the diferents columns fill them with the diferent data and be able to search for every colum.
![capture](https://cloud.githubusercontent.com/assets/9560399/4909602/f06c6c7c-6474-11e4-8326-7f36d087be6a.PNG)

Can you help me please

**Comment by mj399** [comment] 2015-03-21 16:10
Hi  Darkswordman

Do you have any update on the versions, i tries using v1.3.0 but it's still not working

**Comment by mj399** [comment] 2015-03-21 16:13
Hey Ipawlak

Can you suggest which bootstrap files to use to get filter working.
Thanks in advance

**Comment by lpawlak** [comment] 2015-03-21 21:31
@darkswordman @mj399 have you try download files from  https://github.com/lukaskral/bootstrap-table-filter?

**Comment by mj399** [comment] 2015-03-22 03:42
Thank Ipawlak .!!
I tried the files from the link you send but the problem is that I want filter to be appear automatically with data-show-filter= "true"

I don't want to write a script as in the example you suggested(like intializing)

Do you have any set of files that works and if  you can share , I'll really appreciate it.

**Comment by dabros** [comment] 2015-04-07 05:08
somewhat related: #678

**Comment by dabros** [comment] 2015-04-07 05:10
@mj399, btw - busy so didnt read through every post here, but i will eventually be implementing server side filtering using this approach, unless my demo app is cancelled after alpha, as i say in #528 - but this wont be too soon

**Comment by wenzhixin** [comment] 2015-04-16 08:55
Close this issue.

**Closed by wenzhixin** 2015-04-16 08:55 UTC
