### ISSUE TITLE
Сlear filter field, the table is not do query for update.

### ISSUE THREAD

**Issue by SEModer** [wenzhixin/bootstrap-table#4504] opened 2019-07-18 08:16 UTC
In release v1.15.3 and 1.15.2 there was a bug with Filter Control. Only when sidePagination: 'server'
When I clear filter field, the table is not updated. 

https://live.bootstrap-table.com/code/SEModer/295

**Comment by wenzhixin** [comment] 2019-07-29 05:59
Seems to work well: https://live.bootstrap-table.com/code/wenzhixin/360

**Comment by SEModer** [comment] 2019-07-29 08:31
Sorry, this bug from cookies. Duplicate of #4158 #4466

**Comment by crochut** [comment] 2019-09-20 15:50
> Seems to work well: https://live.bootstrap-table.com/code/wenzhixin/360

Hi, wenzhixin, it doesn't work if you add cookie extention !
The problem is these combined cases :
- filter control extention
- cookie extention 
- data-search = true

**Comment by UtechtDustin** [comment] 2019-11-02 18:15
duplicate of #4158

**Closed by UtechtDustin** 2019-11-02 18:15 UTC
Labels: filter-control
