### ISSUE TITLE
checkbox, cookie and columns not working together

### ISSUE THREAD

**Issue by s72817** [wenzhixin/bootstrap-table#6522] opened 2022-11-18 15:39 UTC
### Bootstraptable version(s) affected

">" 1.21.0

### Description

Hi,
environment:
- cookie extension
- showColumn option
- checkbox 

If I activate and deactivate some columns - reload the page - checkbox column will disappear.
https://www.canva.com/design/DAFST638aPw/WG4N5gS42QTSQrO0IJxMng/watch

Its NOT working from cookie extension 1.21.0 and later. BUT its working with cookie extension 1.20.2.
Table version is: 1.21.1

### Example(s)

https://live.bootstrap-table.com/code/s72817/13473

### Possible Solutions

Workaround for the moment:
- use bootstrap-table version 1.21.1 (newest)
- BUT use cookie extension in version 1.20.2

**Comment by s72817** [comment] 2022-11-18 17:36
> Just change line 3352 to: return false;

where exactly?

**Comment by XGRATION** [comment] 2022-11-18 17:53
**Version 1.21.1 of bootstrap-table-cookie.js**

**Currently**
Line 3350:              column.visible = !hiddenColumnsCookie.filter(function (columnField) {
Line 3351:                if (_this.isSelectionColumn(column)) {
Line 3352:                  return true;
Line 3353:                }

**Changed to**
Line 3350:              column.visible = !hiddenColumnsCookie.filter(function (columnField) {
Line 3351:                if (_this.isSelectionColumn(column)) {
Line 3352:                  return false;
Line 3353:                }

**Comment by s72817** [comment] 2022-11-18 18:59
wow, seems working! Thank you.

**Comment by svinsightdata** [comment] 2022-12-20 10:14
This bug also affects radio buttons.

**Comment by UtechtDustin** [comment] 2023-02-11 21:06
Duplicate of #6423

**Closed by UtechtDustin** 2023-02-11 21:06 UTC
Labels: confirmed, cookie, Bug
