### ISSUE TITLE
pageList不能设置All的问题

### ISSUE THREAD

**Issue by baoxianggao** [wenzhixin/bootstrap-table#2513] opened 2016-07-29 07:08 UTC
作者你好：
文档中我看到了能设置pageList为all，但是实际使用过程中我设置pageList: [8, 10, 15，All],时浏览器报错all未定义，请问一下是有什么地方没设置好吗？谢谢回答

**Comment by holmes2136** [comment] 2016-07-31 06:31
Could you provide your jsfiddle ? 
It's working for me like the following sample

https://jsbin.com/kuvazip/edit?html,js,output

**Comment by baoxianggao** [comment] 2016-08-01 06:10
thanks for your answer，my local code can not run like this,but i found another solution:when i want export all rows, i will set params.limit=-2,then make a special handling in server,they will give me all data.
but in my webPage,i still can not set all data. I will try again when the project is free,then i put my code
thank you again!
English is not good,don't mind T_T!

**Comment by sugerlemon** [comment] 2016-08-02 13:13
我也有同样问题

**Comment by wenzhixin** [comment] 2016-08-04 01:21
假如是用 js 设置你要用 'ALL' 字符串啊。

**Comment by djhvscf** [comment] 2017-12-29 08:15
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR**. Thanks!

**Closed by djhvscf** 2017-12-29 08:15 UTC
Labels: awaiting reply, help wanted
