### ISSUE TITLE
bug first loading remote json >1.10.1

### ISSUE THREAD

**Issue by ang3lx** [wenzhixin/bootstrap-table#2533] opened 2016-08-02 22:31 UTC
some hours ago I tried to update plugin from 1.10.1 to latest 1.11.0 (i've download git versione too)
but I encountered a strange behavior on loading bootstrap-table with a remote url:
on first page loading table is empty. If I push on refresh button.. data appear

From chrome resources I notice that on first page loading, my remote php script that should reply json data is not called

sorry for my english

**Comment by dabros** [comment] 2016-08-03 23:28
Please provide a Fiddle and we can help you more, dummy data from js array is fine (just needs to replicate core issue). For data-url use them from examples provided, if you need more custom server side then see http://stackoverflow.com/questions/7194408/how-can-i-use-the-jsfiddle-echo-feature-with-jquery

Examples and guide provided below:
- https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports
- #1765

You can point to any version of boostrapTable (including your own forks of the project via rawgit) very easily, remote data url can be from examples or just dummy data from anywhere

**Comment by djhvscf** [comment] 2017-12-29 08:15
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR**. Thanks!

**Closed by djhvscf** 2017-12-29 08:15 UTC
Labels: awaiting reply
