### ISSUE TITLE
Footer doesn't update after X-Editable change

### ISSUE THREAD

**Issue by strikerjjb** [wenzhixin/bootstrap-table#1991] opened 2016-02-15 00:18 UTC
I have a table that has 6 months and quantities for each month when I update the quantity the footer row does not update to the new sum until I refresh the page.

![image](https://cloud.githubusercontent.com/assets/10637609/13037482/70fb0dc2-d34f-11e5-9bb2-217990779033.png)

Updating the column seems to do a string concatenation of all the quantity values. i am using the oneditsave function and passing in the RefreshOptions method with the columns. Result shown below:

![image](https://cloud.githubusercontent.com/assets/10637609/13037492/a43c2c34-d34f-11e5-9ced-d6f83d6046d5.png)

**Comment by dabros** [comment] 2016-02-15 01:24
@strikerjjb - im happy to do **PR** for this, but need a fiddle to work with pls

https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

What im thinking is simply call `resetFooter` from within extension  (https://github.com/wenzhixin/bootstrap-table/blob/develop/src/bootstrap-table.js#L2002)

**Comment by strikerjjb** [comment] 2016-02-15 01:28
@dabros I will work on putting a fiddle together and will post back here when it is up.

**Comment by strikerjjb** [comment] 2016-02-15 02:45
@dabros working fiddle at http://jsfiddle.net/ytgsf6Lz/

each edit does nothing to update footer.

**Comment by dabros** [comment] 2016-02-15 04:48
**PR** made: #1992

Please close this issue and post there if any problems with this fix

**Comment by djhvscf** [comment] 2016-02-16 00:05
@dabros just a comment.. When you open a PR you should include in the commit title "Fix #(issue number)" in order to link the issue and the PR and then when the PR is merged, the issue is closed automatically.

**Comment by dabros** [comment] 2016-02-16 02:59
@djhvscf - thanks for tip, updated title

**Comment by wenzhixin** [comment] 2016-02-17 05:31
Merged in develop branch.

**Closed by wenzhixin** 2016-02-17 05:31 UTC
Labels: fixed
