### ISSUE TITLE
Error in IE 11: Object doesn't support property or method 'includes'

### ISSUE THREAD

**Issue by tenshs** [wenzhixin/bootstrap-table#4144] opened 2019-01-29 08:46 UTC
after migrating from version 1.12.2 to version 1.13.3, the syntax "includes" doesn't work in the IE 11 browser.

the following error reference:
SCRIPT438: Object doesn't support property or method 'includes'
bootstrap-table.js (879,11)

**Comment by wenzhixin** [comment] 2019-01-29 09:39
Duplicate of #4098

**Closed by wenzhixin** 2019-01-29 09:39 UTC
