### ISSUE TITLE
data-detail-formatter not refreshed after bootstrap table refresh was called

### ISSUE THREAD

**Issue by siebonguyen** [wenzhixin/bootstrap-table#6243] opened 2022-07-04 08:16 UTC
### Bootstraptable version(s) affected

1.20.2

### Description

I am using vue with bootstrap table and turn detailView on.
After finishing edit one expanded row data, I call refresh method:
`$('#contactTable').bootstrapTable('refresh');`
The table was refreshed and row keep expanded, however its content was not updated with new values.
I found that the detail-fomatter function was not called in this case.

Next, I tried to cheat by calling collapse then expand the row:
```
$('#contactTable').bootstrapTable('collapseRowByUniqueId', 86315);
$('#contactTable').bootstrapTable('expandRowByUniqueId', 86315);
```
Yay, the detail formatter function was triggered. But wait, the object `row` passed to the function was still old values, how unlucky.
```
function contactDetailFormatter(index, row) {
    console.log(row);    // still old object
}
```
So please add a bug fix that:

-  Detail formatter function would be triggered after a refresh was called
-  New `row ` object passed to formatter function

**Comment by wenzhixin** [comment] 2022-07-06 00:34
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem. Thanks!

**Comment by UtechtDustin** [comment] 2022-07-15 21:04
I'm closing this issue, because we got no example from you within 7 days.
If you still need help please provide us an example.

**Closed by UtechtDustin** 2022-07-15 21:04 UTC
Labels: needs example, Bug

**Comment by ok300** [comment] 2023-06-05 11:14
I came across the same issue: https://live.bootstrap-table.com/code/ok300/15526

Steps to reproduce in the example:
* Expand the row with "Item 3"
* Click the `updateCellByUniqueId` button
* The item name is updated in the row, but not in the Detail View.
* Closing / re-opening Detail View shows the new value.

IMO the issue is closing / reopening shoudn't be necessary. When table data is updated, the detail formatter function should be re-triggered.
