### ISSUE TITLE
bootstrap-table overlap form input

### ISSUE THREAD

**Issue by ericduhamel** [wenzhixin/bootstrap-table#1760] opened 2015-11-29 23:21 UTC
Hi,

I use bootstrap 3.
I designed the side with a left panel for the menu and the main content to the right.

Both section is under a container-fluid and row fluid.
My main part is under a tab-content and tab-pane.

When i use a table in the panel who have many line, it's overlap my form under it.
http://jsfiddle.net/z7n1b27z/

image
http://picpaste.com/bootstrap-table-AEouqdFx.jpeg

I see then in the  : fixed-table-container class, padding-bottom is set is 0px

When i have many column fixed-table-container class set value 40 to padding-bottom
http://jsfiddle.net/ntwnwowf/

is there a problem with bootstrap table wit a table with one column?

**Comment by dabros** [comment] 2015-11-30 00:29
@ericduhamel - never seen a table setup like that, using full output html for rows and table options too...

Im not saying you cant do it, but it felt wrong to me, and for maintainence and performance i suggest you look at json (url or array) options, maybe init with js, maybe with `data-toggle="table"` (important to note that `data-toggle="table"` can cause issues with scope, if using formatters or other advanced options and other onDomReady scope closures.

In any case, remove the `data-height="300"` and it works fine.

Not certain why that caused issue (though your 'min-height' needs unit, just not number, but also wont be respected in most cases, see in fiddle)

I suggest maybe reworking your table to match another format, like seen here:

https://github.com/wenzhixin/bootstrap-table#reporting-issues
https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

Also do see the many examples, which show bootstrap-tables defined from pure html, and others showing a mixture of js, html and json data url (use 'view source in github' in top right)

http://issues.wenzhixin.net.cn/bootstrap-table/
http://issues.wenzhixin.net.cn/bootstrap-table/#options/from-html.html
http://issues.wenzhixin.net.cn/bootstrap-table/#options/from-data.html

http://bootstrap-table.wenzhixin.net.cn/getting-started/ guide

----

Perhaps then try applying `data-height` and see if respected, as i have a hunch its because of how you declare your rows, but thats just a guess

If it still fails, try like i did and place 'clearfix' elements between, and maybe look at `data-pagination="true"` if your fixed on a certain height.

But removing `data-height` showed all rows with break then form, and moving that `min-height` to the wrapper div (and adding 'px' to it) should make min-height be respected, if isnt respected on table itself.

**Comment by wenzhixin** [comment] 2015-11-30 00:40
You can init the table when you click a tab instead of init all table one time. 
or: 
Use resetView method when you click a tab.

**Comment by ericduhamel** [comment] 2015-11-30 00:58
i use ajax call to feed the table, just not using it in the example.

Question it's more why in one case that work and in the other not.
Someting don't set correctly the value for padding-bottom in the fixed-table-container class.

**Comment by dabros** [comment] 2015-11-30 05:30
@ericduhamel - as i said, removing `data-height` solved it, so just open the fiddle in 2 tabs, then in second tab remove that attribute and see difference

I noticed change almost immediate.

Your broken inline style is ignored (as no unit, just number) but the height is applied to '.fixed-table-container', a parent of table itself. 

That conficts somehow, not entirely clear why.

Maybe update your fiddle and keep both versions open to see how you can use explicit height without issue, whether its unique to it being inside panels, ect.

Footer padding does seem likely, and no im not sure why '.fixed-table-container' padding needs to be set like that, or if its something else causing this.

But in any case, add `overflow: hidden;` to '.fixed-table-container' (or another element if fits better) and that fixes it.

Cant say whether it is a bug or not yet, or just intersection of other elements in view, but seeing as it has been quoted twice i will try to reproduce on vanilla code and if yes will make quick PR if applicable

**Comment by dabros** [comment] 2015-11-30 05:47
**Solved**

Its you, not me ;)

```javascript

$('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
  e.target // newly activated tab
  e.relatedTarget // previous active tab
  
  console.log('shown.bs.tab ',e);
    
    $('#setupDrawerTableResult').bootstrapTable('resetView');
})

```

So either use css rule `overflow:hidden` on '.fixed-table-container', **OR** (preferred, and as @wenzhixin asked you to do) use code similar to above to call `resetView` on tab nav, **OR** rework your init so avoids this need.

Its the init script causing issues, im guessing the dynamic elements resized so needs to be called again. 

Either break up your init so less `data-toggle` reliance, which should work for you if you call it from appropriate location, such as after tabs init or similar (data-toggle has many flaws, better to rely on explicit timing)

Or use callback like shown above.

Not a bug at all

**Comment by mctdi** [comment] 2015-11-30 13:45
that work fine, thank

**Comment by dabros** [comment] 2015-11-30 23:41
@ericduhamel - pls confirm this worked for you too, then close issue

**Comment by wenzhixin** [comment] 2015-12-02 01:52
Thanks @dabros, close the issue.

**Closed by wenzhixin** 2015-12-02 01:52 UTC

**Comment by mctdi** [comment] 2016-01-15 18:43
there are some example like this one where data-height don't have any unit
https://github.com/wenzhixin/bootstrap-table-examples/blob/master/options/detail-view.html
