### ISSUE TITLE
v1.15.x ain't working in IE browser ( v 1.14.2 works for me)

### ISSUE THREAD

**Issue by mattavireddy** [wenzhixin/bootstrap-table#4629] opened 2019-10-10 14:43 UTC
bootstrap table of versions 1.15.x ain't working in IE browser ( but v 1.14.2 works for me)

I am using TypeScript with Webpack (bluebird as promise polyfill), 
New version like 1.15.x works in chrome when i run my application in 
IE (edge, 10) browser then gets following error (see image)

![image](https://user-images.githubusercontent.com/35302701/66578929-9abb4a80-eb99-11e9-8632-67f5c1643903.png)

When i run my application in IE 9 then gets following error
![image](https://user-images.githubusercontent.com/35302701/66579406-6bf1a400-eb9a-11e9-98ab-7a44f78a4d8f.png)

**Comment by UtechtDustin** [comment] 2020-02-02 18:43
@djhvscf could you please check if that issue is fixed in the newest version ?
I cant reproduce the issue in my VM (IE 11.418).

**Comment by djhvscf** [comment] 2020-02-02 18:57
Yes, it is working as expected

**Closed** 2020-02-02 18:57 UTC
Labels: browser dependent
