### ISSUE TITLE
Export table to excel  is not working

### ISSUE THREAD

**Issue by saranyakannan** [wenzhixin/bootstrap-table#3592] opened 2018-02-06 10:15 UTC
It doesnt work in the example as well. http://issues.wenzhixin.net.cn/bootstrap-table/

**Comment by jimgit** [comment] 2018-02-06 10:56
I just tried it in CHROME, IE and Edge on Windows 10and it worked

![image](https://user-images.githubusercontent.com/1921941/35855922-2438e420-0afa-11e8-8c76-f2551ae7cc8e.png)

![image](https://user-images.githubusercontent.com/1921941/35855747-a0fff3aa-0af9-11e8-865e-6558c347412c.png)

![image](https://user-images.githubusercontent.com/1921941/35855778-ba225fee-0af9-11e8-8d94-ae37a68a4f90.png)

**Comment by wenzhixin** [comment] 2018-02-27 16:44
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide more information, thanks!

**Closed by wenzhixin** 2018-02-27 16:44 UTC

**Comment by CBarratt63** [comment] 2018-03-15 03:17
I'm not the original poster, but as I have come across this problem as well, I will try to give you some further information.
The error occurs when opening the created xlsx file - hence the browser console will show nothing. The error encountered is "Excel found unreadable content in 'tableExport.xlsx'. Do you want to recover the contents of this workbook ?  If you trust the source of this workbook, click Yes.".
If you click Yes, the file is able to be recovered and read ok, however, it would appear the .xlsx file is being generated with a minor error.
The problem is easily seen when you use the example quoted above, do the export, then try to open the created file. I have tested in Firefox and Chrome.

**Comment by CBarratt63** [comment] 2018-03-15 03:21
Also, this seems to have happened since upgrading to V1.9.8 of tableExport.jquery.plugin

**Comment by wenzhixin** [comment] 2018-03-15 03:51
I have tried to export Excel file: `tableExport.xls`, open it and it is working well.

**Comment by CBarratt63** [comment] 2018-03-15 04:11
What version of Excel are you using to open it ?  
Mine is Excel 2010  V14.07194.5000
Perhaps you are using something more recent ?  :-)

**Comment by wenzhixin** [comment] 2018-03-15 07:19
@hhurz maybe know what's the problem

**Comment by dena1111** [comment] 2018-03-15 11:34
Hey,
I have the same problem. I use Excel 2016 and the error is:
We found a problem with some content in 'fileName.xlsx'.Do you want to try to recover as much as we can? If you trust the source of this workbook, click yes.

I also get an error when i try to open a xls file. it happen even with the given example for this plugin.

**Comment by wenzhixin** [comment] 2018-03-16 02:04
https://github.com/hhurz/tableExport.jquery.plugin#installation

Maybe this information can be helpful.

> To export the table in XLSX (Excel 2007+ XML Format) format, you need to include additionally:
> ```
> <script type="text/javascript" src="libs/js-xlsx/xlsx.core.min.js"></script>
> ```

**Comment by CBarratt63** [comment] 2018-03-16 03:27
Yep, have that included.  I should re-iterate that this was working fine for 12 months and only started having the new behaviour after an upgrade that included V1.9.8 of tableExport.jquery.plugin.  

It is still curious why the example works for some and not others... 
So far we have it not working for Excel 2010 and Excel 2016.
What versions does the example work with ?

**Comment by wenzhixin** [comment] 2018-03-16 05:54
Version 1.9.10
https://rawgit.com/hhurz/tableExport.jquery.plugin/master/tableExport.js

**Comment by hhurz** [comment] 2018-03-17 12:02
FYI: Due of an undefined sheet name in the workbook definition, Excel (or some versions of it ?) complained about unreadable content. I just released version 1.9.10 of tableExport.jquery.plugin that should fix that. Please note that this release requires also to update xlsx.core.min.js, which you need to import for xlsx support.

**Comment by Immontalis** [comment] 2018-03-18 21:30
@wenzhixin @hhurz  is there any posibillity to export the html table in xlsx with image?
i have tryed many thinks but nothing worked. if i use htmContent:true than i will geht an img link but not the image it self in my file.

**Comment by CBarratt63** [comment] 2018-03-19 05:54
@hhurz  that fixed it. Many thanks.

**Comment by coderasp** [comment] 2018-09-20 21:34
@wenzhixin @hhurtz @CBarratt63 I included latest version  tableExport.jquery.plugin Version 1.10.2. But still getting error while opening .xls file
![error](https://user-images.githubusercontent.com/36758944/45848120-e0735e00-bd5f-11e8-8b30-4958adc185a0.png)

**Comment by kshipp** [comment] 2019-08-26 04:49
I'm also getting the same Excel error as mentioned previously in this thread -- using the latest versions of everything....  using FF as the browser.

**Comment by wenzhixin** [comment] 2019-08-26 08:16
@kshipp If problem exits, you can create a new issue in https://github.com/hhurz/tableExport.jquery.plugin repo.
