### ISSUE TITLE
updateByUniqueId works wrong for filtered table

### ISSUE THREAD

**Issue by serefbilge** [wenzhixin/bootstrap-table#2209] opened 2016-04-21 08:08 UTC
Hi, 

updateByUniqueId method searches data inside all data and gets index of it; but it updates inside filtered data with this index. It can be fixed by changing 

"$.extend(this.data[rowId], params.row);" --> $.extend(this.options.data[rowId], params.row);

**Comment by djhvscf** [comment] 2016-04-21 13:30
ok, lets do this:

Provide an example with the issue
Provide an example with the fix
Open a new **PR**

**Comment by drawlinson** [comment] 2016-05-03 05:32
I am also having this problem. I don't have a full example yet but the gist of it is:

1. Create the bootstrap table instance, ( which I'm guessing implicitly creates a filtered data copy)
e.g.

         $(tableId).bootstrapTable({
         uniqueId: 'viewerId',  
         checkboxHeader: true,
         editableEmptytext: 'Edit',
         searchOnEnterKey: true,
         searchTimeOut: 50,
         onEditableSave: onEditSave,
         onResetView: onResetView,
         filterControl: true,
         sortName: true,
         sortOrder: true,
         maintainSelected: true,
         columns: tableHeaders, 
         data: tableRows
       }); 

2. Update some table data, which only modifies the filtered data copy. e.g.

            parent.$('#recordings-table', window.parent.document).bootstrapTable('updateByUniqueId', {
                id: qMedia,
                row: {
                    media: vMedia,
                    mediaVal: mediaArr.join(),
                    size: vSize
                }
            });

3. Apply any filter to the table.

e.g.

        $(".studyResult").val('<i class="fa fc-success playable">&nbsp;Successful</i>').change();

4. The modified data has now been reverted to the original data. The modifications are never seen again.

If I can make a compilable example I'll post it here.

**Comment by drawlinson** [comment] 2016-05-03 05:39
I can confirm the fix reported above. Here's the fixed method from bootstrap-table.js:

  BootstrapTable.prototype.updateByUniqueId = function (params) {
        var rowId;

        if (!params.hasOwnProperty('id') || !params.hasOwnProperty('row')) {
            return;
        }

        rowId = $.inArray(this.getRowByUniqueId(params.id), this.options.data);

        if (rowId === -1) {
            return;
        }

        $.extend(this.options.data[rowId], params.row);
        this.initSort();
        this.initBody(true);
  };

**Comment by drawlinson** [comment] 2016-05-03 05:40
This issue is probably ALREADY fixed in production branch because the equivalent line reads:

            $.extend(that.options.data[rowId], params.row);

However master branch is broken as originally specified in this issue.

**Comment by wenzhixin** [comment] 2016-07-12 05:15
I think this problem is fixed now, please use the latest version: v1.11.0

**Closed by wenzhixin** 2016-07-12 05:15 UTC
Labels: needs example
