### ISSUE TITLE
Footer padding bottom goes wrong

### ISSUE THREAD

**Issue by alvin0618** [wenzhixin/bootstrap-table#1689] opened 2015-11-14 10:06 UTC
When table option `height: 'auto'` and `showFooter: true`, the padding-bottom suppose set 0px, however it give a value there that caused extra padding on bottom.

Here is the fiddler example: http://jsfiddle.net/qLo4vj8h/2/

I have solved the problem in function `BootstrapTable.prototype.resetView`

```
        if (this.options.showFooter) {
            this.resetFooter();
            if (this.options.height) {
                padding += this.$tableFooter.outerHeight() + 1;
            }

            if (this.options.pagination === false) {
                padding = 0;
            }
        }
```

I am not sure is this solution is the correct way to apply. Seeking for advises , Thank you.

**Comment by wenzhixin** [comment] 2015-11-16 02:24
Thanks for your feedback, but now our plugin does not support `height: 'auto'` option.

**Comment by LockTar** [comment] 2015-11-18 09:20
I've got the same issue and created a new fiddle.
http://jsfiddle.net/hbzctayu/

This Fiddle is cleaner and much more basic. The problem is an important padding styling of 8px.

I don't understand why the footerformatter isn't working because it does work in my solution. But then the problem is still there.

**Comment by dabros** [comment] 2015-11-20 05:48
@LockTar - 'no wrap in HEAD' is what you needed to select for the js.

Basically, `data-toggle` is common way of auto-initializing plugins on objects after domReady, but any code it links to needs to be in scope when it is called.

Easy mistake to make with fiddles, just updated your fiddle with that option, nothing bout columns fixed.

http://jsfiddle.net/dabros/403zq9yb/

**Comment by dabros** [comment] 2015-11-20 05:52
@alvin0618 - like @wenzhixin said, `height: 'auto'` not supported, and removing that 'seemed' to fix your fiddle, but please clarify with clear 'expected output' vs 'actual output' if that is not sufficient.

@LockTar - please also clarify the 'expected output' vs 'actual output' to say whether padding size, column offset issue (maybe specific to browser) or both you refering to, as i dont see either in both fiddles (once `height: 'auto'` removed)

**Comment by LockTar** [comment] 2015-11-21 13:03
Thanks @dabros, I see the counter working now. Off course the problem is still there. I updated the fiddle to v3 and updated the link above. 

Your right, my comment is not very clear. With the same problem, I mean that the footer row (were the counter is) the padding is wrong. I tested in Chrome, Edge and IE11 on Windows 10. In every browser I got the same problem. The width of the counter column (with the number 4) is to wide. The right column border of that column is crossing the second column.

**Comment by LockTar** [comment] 2015-11-21 13:05
And yes, this is the same problem as #1613.

**Comment by dabros** [comment] 2015-11-24 03:20
@LockTar - when you get chance, pls see PR #1684 (also linked from #1613) and confirm if that solves your issue. If not, please post there or in #1613, as it appears to be different issue to original issue here (from @alvin0618)

@alvin0618 - still waiting you to confirm, but your problem seems solved so pls confirm and close this topic.

**Comment by LockTar** [comment] 2015-11-24 06:36
I commented in the #1613 issue. Thanks!

**Comment by wenzhixin** [comment] 2015-12-02 06:25
Have you solved your problem? @LockTar

**Comment by LockTar** [comment] 2015-12-04 12:50
The problem is almost gone. The big paddings like you see in #1613 are gone. But now I have one column with a custom formatter. When I place an icon in the footer formatter the padding is still a few pixels off. I don't have that problem with a button.

```javascript
function infoFormatter(value, row, index) {
  var infoItems = new Array();

  var errorIcon = '<span class="glyphicon glyphicon-exclamation-sign text-danger" aria-hidden="true" title="Geen sportlocatie en of taken"></span>';
  //var warningIcon = '<span class="glyphicon glyphicon-warning-sign text-warning" aria-hidden="true" title="Niet genoeg taken"></span>';
  var addTaskBtn = '<a href="/Admin/BasketballTask/Create?basketballMatchId=' + row.Id + '&controllerName=BasketballMatch" class="btn btn-xs btn-success" title="Taak toevoegen"><i class="fa fa-plus"></i> Taak</a>';

  //if (row.Location == null || (showTasks && row.Location.IsMatchLocationForThisClub && row.Tasks.length < 0)) {
  	infoItems.push(errorIcon);
  //	infoItems.push(' ');
  //}

  //if (showTasks && row.Location != null && row.Location.IsMatchLocationForThisClub && (row.Tasks.length > 0 && row.Tasks.length < 5)) {
  //	infoItems.push(warningIcon);
  //	infoItems.push(' ');
  //}

  //if (showTasks && row.Location != null && row.Location.IsMatchLocationForThisClub && row.Tasks.length < 5) {
  //	infoItems.push(addTaskBtn);
  //}

  return infoItems.join('');
}
```

**Comment by wenzhixin** [comment] 2018-04-05 16:01
Fixed in the latest version: http://jsfiddle.net/wenyi/e3nk137y/26123/

**Closed by wenzhixin** 2018-04-05 16:01 UTC
Labels: js

**Comment by mtngnn** [comment] 2021-03-14 18:36
This error still exists
