### ISSUE TITLE
Uncaught TypeError: Cannot read property 'field' of undefined

### ISSUE THREAD

**Issue by sxahmed** [wenzhixin/bootstrap-table#1218] opened 2015-07-27 14:19 UTC
Uncaught TypeError: Cannot read property 'field' of undefined
![bootstrap-table-error](https://cloud.githubusercontent.com/assets/13351741/8908120/d0b70f5e-343f-11e5-834c-2f94a263f5fa.PNG)
![bootstrap-table-error](https://cloud.githubusercontent.com/assets/13351741/8908225/82e222d6-3440-11e5-825f-06a7d231c060.PNG)

(anonymous function) @ bootstrap-table.min.js:7n.extend.each @ jquery.js:374n.fn.n.each @ jquery.js:139(anonymous function) @ bootstrap-table.min.js:7n.extend.each @ jquery.js:374n.fn.n.each @ jquery.js:139o.initTable @ bootstrap-table.min.js:7o.init @ bootstrap-table.min.js:7o @ bootstrap-table.min.js:7(anonymous function) @ bootstrap-table.min.js:8n.extend.each @ jquery.js:374n.fn.n.each @ jquery.js:139a.fn.bootstrapTable @ bootstrap-table.min.js:8(anonymous function) @ bootstrap-table.min.js:8n.Callbacks.j @ jquery.js:3099n.Callbacks.k.fireWith @ jquery.js:3211n.extend.ready @ jquery.js:3417I @ jquery.js:3433

**Comment by sxahmed** [comment] 2015-07-27 14:21
I am new to bootstrap-table but when I included the bootstrap-table to my application 

ex:  <table class="table table-striped" data-toggle="table">

I have tried using table example from bootstrap-table but the error keeps popping all the time.

**Comment by wenzhixin** [comment] 2015-07-28 01:57
Can you provide a jsFiddle to show your problem?

**Comment by CathalG** [comment] 2015-08-04 11:57
Hey there,

I just finished troubleshooting this same issue, make sure your table includes table header and table body tags:

<thead>
<tbody>

Problem solved

**Comment by sxahmed** [comment] 2015-08-04 19:32
You nailed it. My table had no <thead> and no <tbody> . After adding I get no  " Uncaught TypeError: Cannot read property 'field' of undefined "

Thank you CathalG

**Comment by wenzhixin** [comment] 2015-08-05 10:04
Please use a standard table.

**Comment by rameshfernandez** [comment] 2016-07-08 05:44
@CathalG You just saved my time. thank you. it works after adding 
```
<thead></thead>
<tbody></tbody>
```

**Comment by InsomniumBR** [comment] 2016-11-02 20:54
What about warning that the table is missing this fields? I lost some time on this, because I was using an ASP.Net MVC sample table...

**Comment by gogaz** [comment] 2019-06-11 09:18
I came across this issue because I had more columns than headers in my table. Hope this could help someone

**Comment by BeardyB** [comment] 2019-08-28 09:51
This error message also occurs if the number of <th>-elements is unequal the number of <td>-elements

**Comment by rachelluethi** [comment] 2020-06-15 09:59
I got the same error message. I have <thead> and <tbody>, number of header columns equals the number of columns in tbody, tags are all closed. Is there another problem leading to the same error message?

**Comment by UtechtDustin** [comment] 2020-06-15 10:23
@rachelluethi Please provide us an example using our [online editor](https://live.bootstrap-table.com/)

**Comment by djhvscf** [comment] 2020-06-15 15:16
Reopened it for tracking purposes

**Comment by rachelluethi** [comment] 2020-06-15 15:22
The problem was that colspan is not considered in <thead> (?). I could solve it by adding the same amount of <th> in <thead> as the sum of colspans defined.

Example:

```
<thead>
 <th></th>
 <th></th>
 <th></th>
 <th></th>
 <th></th>
</thead>
<tbody>
<tr colspan="1"></tr>
<tr colspan="3"></tr>
<tr colspan="1"></tr>
</tbody>
```

**Comment by UtechtDustin** [comment] 2020-06-15 15:24
@rachelluethi ask already said, please provide a example using our editor.

**Comment by UtechtDustin** [comment] 2020-06-15 15:47
Im not sure if we support colspan/rowspan on the tbody.
There is a method called `mergeCells` : https://examples.bootstrap-table.com/#methods/merge-cells.html

@wenzhixin @djhvscf could you check this ?

**Comment by djhvscf** [comment] 2020-06-15 17:02
I think you can use the mergeCells method in order to do that

**Comment by wenzhixin** [comment] 2020-07-05 15:09
> Thank you!
> I added a working and a non-working example:
> https://live.bootstrap-table.com/code/rachelluethi/3433
> https://live.bootstrap-table.com/code/rachelluethi/3434

Duplicate of #4562

**Closed by wenzhixin** 2020-07-05 15:09 UTC

**Comment by keithpickett** [comment] 2021-01-28 02:00
Adding my $0.02 worth:
I had this exact same issue and after reading this thread, was able to solve my problem. My table was set up like this with a td instead of a th like so:
```
<thead>
   <td></td>
   <th></th>
   <th></th>
   <th></th>
   <th></th>
</thead>
```
This falls under @BeardyB 's comment above regarding unequal number of elements.  Hope this helps someone.
