### ISSUE TITLE
Plan to remove jQuery

### ISSUE THREAD

**Issue by djhvscf** [wenzhixin/bootstrap-table#5526] opened 2021-01-05 08:29 UTC
**Description**  
We should be planning the process to remove jQuery. I know that this could be a huge work but I think it worth. My proposal is that we need to have a strong unit testing and then we need to start removing jQuery.

I was working on this and you can see the progress in this branch

https://github.com/wenzhixin/bootstrap-table/tree/feature/modular_js

Please let me know your thoughts

**Comment by ufhy** [comment] 2021-01-08 14:19
up

**Comment by TiKevin83** [comment] 2021-04-11 03:25
This would be really helpful given bootstrap 5's dropping of jQuery. I was able to drop a dependency on jQuery on https://runs.tas.bot/runs.html by migrating from bootstrap 4 to 5, but when implementing more advanced table functionality using boostrap-table I had to add jQuery back in (though it does seem to at least work fine with jQuery slim).

**Comment by jimmywarting** [comment] 2022-08-20 18:02
bump

**Comment by UtechtDustin** [comment] 2022-08-20 18:05
Duplicate of #4796
@jimmywarting please check this issue, there is a recent answer :-)

**Closed by UtechtDustin** 2022-08-20 18:05 UTC
Labels: feature, core
