### ISSUE TITLE
How to override method in  Filter Control 

### ISSUE THREAD

**Issue by XEnmaai** [wenzhixin/bootstrap-table#4589] opened 2019-09-12 06:17 UTC
HI,
I want to override  some methods in UtilsFilterControl , but "UtilsFilterControl" is sealed, is there some way to do this.

for example:
`UtilsFilterControl.getFilterDataMethod = function getFilterDataMethod(objFilterDataMethod, searchTerm) {
	    var keys = Object.keys(objFilterDataMethod);

	    for (var i = 0; i < keys.length; i++) {
	      if (keys[i] === searchTerm) {
	        return objFilterDataMethod[searchTerm];
	      }
	    }
	    //custom filter method 
	    if('dictionary' === searchTerm){
	    	return dicfilter;
	    }
	    return null;
	}`

**Comment by UtechtDustin** [comment] 2019-09-28 23:37
Duplicate of #4559.

**Closed by UtechtDustin** 2019-09-28 23:37 UTC
