### ISSUE TITLE
refreshOptions sort by date / datetime

### ISSUE THREAD

**Issue by jynxy** [wenzhixin/bootstrap-table#5964] opened 2021-11-25 11:27 UTC
### Description

Hi,

Using a custom filter to sort, i have it working for name etc but when it comes to dates its not working, date format is dd-mm-yyyy or dd-mm-yyyy hh:ii

```
function first_day_new()
{
	$("#table").bootstrapTable("refreshOptions",
	{
		sortName: "first_day",
		sortOrder: "desc",
	  });
	
	set_pagination_id();
}
```

How can i get it to filter by date and also datetime.

Thanks

**Comment by UtechtDustin** [comment] 2021-11-25 11:49
Duplicate of #4978.

**Closed by UtechtDustin** 2021-11-25 11:49 UTC
Labels: help-wanted
