### ISSUE TITLE
Problem with iPhone device

### ISSUE THREAD

**Issue by brmeloleite01** [wenzhixin/bootstrap-table#5299] opened 2020-09-14 19:19 UTC
**Bootstraptable version(s) affected**:
1.16.0

**Description**  
The table is not showing any data only on iOS device... I've already testing on android and desktop, the same code works there.
Anyone had the same problem??

I tested now, and it works on safari browser, but not in phonegap ios

**Comment by djhvscf** [comment] 2020-09-15 06:38
Which version of Safari are you using?

**Comment by UtechtDustin** [comment] 2020-09-15 07:22
I cant reproduce it on macos (safari 13.1.2) and ios (safari 13).

**Comment by UtechtDustin** [comment] 2020-09-22 14:30
We are closing this issue as we cant reproduce it and you didn't responed.
If you still have this issue please answer the question of @djhvscf .

**Closed by UtechtDustin** 2020-09-22 14:30 UTC
Labels: awaiting reply, browser dependent
