### ISSUE TITLE
fixedColumns and showFooter not working

### ISSUE THREAD

**Issue by mfito** [wenzhixin/bootstrap-table#4938] opened 2020-03-18 10:12 UTC
when adding fixedColumn option to a table with option showFooter: true, then the fixed columns overflows the footer, furthermore the scrolling lags at the end because of the footer height, which is not observed.

my Configuration:
`$table = $table.bootstrapTable({
        locale: 'de-DE',
        height: 200,
        search: true,
        sortalbe: true,
        showFooter: true,
        classes: 'table table-bordered bg-white',
        fixedColumns: true,
        fixedNumber: 2
    });`

[https://live.bootstrap-table.com/code/mfito/2191](https://live.bootstrap-table.com/code/mfito/2191)

**Comment by wenzhixin** [comment] 2020-03-20 16:05
Duplicate of #4264

**Closed by wenzhixin** 2020-03-20 16:05 UTC
