### ISSUE TITLE
Information about requirement [Help-Wanted]

### ISSUE THREAD

**Issue by ramanjaneya-karnati** [wenzhixin/bootstrap-table#3627] opened 2018-02-26 18:12 UTC
Hi,
I have a query before implementing the bootstrap tables in my project.

I have a requirement of adding a new row to the table by clicking Add New Row button.

The new row should be added below the parent row where I clicked the button. after entering the data and navigate through pagination. Will the data available in the table. I mean is there any state save method available so that we can save to the grid.

The data needs to be there if I navigate through pagination.

Thanks,
Ramanjaneya

**Comment by UtechtDustin** [comment] 2019-04-22 05:09
You can use the group-by extension to have "parents" or you use a field which is sorted.
The row remains after switching rows.

The issue is old, so i will close it. If you still need help/more information pls reopen the issue.

**Closed by UtechtDustin** 2019-04-22 05:09 UTC
Labels: help wanted
