### ISSUE TITLE
updateByUniqueId additional param "rewrite"

### ISSUE THREAD

**Issue by kolobok55** [wenzhixin/bootstrap-table#3714] opened 2018-03-27 15:29 UTC
for example my row is 
{"id":"1", "some1":"2", "some3":"3"}
i want to update it with updateByUniqueId, but i want just delete some3
{"id":"1", "some1":"2", "some3":""}
in this case i must send to table field "some3" and empty value, but i want just ommit this field
{"id":"1", "some1":"2"}
I think, that this method need to have additional boolean param rewrite, to fully replace data of row.

**Comment by UtechtDustin** [comment] 2019-06-15 19:34
duplicate of #3079

**Closed by UtechtDustin** 2019-06-15 19:34 UTC
Labels: help wanted
