### ISSUE TITLE
Filtered tags other than text in filter control extension

### ISSUE THREAD

**Issue by redtide** [wenzhixin/bootstrap-table#5378] opened 2020-10-13 14:39 UTC
**Bootstraptable version(s) affected**:
Bootstrap v4.0.0 and Bootstrap Table v1.18.0

**Description**  
If a data cell contains tags like href links, the filter get them as part of the text, making the input search function unusable or, in the case of a select, garbage values.

**Example**  
https://live.bootstrap-table.com/code/redtide/5083 using the normal filter
https://live.bootstrap-table.com/code/redtide/5085 with the custom container (as a side note it seems not possible to use a placeholder attribute).
The filter doesn't work when using `h` `r` `e` or `f` etc. characters as search filters.

**Possible  (optional)**  

**Additional context**

**Comment by UtechtDustin** [comment] 2020-10-13 15:38
Duplicate of #5146, thanks for the report ! :-)

**Closed by UtechtDustin** 2020-10-13 15:38 UTC
Labels: Bug
