### ISSUE TITLE
Sort date/datetime columns

### ISSUE THREAD

**Issue by faran-mw** [wenzhixin/bootstrap-table#5280] opened 2020-09-03 12:44 UTC
I have noticed that date columns are treated as string and sorted accordingly. It would be great to set a data type on columns so sort can work for non string columns as well.

**Comment by UtechtDustin** [comment] 2020-09-03 12:51
You can use [customSort](https://bootstrap-table.com/docs/api/table-options/#customsort).   
Example: https://examples.bootstrap-table.com/#options/custom-sort.html

**Comment by wenzhixin** [comment] 2020-09-06 15:39
https://examples.bootstrap-table.com/#column-options/sorter.html
Duplicate of ##65

**Closed by wenzhixin** 2020-09-06 15:39 UTC
Labels: awaiting reply
