### ISSUE TITLE
使用bootstrap-table-group-by扩展时发生异常

### ISSUE THREAD

**Issue by uyong** [wenzhixin/bootstrap-table#3224] opened 2017-06-23 04:01 UTC
执行到 tableGroups.forEach(function(item){}时发生异常：
Uncaught TypeError: Cannot read property 'forEach' of undefined
    at e.BootstrapTable.initBody()
调试时发现tableGroups is undefined。

**Comment by djhvscf** [comment] 2017-06-23 04:09
Can you translate this issue to english, please?

**Comment by uyong** [comment] 2017-08-23 08:50
when i use extension of bootstrap-table-group-by, occur error:"Uncaught TypeError: Cannot read property 'forEach' of undefined. at e.BootstrapTable.initBody()".
detail error:
![image](https://user-images.githubusercontent.com/11604426/29607145-e78491c8-8822-11e7-9a23-3af346a61cc3.png)

**Comment by wenzhixin** [comment] 2017-12-20 14:22
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by djhvscf** [comment] 2018-01-29 05:45
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR** with an [example](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports). Thanks!

**Closed by djhvscf** 2018-01-29 05:45 UTC
Labels: needs example

**Comment by mgc-oanton** [comment] 2018-06-12 14:28
Hi
I have this problem, and it happens when change data-side-pagination, if is client works (but doesent appear pagination or page-size) and if i put server appears the problem, how could be the json format for that case? Rows groupped by the field?
Thanks
