### ISSUE TITLE
Filter + resetView/resetWidth: problem with width in table header

### ISSUE THREAD

**Issue by shinjiDev** [wenzhixin/bootstrap-table#1335] opened 2015-08-26 15:09 UTC
Hi
I have this case:
https://jsfiddle.net/shinjidev/kt5aj0o9/1/ (please avoid the data)

I need my table header fixed in the top.
The problem when I try the filter is that just one case does not work properly ("Impresos" in the combobox)

I'm not sure why do I have the problem just in one filter case.
I've tried the refresh with resetView and resetWidth without success.

**Comment by wenzhixin** [comment] 2015-09-01 04:39
Please use `load` method instead: https://jsfiddle.net/wenyi/kt5aj0o9/4/

**Comment by shinjiDev** [comment] 2015-09-01 13:24
Thank you @wenzhixin :)

**Comment by shinjiDev** [comment] 2015-09-02 14:08
Dear @wenzhixin 
I'm not very sure but, Don't you think the problem is the method "fitHeader"? Does It consider the hidden rows?

**Comment by wenzhixin** [comment] 2016-07-13 23:28
Can you help to verify whether the problem still exists using the latest version, thank you.

**Comment by djhvscf** [comment] 2017-05-10 17:24
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **PR**. Thanks!

**Closed by djhvscf** 2017-05-10 17:24 UTC
Labels: awaiting reply, help wanted
