### ISSUE TITLE
Compatibility of bootstrap table on IOS，The table width generated in iPhone 6 12.4.2 does not adapt to the screen

### ISSUE THREAD

**Issue by libolong2** [wenzhixin/bootstrap-table#5370] opened 2020-10-09 02:19 UTC
在iphone 6 12.4.2版本中通过js生成的表格无法自适应宽度，表格的宽度会自动因为内容撑开，超出屏幕范围，进而影响整体样式

**Comment by ShreeKrishna1590** [comment] 2021-09-01 03:42
In iPhone 6 12.4.2 version, the table generated by js cannot adapt to the width. The width of the table will automatically be expanded due to the content and exceed the screen area, which will affect the overall style.

**Translation of issue no. 5370 (https://github.com/wenzhixin/bootstrap-table/issues/5370)**

**Comment by UtechtDustin** [comment] 2022-07-30 21:52
I close this issue because it's almost 1 year old and iphone 6 is EOL.
Also i can't reproduce this issue while using the newest Versions of iOS.

**Closed by UtechtDustin** 2022-07-30 21:52 UTC
Labels: browser dependent
