### ISSUE TITLE
Custom View issue on data-show-custom-view

### ISSUE THREAD

**Issue by dharen008** [wenzhixin/bootstrap-table#6286] opened 2022-07-25 18:06 UTC
### Bootstraptable version(s) affected

1.20.2

### Description

On your documentation

This attribute is for what you want to show first on the first load of the browser?

showCustomView
Attribute: data-show-custom-view
Type: Boolean
Detail:
Set to true to show the custom view as default view.
Default: false

but when i change the true into false. all the custom view extension will disappear even the button even data-show-custom-view-button is set to true.

Please look at my sample using your own code

my goal here is to show the table first on first load.
is this a bug or there is another way to do it?

### Example(s)

https://live.bootstrap-table.com/code/dharen008/12184

**Comment by UtechtDustin** [comment] 2022-07-25 18:52
Thanks for the report @dharen008.
It seems the parameter are buggy right know, because of a feature which was implemented some time ago.
We rewrote the button handling, which means all buttons have the same syntax.
In that case it means the internal attribute to show/hide the button will be `data-show-custom-view`, as the extension was written the attribute was `data-show-custom-view-button` which has `-button` at the end.

So the new show/hide attribute  `data-show-custom-view` will collide now with the old attribute `data-show-custom-view` which was designed to toggle the default view.

**Comment by UtechtDustin** [comment] 2022-07-25 19:01
Issue will be fixed in #6287.
This [example](https://live.bootstrap-table.com/code/UtechtDustin/12186) is the solution to your issue as soon the PR is merged and a new version was released.

**Comment by dharen008** [comment] 2022-07-25 20:15
ok thank you. so i just need to wait for them to approve the fix?

**Comment by UtechtDustin** [comment] 2022-07-25 20:16
Yes, you have to wait for the next version.

**Comment by dharen008** [comment] 2022-07-25 20:19
ok thank you very much!

**Closed** 2022-08-02 22:19 UTC
Labels: confirmed, has PR, Bug, custom-view

**Comment by dharen008** [comment] 2022-08-05 18:04
when is the next release? it is still on 1.20.2

**Comment by wenzhixin** [comment] 2022-08-06 01:57
will release a new version soon.
