### ISSUE TITLE
Filter-control: nested property not fills select control

### ISSUE THREAD

**Issue by aescobarsamcla** [wenzhixin/bootstrap-table#4126] opened 2019-01-21 08:55 UTC
Hello,
1- I have data with nested properties:
var sample_of_data = [
  {
    "tier": {
      "nom_complet": " full name"
    }
  }
];
2-I use filter-control extension.
3-I use data-filter-control 'select' control on 'nom_complet' column.

Issue: The 'select' control is not filled with 'nom_complet' values.

Tests I've done but not works:
1- <th data-field="tier.nom_complet" data-filter-data="json:{tier:nom_complet}" data-sortable="true" data-filter-control="select">
2- Table with and without data-flat="true" (previously loading bootstrap-table-flatJSON.min.js)
3- Some more but I do not remember

JSFiddle:
I have taken advantage of old https://github.com/wenzhixin/bootstrap-table/issues/3302 issue jsfiddle but getting resources from cdns repository.

[jsfiddle]() - http://jsfiddle.net/v6tyd3mb/

Can you help me please?

Thank you in advance.

**Comment by UtechtDustin** [comment] 2019-06-09 01:55
Duplicate of #4375, got fixed in our develop branch, on the next update its finally fixed for everybody.

**Closed by UtechtDustin** 2019-06-09 01:55 UTC
Labels: filter-control
