### ISSUE TITLE
Boolean Variables Were Not Sorted Properly in the case of multiple sort.

### ISSUE THREAD

**Issue by rvats** [wenzhixin/bootstrap-table#2877] opened 2017-01-27 16:49 UTC
Boolean Variables Were Not Sorted Properly in the case of multiple sort.
Change to fix the bug have been already proposed.

**Comment by djhvscf** [comment] 2017-02-02 20:57
I have not seen your **PR**.

Can you provide an example? @rvats

**Comment by wenzhixin** [comment] 2017-02-22 00:28
Any update?

**Comment by djhvscf** [comment] 2018-01-29 05:52
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR** with an [example](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports). Thanks!

**Closed by djhvscf** 2018-01-29 05:52 UTC
Labels: awaiting reply, needs example
