### ISSUE TITLE
The click-edit-row plugin is so bad... I changed him... It feels good to use a little

### ISSUE THREAD

**Issue by konralfa** [wenzhixin/bootstrap-table#3265] opened 2017-07-14 07:16 UTC
[bootstrap-table.rowedit.js.zip](https://github.com/wenzhixin/bootstrap-table/files/1147579/bootstrap-table.rowedit.js.zip)
I'm not familiar with the front end..so doesn't write very succinctly, but it works well...
enabled is the addition of data-row-edit= "true" in table and add data-editable= edit type to th's cell

the above is the same, the following is the different settings

I added a bunch of settings in optiosns

settings
```  
 rowEditOption:{
    		  Template:{
    	    	  input:'<input data-field="{{field}}" type="text" class="form-control input-sm"/><span class="input-group-btn"><button class="btn btn-default input-sm clear" type="button"><i class="fa fa-times"></i></button></span>',
    	          select:'<select data-field="{{field}}"  class="form-control input-sm"></select>',
    	      	  checkbox:'<label><input type="checkbox" data-field="{{field}}" value=""/></label>',
    	      	 radio:'<label for="{{index}}"><input type="radio" name="{{field}}" id="{{index}}" value=""/></label>',
    	      	  textarea:'<textarea  data-field="{{field}}"  class="form-control input-sm"></textarea><span class="clear"><i class="fa fa-times-circle-o" aria-hidden="true"></i></span>',
    	      	 submitBtn : '<button type="button" class="btn btn-primary btn-xs editable-submit"><i class="glyphicon glyphicon-ok"></i></button>',
    	    	  cancelBtn :'<button type="button" class="btn btn-default btn-xs editable-cancel"><i class="glyphicon glyphicon-remove"></i></button>',
    	    	  editabletoolsbar:'<div id="editable-toolsbar" class="editable-buttons"/>',
    	    	 inputbar:'<div class="editable-input "></div>'
    	      },
    	  upDataEvent:rowEditUpDataEvent,//You can overwrite this event and submit data to the server
    	  selectData:{},//add here when you need to bind a data
    	  DataEvent:{ //data formatting,can extend the type wen you need....
    		  'input':defaultreplace,
    		  'select':defaultreplace,
    		  'textarea':defaultreplace,
    		  'radio':defaultreplace,
    		  'checkbox':defaultreplace    		  
    	  }
      }
```

-------------------------------------
demo:
html
``` 
<table id="grid" class="table table-hover table-striped"   data-row-edit="true"  >
                            <thead>
                                <tr>
                                    <th   data-field="id" >ID</th>
                                    <th data-field="name"  data-editable="input" data-align="center" >name</th>
                                      <th data-field="readname2" data-editable="select" data-editbind="rm" >test1</th>
                                   <th data-field="link">action</th>
                                </tr>
                            </thead>
                            <tbody>                               
                            </tbody>
                        </table>
```
js
```
$(function()
            {
         var options=$.extend(true,{},$.fn.bootstrapTable.defaults,{          
                    url: "ooxx" ,       
                    rowEditOption:{
                    	 selectData:{"rm":{"aaaaa":"1","bcccc":"Gestern2","ccccc":"Geswtern2","dccc":"wGestern2","ecccc":"Gestewrn2"}},
                    }    
                });
          $("#grid").bootstrapTable(options);
```

**Comment by djhvscf** [comment] 2017-12-19 07:30
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by djhvscf** [comment] 2017-12-29 01:09
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR**. Thanks!

**Closed by djhvscf** 2017-12-29 01:09 UTC
Labels: awaiting reply, click-edit-row, needs example
