### ISSUE TITLE
fixed headers not working with fixed heigth #4166

### ISSUE THREAD

**Issue by sgalcheung** [wenzhixin/bootstrap-table#4768] opened 2019-12-27 07:59 UTC
Do you mean: https://examples.bootstrap-table.com/#extensions/sticky-header.html extension?

_Originally posted by @wenzhixin in https://github.com/wenzhixin/bootstrap-table/issues/4166#issuecomment-463580139_

I ran into the same problem, adding data-height, the head of the table does not match

My [Live Code](https://live.bootstrap-table.com/code/sgal008/1483)
Here are the local effects
![image](https://user-images.githubusercontent.com/42566429/71508286-31a6c180-28c2-11ea-8d72-3e57e56f98b2.png)
Problems with my project
![image](https://user-images.githubusercontent.com/42566429/71508633-69623900-28c3-11ea-9794-87a0887ba33d.png)

**Comment by UtechtDustin** [comment] 2020-02-02 14:49
@sgalcheung 
I dont understand the issue, could you please explain it (if you still have the issue) ?
I also dont see a issue with the example.

**Comment by UtechtDustin** [comment] 2020-02-09 18:05
I close this issue because we got no response from you within the last 7 days, if you still need help please anwer my questions above and we will reopen the issue.

**Comment by sgalcheung** [comment] 2020-02-11 05:57
After I added the width attribute, the table list header and content are offset

**Comment by wenzhixin** [comment] 2020-02-11 06:11
I don't understand the issue.

@sgalcheung 具体是什么问题呢，不太懂哦。

**Comment by sgalcheung** [comment] 2020-02-12 01:09
Live Code是正常的，不会出现错位现象，我本地使用相同代码，却出现了错位现象，无表格等现象，我们项目中同样出现了这个问题

**Comment by wenzhixin** [comment] 2020-02-12 01:28
没有环境不好找原因，昨天发布了 1.16.0 ，你可以试试最新版本

**Comment by UtechtDustin** [comment] 2020-02-22 08:46
I close this issue because i cant reproduce the issue in the newest version (1.16.0) of the bootstrap-table. If this issue still exists please provide us an example and tell us your browser (version).

**Closed by UtechtDustin** 2020-02-22 08:46 UTC
Labels: awaiting reply
