### ISSUE TITLE
cookie extension and multiple server requests

### ISSUE THREAD

**Issue by dfmaxwell** [wenzhixin/bootstrap-table#2390] opened 2016-06-16 13:30 UTC
I'm using the cookie extension and am convinced that for each cookie that gets saved for my table on the initial load or refresh of the page it makes a server request for the data and another one for each cookie, or sometimes an additional one.  If I delete the cookies and reload the page I have 1 request sent to the server.

For instance I have these two cookies:
housingTable.bs.table.filterControl
housingTable.bs.table.pageNumber

And the console shows:
<domain/path>/regmgmt_housingdata.php?order=asc&limit=25&offset=0
<domain/path>/regmgmt_housingdata.php?search=&order=asc&limit=25&offset=0
<domain/path>/regmgmt_housingdata.php?search=&order=asc&limit=25&offset=0
<domain/path>/regmgmt_housingdata.php?search=&order=asc&limit=25&offset=0

So, is there any reason that the cookies would cause this to happen?

**Comment by wenzhixin** [comment] 2016-06-16 13:49
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by dfmaxwell** [comment] 2016-06-16 14:57
I don't think I can show a jsFiddle.  I've tried to put one together but I
can't replicate my internal environment or allow direct access to some of
our data.  Do you have any troubleshooting ideas that I could use to
perhaps efficiently step through the code and maybe catch where that would
be?

**Comment by dfmaxwell** [comment] 2016-06-16 15:03
I am now thinking that this is related to the filter control extension and
cookies.  I just tested with one cookie set by advancing to the next page
and refresh and it acted like I expected, one request.  I then set a filter
and refreshed and have 2 cookies now and 3 requests to the server on
refresh.

**Comment by dfmaxwell** [comment] 2016-06-16 15:20
I've commented out lines 195 to 219 in bootstrap-table-cookie.js which is
the setTimeout where it deals with filterControl.  I've added a line
console.log( 'here' and see that the .on('post-body.bs.table' appears to be
firing twice, so I'm exploring that for the moment.

**Comment by dfmaxwell** [comment] 2016-06-16 16:04
I *might* have a jsFiddle working to demonstrate the issue that I'm having
http://jsfiddle.net/e3nk137y/7118/

I put "boot" in the first column filter
I put "2" in the second column filter

and the console in Firefox shows multiple attempts to get data

**Comment by dfmaxwell** [comment] 2016-06-17 20:41
I think that this attribute data-side-pagination="server" plays into things too.

**Comment by waspinator** [comment] 2016-06-24 20:33
sounds similar to my issue

https://github.com/wenzhixin/bootstrap-table/issues/2370

**Comment by dfmaxwell** [comment] 2016-06-24 21:27
Yes @waspinator I think it is.  It is driving me nuts because I can see it actively interfering with loading the data.

**Comment by anujism** [comment] 2016-07-01 10:24
I am also having the same issue. #2417

**Comment by anujism** [comment] 2016-07-01 12:39
@dfmaxwell For now, you can use code from develop branch. The issue is fixed there.

**Comment by dfmaxwell** [comment] 2016-07-01 13:07
Thanks!

**Comment by wenzhixin** [comment] 2016-07-03 08:13
close this issue

**Closed by wenzhixin** 2016-07-03 08:13 UTC
Labels: cookie, needs example

**Comment by billbo99** [comment] 2017-08-04 00:29
The code still causes the back end server to be called multiple times in the below conditions when server side pagination is enabled.

## Scenario 1 : When you enable **searchOnEnterKey**.  

With this enabled there are two event watchers listening for keycode 13 being pressed. 

The first is used to change the sort direction of the current column from the base javascript library  **bootstrap-table.js**.  The onSort method causes the **serverInit** method to be called.  

```
         this.$header.children().children().off('keypress').on('keypress', function (event) {
             if (that.options.sortable && $(this).data().sortable) {
                 var code = event.keyCode || event.which;
                 if (code == 13) { //Enter keycode
                     that.onSort(event);
                 }
             }
         });
```
The second event watcher is the one in **bootstrap-table-filter-control.js** when its listening for keyup on input boxes and watching for keycode 13 (due to searchOnEnterKey).  This causes the **serverInit** method to be called a 2nd time.


## Scenario 2 : The "keyup input" event watcher appears to be triggered twice.

When I looked at the events being triggered though this watcher,  I saw two separate event sources causing the setTimeout function to be armed

- delegateTarget: div.fixed-table-header
- delegateTarget: thead

My hack to get around that race condition was to only allow the event from the DIV to trigger the timeout for onColumSearch. 
```
            header.off('keyup', 'input').on('keyup', 'input', function (event) {
                if (event.delegateTarget.nodeName === 'DIV') {
                    if (that.options.searchOnEnterKey && event.keyCode !== 13) {
                        return;
                    }

                    if ($.inArray(event.keyCode, [37, 38, 39, 40]) > -1) {
                        return;
                    }

                    clearTimeout(timeoutId);
                    timeoutId = setTimeout(function () {
                        that.onColumnSearch(event);
                    }, that.options.searchTimeOut);

                }
            });

```

I hope my explanation make sense.
