### ISSUE TITLE
when my table first load data total is 0, I will can't reseive my data then

### ISSUE THREAD

**Issue by smile-night** [wenzhixin/bootstrap-table#2862] opened 2017-01-12 09:29 UTC
problem:
  If I do not request data for the first time, then I bootstrapTable implementation of the method will no longer send data

resolve way:
Change the 1313 line "if (this.options.totalRows) " of the JS file to “if(this.options.totalRows!==null &&this.options.totalRows !== undefined)”

**Comment by wenzhixin** [comment] 2017-02-22 00:33
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by djhvscf** [comment] 2017-06-19 06:22
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR**. Thanks!

**Closed by djhvscf** 2017-06-19 06:22 UTC
Labels: needs example
