### ISSUE TITLE
server side pagination corrupts filter control plugin

### ISSUE THREAD

**Issue by martinbarilik** [wenzhixin/bootstrap-table#5955] opened 2021-11-19 12:43 UTC
### Bootstraptable version(s) affected

1.19.1

### Description

"Server" sidePagination corrupts filterControl plugin.  If you set filter to $0, result is OK, but filter is reset and the only way you remove filter is to reload page.

"Client" sidePagination is working OK.

### Example(s)

https://live.bootstrap-table.com/code/martinbarilik/9660

### Additional Context

Also with this combination of plugins and settings, pagination selectbox with amount of rows is disabled ( only "10" is shown ) but i can't seem to simulate it here.

**Comment by UtechtDustin** [comment] 2021-11-19 12:49
Thank you for the bug report, it seems this is a duplicate of #5828.

**Closed by UtechtDustin** 2021-11-19 12:49 UTC
Labels: Bug

**Comment by martinbarilik** [comment] 2021-11-19 12:53
Sorry, it didn't seem to be a problem until I updated to 1.19, that's why i haven't spotted the duplicate. I was searching in latest bugs.

**Comment by UtechtDustin** [comment] 2021-11-19 13:05
No problem :-)
