### ISSUE TITLE
Data readin - "Cannot read property 'length' of undefined" in jquery.min.js

### ISSUE THREAD

**Issue by albertnghiuleong** [wenzhixin/bootstrap-table#3164] opened 2017-05-28 04:43 UTC
Dear wenzhixin,

I am a new user of js and html. I have downloaded the source codes of bootstrap-table from your website. ("bootstrap-table-examples-master", "bootstrap-table-master", "multiple-select-master"). However, as shown in the welcome.html, there is missing datas from the specified link "/examples/bootstrap_table/data". I guess I could use the data in the "json" folder. So I changed the link of data-url as linking one of the json file (/json/Testing.json) 

Then I tried to run the welcome.html on wamp from localhost. It fails to load the data as the below error pops out:
Uncaught TypeError: Cannot read property 'length' of undefined
    at Function.each (jquery.min.js:2)
    at Object.responseHandler (VM59 welcome.html:165)
    at calculateObjectValue (VM60 bootstrap-table.js:130)
    at Object.success (VM60 bootstrap-table.js:2032)
    at j (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at x (jquery.min.js:4)
    at XMLHttpRequest.b (jquery.min.js:4)

It seems like that the res.rows in welcome.html is not defined but I could see the object "res" stores the values of the data. 

So, I am wondering if the error comes because of the data format (json file).

Thank you for your kind attention. I am looking forward to your reply!

**Comment by djhvscf** [comment] 2017-06-13 07:42
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by djhvscf** [comment] 2017-06-19 06:16
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR**. Thanks!

**Closed by djhvscf** 2017-06-19 06:16 UTC
Labels: needs example

**Comment by Jingkun-Hu** [comment] 2017-11-28 08:17
Because there is no data, it shows "read property 'length' of undefined". go ResponseHandler function to check the parameter res.rows value, if undefined but res has value in JSON format, just add     var res = $.parseJSON(res) to make it work
