### ISSUE TITLE
Non-jQuery initialisation

### ISSUE THREAD

**Issue by marceloverdijk** [wenzhixin/bootstrap-table#6717] opened 2023-03-31 13:26 UTC
### Description

I understand BT needs jQuery internally, and this idea is not about removing jQuery all together, but for the users to have an option to initialise BT without jQuery.

Similar as https://datatables.net/examples/non_jquery/init.html

```
document.addEventListener('DOMContentLoaded', function () {
    let table = new DataTable('#example');
});
```

**Comment by marceloverdijk** [comment] 2023-04-06 12:45
So it would be great to do something like:

```
  document.addEventListener('DOMContentLoaded', function() {
    new BootstrapTable('#table', { ... })
  })
```

I understand the current `BootstrapTable` class does not parse config options (e.g. `data-search="true"` so just constructing `BootstrapTable` won't be sufficient.

**Comment by marceloverdijk** [comment] 2023-04-14 21:17
@wenzhixin I would love to be able to remove direct usage of jquery from my code (I do understand BT needs jquery). 
Are you interested in this for the upcoming release, as I could take a go to implement this?

PS: What I see in current code (constructor of `class BootstrapTable`) that it does not auto `init()`.
And a way from ordinary `document.getElementById('table')` to get hold on the `BootstrapTable` and to be able to call e.g. refresh options.

**Comment by UtechtDustin** [comment] 2023-06-08 15:17
Duplicate of #4796   
We also want to remove jQuery (this issue is a part of that), but other issues have a higher priority.   
Pull requests are welcome :)

**Closed by UtechtDustin** 2023-06-08 15:17 UTC
Labels: feature
