### ISSUE TITLE
Json Limits

### ISSUE THREAD

**Issue by maxx1985** [wenzhixin/bootstrap-table#605] opened 2015-03-10 14:39 UTC
Hi, i've a dataset about 5000 records
i want all the records in the table (the performances actually aren't a problem)

when the base query has a limit under 2292 the table display correctly the results
when i go over that numer i got ''no result found''

I've tryed to reduce the size of the json, but it seems only dependent of the number of rows. 
What can i do?

**Comment by djhvscf** [comment] 2015-03-10 18:50
Just to be sure about your problem.. If you show more than 2292 row in your table you have the message "No result found" ?? @maxx1985

**Comment by maxx1985** [comment] 2015-03-10 19:05
yes

**Comment by djhvscf** [comment] 2015-03-10 19:26
ok, now can you share us your table configuration? @maxx1985

**Comment by maxx1985** [comment] 2015-03-10 20:00
<table data-toggle="table" data-url="jsonparser.php"    data-query-params="queryParams"     data-pagination="true"   data-page-size="100"    data-search="true"    data-height="600">
    <thead>
    <tr>
        <th data-field="name"  data-sortable="true">Nome</th>
        <th data-field="edit">edit</th>
        <th data-field="delete">delete</th>
     </tr>
    </thead>
</table>
<script>function queryParams() {
    return {
        type: 'owner',
        sort: 'name',
        direction: 'desc',
        per_page: 100,
        page: 1
    };
}</script>

the JSON answer is
 [
{"name":"<a title='Anfiteatro ' href='?tipoevento&edit_tipoevento=775' style='color:#000;'>Anfiteatro </a>","edit":"edit_link","delete":"delete_link"},
{"name":"<a title='Anfiteatro' href='?tipoevento&edit_tipoevento=3876' style='color:#000;'>Anfiteatro</a>","edit":"edit_link","delete":"delete_link"},
{"name":"<a title='Anfiteatro Adriatico' href='?tipoevento&edit_tipoevento=675' style='color:#000;'>Anfiteatro Adriatico</a>","edit":"edit_link","delete":"delete_link"},
{"name":"<a title='Anfiteatro Artinscena' href='?tipoevento&edit_tipoevento=3956' style='color:#000;'>Anfiteatro Artinscena</a>","edit":"edit_link","delete":"delete_link"},.....]

and yes it doesn't work also with ''plain/No tag'' data

**Comment by maciej-gurban** [comment] 2015-03-12 07:53
Hi. Have you checked whether the resulting JSON array's length matches 5000 records?

**Comment by maxx1985** [comment] 2015-03-12 09:52
sure, the output is ok, when in the sql query i've 'limit 0,2292' it works fine, when i've 'limit 0, 2293' nothing found appears, the json is ok

**Comment by maciej-gurban** [comment] 2015-03-12 10:36
Make sure you're checking the length of the JSON array, not the result of SQL query in whatever language your backend is written in though. I mean `JSON.parse(json).length` specifically.

If the result set is smaller than 5000 elements, it could be that your JSON serializer it limited to X MB of data that it can serialize, and thus the remaining part after 2292th element is simply cut off. If that's the case, you could also stringify your JSON string and check the character count and convert it to KB/MB. This will give you the property called `JavaScriptSerializer.MaxJsonLength`, which depending on your environment may or may not be changeable.

For more information refer to [this SO answer](http://stackoverflow.com/a/10793615/2066118)

**Comment by wenzhixin** [comment] 2015-04-07 15:52
I think the problem is just like @maciej-gurban said. Please check.
Close this issue.

**Closed by wenzhixin** 2015-04-07 15:52 UTC

**Comment by bounlu** [comment] 2016-09-02 02:15
I confirm that this problem occurs and it is not related to corrupted JSON, as the JSON was confirmed to be valid on [JSONlint](http://jsonlint.com/). My limit is instead around 120000 rows, more than that a blank page is displayed on the browser.

**Comment by dlannan** [comment] 2017-07-01 03:54
I believe I have a similar problem when I select "ALL" for pagination.
The table requests the server with a weird GET: 
"GET /dbtable.php?order=asc&offset=0&limit%5B%5D=8020 HTTP/1.1" 200 2326

Normal GET requests look fine:
"GET /dbtable.php?order=asc&offset=0&limit=100 HTTP/1.1" 200 157853

So, it appears something is being "tagged" on to the url construction at certain sizes? Is this the case?
