### ISSUE TITLE
How to export hidden columns

### ISSUE THREAD

**Issue by kamarajgit** [wenzhixin/bootstrap-table#1982] opened 2016-02-09 10:12 UTC
Hi,

I need export to excel,csv format. In this feature i need to export hidden columns also. please help me.

**Comment by dabros** [comment] 2016-02-10 00:55
@kamarajgit - we need a fiddle showing how this doesnt work pls

https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports
http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/export.html

Though this is likely a deliberate design decision if true, so people can just export what they need and nothing else.

If its a big issue to you, id say look at custom toolbar with just one extra button that toggles all columns visible (storing thier previous states to toggle back just those ones if clicked again)

http://bootstrap-table.wenzhixin.net.cn/documentation/#table-options
http://issues.wenzhixin.net.cn/bootstrap-table/index.html#options/custom-toolbar.html

Or just make it clear to them that export is (obviously) exporting only what columns you can see, with it pre-set to `export-all` so all rows are exported.

**Comment by khushirandive65** [comment] 2016-08-04 13:52
I have some problem. I want to export my column that is visible : false. But if i make it false it will not display while export to csv. Please help as soon as possible

**Comment by dabros** [comment] 2016-08-05 01:59
@khushirandive65 - same as my post to @kamarajgit  

We need a fiddle, see above

**Comment by lutol** [comment] 2016-09-22 14:38
I have the same problem and I can't make the hidden column export. I've prepared a [jsFiddle](https://jsfiddle.net/fjykowtL/30/). The table there has two columns named "sign" and "sign2" and both columns have the same value. The column "sign" has data formatter function and shows icon on the screen but of course the icon do not export to excel so I just want to export the values from column "sign2" which is hidden. It would be good to add possibility for a user to export or not hidden columns, but for now how can be this solved?

**Comment by dabros** [comment] 2017-06-13 01:37
@wenzhixin @djhvscf 

Any better idea or built in feature for exporting hidden columns?

**Comment by wenzhixin** [comment] 2018-04-03 01:08
Duplicate of #3475

**Closed by wenzhixin** 2018-04-03 01:08 UTC
Labels: awaiting reply, export

**Comment by cblopez** [comment] 2021-03-18 10:25
I am way too late on this, but for newer versions you do not need to change the code, a column may be declared with `data-force-export="true"` to always get exported:
```
<th data-field="something" data-visible="false" data-force-export="true"></th>   <!-- This gets exported -->
```
