### ISSUE TITLE
Filter by few options

### ISSUE THREAD

**Issue by mkatu** [wenzhixin/bootstrap-table#2454] opened 2016-07-12 17:11 UTC
Hi guys!
How can I filter table by few options?
I need to filter table when click on status' buttons (http://joxi.ru/4AkeDYMHMan5km) and select type (http://joxi.ru/E2pgDw6uBEy8Mm). But when I use filterBy, I rewrite options and filter only by one param.

http://tristanassist.itera-research.com/_tristan/templates/management/users.html

**Comment by djhvscf** [comment] 2016-07-12 19:14
I think you must include in the **filterBy** call both parameters.. In your code when the user click a status button you only send the status selected but type is not sent.

Please try sending both parameters and let us know if it is working or not, in case it is not working as expected provide us a fiddle.

@mkatu

**Comment by djhvscf** [comment] 2017-12-29 08:17
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR**. Thanks!

**Closed by djhvscf** 2017-12-29 08:17 UTC
Labels: awaiting reply, help wanted
