### ISSUE TITLE
Editable and OnClickRow event

### ISSUE THREAD

**Issue by Blue1791** [wenzhixin/bootstrap-table#3529] opened 2018-01-03 21:17 UTC
I am using both editable and the onClickRow event. When I click on a cell to edit it the event takes place (which in this case is to launch a modal).

How can I cancel the onClickRow event when I click on a cell with editable active?

**Comment by wenzhixin** [comment] 2018-01-04 05:27
Duplicate of #3514 
http://jsfiddle.net/wenyi/e3nk137y/18030/

**Closed by wenzhixin** 2018-01-04 05:27 UTC
