### ISSUE TITLE
Change bootstrap5 to bootstrap4?

### ISSUE THREAD

**Issue by SuperBoy17** [wenzhixin/bootstrap-table#6374] opened 2022-09-06 08:02 UTC
![Capture](https://user-images.githubusercontent.com/112933534/188582395-2070fff8-f645-4b34-8374-c762b2f20b9e.JPG)
### Description

Hi there, I got issue on dropdown which cannot work plus with css problem, I tried put down url link able to change to bootstrap 4 but download and put inside project...won't work, is there a way no need change bootstrap folder to 5 but downgrade it only table?

FYI, 1.19.1 and below can work

**Comment by SuperBoy17** [comment] 2022-09-06 08:03
FYI, only 1.19.1 and below working

**Comment by SuperBoy17** [comment] 2022-09-06 08:05
If can got other way from data-bs-toggle to data-toggle?

**Comment by wenzhixin** [comment] 2022-09-09 02:47
Duplicate of #6380

**Closed by wenzhixin** 2022-09-09 02:47 UTC
Labels: help-wanted
