### ISSUE TITLE
Server pagination - total count from header

### ISSUE THREAD

**Issue by stevespringett** [wenzhixin/bootstrap-table#3064] opened 2017-03-31 19:09 UTC
I'm writing a client for an existing server. The server uses many best practices including not encapsulating multiple objects in a 'rows' object, nor does it include the total number of results in the body.

The server provides a set of results as a simple object array, and always includes the total number of results in the response header (X-Total-Count).

Using a response handler was my first thought, as a way to manipulate the data in a way as to satisfy the expectations of Bootstrap Table. But the response handler doesn't expect XHR. So I have no way to get the total number of results.

What I ended up doing (as a hack), is to modify BootstrapTable.prototype.initServer so that calculateObjectValue looks like this:

```javascript
// Begin modification
success: function (tmpres, status, xhr) {
    tmpres = calculateObjectValue(that.options, that.options.responseHandler, [tmpres], tmpres);
    var res = [];
    res.rows = tmpres;
    res.total = xhr.getResponseHeader("X-Total-Count");
    // End modification
    that.load(res);
```

I couldn't think of another way to do this. I'm not happy with having a custom version of Bootstrap Table so if there's a better way, I'd really appreciate some feedback. If not, then perhaps a future enhancement request. It appears that use of X-Total-Count is a popular way of providing this information.

**Comment by anizephyr** [comment] 2017-03-31 23:50
![](http://i.imgur.com/YuOPLHu.jpg)
use responseHandler

**Comment by djhvscf** [comment] 2017-04-02 06:35
@stevespringett did you try the `responseHandler` as @anizephyr mentioned?

**Comment by djhvscf** [comment] 2017-12-29 08:27
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR**. Thanks!

**Closed by djhvscf** 2017-12-29 08:27 UTC
Labels: awaiting reply, help wanted
