### ISSUE TITLE
change updaterow method

### ISSUE THREAD

**Issue by 7vqinqiwei** [wenzhixin/bootstrap-table#3291] opened 2017-07-27 09:15 UTC
1,only update one line;
2,updaterow method  reder the whole view;(so that I can edit multi line)
so I just change a little bit.
ofcause,bootstrap-table-click-edit-row.js is not well enough!~_~!

BootstrapTable.prototype.refreshRow = function (index) {
    	var table = this;
    	var $tbody = table.$tableBody;
    	if (index == undefined) {
    		return;
    	}
    	var row = table.getData()[index];
    	var $tr = $tbody.find("tbody>tr").eq(index);
    	
    	var that = this,
        html = [],
        data = this.getData();
    	
    	
	    for (var i = this.pageFrom - 1; i < this.pageTo; i++) {
	    	if(i != index)continue;
	    	
	        var key,
	            item = data[i],
	            style = {},
	            csses = [],
	            data_ = '',
	            attributes = {},
	            htmlAttributes = [];
	
	        style = calculateObjectValue(this.options, this.options.rowStyle, [item, i], style);
	
	        if (style && style.css) {
	            for (key in style.css) {
	                csses.push(key + ': ' + style.css[key]);
	            }
	        }
	
	        attributes = calculateObjectValue(this.options,
	            this.options.rowAttributes, [item, i], attributes);
	
	        if (attributes) {
	            for (key in attributes) {
	                htmlAttributes.push(sprintf('%s="%s"', key, escapeHTML(attributes[key])));
	            }
	        }
	
	        if (item._data && !$.isEmptyObject(item._data)) {
	            $.each(item._data, function (k, v) {
	                // ignore data-index
	                if (k === 'index') {
	                    return;
	                }
	                data_ += sprintf(' data-%s="%s"', k, v);
	            });
	        }
	
	        html.push('<tr',
	            sprintf(' %s', htmlAttributes.join(' ')),
	            sprintf(' id="%s"', $.isArray(item) ? undefined : item._id),
	            sprintf(' class="%s"', style.classes || ($.isArray(item) ? undefined : item._class)),
	            sprintf(' data-index="%s"', i),
	            sprintf(' data-uniqueid="%s"', item[this.options.uniqueId]),
	            sprintf('%s', data_),
	            '>'
	        );
	
	        if (this.options.cardView) {
	            html.push(sprintf('<td colspan="%s"><div class="card-views">', this.header.fields.length));
	        }
	
	        if (!this.options.cardView && this.options.detailView) {
	            html.push('<td>',
	                '<a class="detail-icon" href="javascript:">',
	                sprintf('<i class="%s %s"></i>', this.options.iconsPrefix, this.options.icons.detailOpen),
	                '</a>',
	                '</td>');
	        }
	
	        $.each(this.header.fields, function (j, field) {
	            var text = '',
	                value = getItemField(item, field, that.options.escape),
	                type = '',
	                cellStyle = {},
	                id_ = '',
	                class_ = that.header.classes[j],
	                data_ = '',
	                rowspan_ = '',
	                colspan_ = '',
	                title_ = '',
	                column = that.columns[j];
	
	            if (that.fromHtml && typeof value === 'undefined') {
	                return;
	            }
	
	            if (!column.visible) {
	                return;
	            }
	
	            if (that.options.cardView && !column.cardVisible) {
	                return;
	            }
	
	            style = sprintf('style="%s"', csses.concat(that.header.styles[j]).join('; '));
	
	            // handle td's id and class
	            if (item['_' + field + '_id']) {
	                id_ = sprintf(' id="%s"', item['_' + field + '_id']);
	            }
	            if (item['_' + field + '_class']) {
	                class_ = sprintf(' class="%s"', item['_' + field + '_class']);
	            }
	            if (item['_' + field + '_rowspan']) {
	                rowspan_ = sprintf(' rowspan="%s"', item['_' + field + '_rowspan']);
	            }
	            if (item['_' + field + '_colspan']) {
	                colspan_ = sprintf(' colspan="%s"', item['_' + field + '_colspan']);
	            }
	            if (item['_' + field + '_title']) {
	                title_ = sprintf(' title="%s"', item['_' + field + '_title']);
	            }
	            cellStyle = calculateObjectValue(that.header,
	                that.header.cellStyles[j], [value, item, i, field], cellStyle);
	            if (cellStyle.classes) {
	                class_ = sprintf(' class="%s"', cellStyle.classes);
	            }
	            if (cellStyle.css) {
	                var csses_ = [];
	                for (var key in cellStyle.css) {
	                    csses_.push(key + ': ' + cellStyle.css[key]);
	                }
	                style = sprintf('style="%s"', csses_.concat(that.header.styles[j]).join('; '));
	            }
	
	            value = calculateObjectValue(column,
	                that.header.formatters[j], [value, item, i], value);
	
	            if (item['_' + field + '_data'] && !$.isEmptyObject(item['_' + field + '_data'])) {
	                $.each(item['_' + field + '_data'], function (k, v) {
	                    // ignore data-index
	                    if (k === 'index') {
	                        return;
	                    }
	                    data_ += sprintf(' data-%s="%s"', k, v);
	                });
	            }
	
	            if (column.checkbox || column.radio) {
	                type = column.checkbox ? 'checkbox' : type;
	                type = column.radio ? 'radio' : type;
	
	                text = [sprintf(that.options.cardView ?
	                    '<div class="card-view %s">' : '<td class="bs-checkbox %s">', column['class'] || ''),
	                    '<input' +
	                    sprintf(' data-index="%s"', i) +
	                    sprintf(' name="%s"', that.options.selectItemName) +
	                    sprintf(' type="%s"', type) +
	                    sprintf(' value="%s"', item[that.options.idField]) +
	                    sprintf(' checked="%s"', value === true ||
	                    (value && value.checked) ? 'checked' : undefined) +
	                    sprintf(' disabled="%s"', !column.checkboxEnabled ||
	                    (value && value.disabled) ? 'disabled' : undefined) +
	                    ' />',
	                    that.header.formatters[j] && typeof value === 'string' ? value : '',
	                    that.options.cardView ? '</div>' : '</td>'
	                ].join('');
	
	                item[that.header.stateField] = value === true || (value && value.checked);
	            } else {
	                value = typeof value === 'undefined' || value === null ?
	                    that.options.undefinedText : value;
	
	                text = that.options.cardView ? ['<div class="card-view">',
	                    that.options.showHeader ? sprintf('<span class="title" %s>%s</span>', style,
	                        getPropertyFromOther(that.columns, 'field', 'title', field)) : '',
	                    sprintf('<span class="value">%s</span>', value),
	                    '</div>'
	                ].join('') : [sprintf('<td%s %s %s %s %s %s %s>',
	                    id_, class_, style, data_, rowspan_, colspan_, title_),
	                    value,
	                    '</td>'
	                ].join('');
	
	                // Hide empty data on Card view when smartDisplay is set to true.
	                if (that.options.cardView && that.options.smartDisplay && value === '') {
	                    // Should set a placeholder for event binding correct fieldIndex
	                    text = '<div class="card-view"></div>';
	                }
	            }
	
	            html.push(text);
	        });
	
	        if (this.options.cardView) {
	            html.push('</div></td>');
	        }
	
	        html.push('</tr>');
	    }
	
	    // show no records
	    if (!html.length) {
	        html.push('<tr class="no-records-found">',
	            sprintf('<td colspan="%s">%s</td>',
	                this.$header.find('th').length, this.options.formatNoMatches()),
	            '</tr>');
	    }
	    
	    $tr.replaceWith($(html.join('')));

**Comment by djhvscf** [comment] 2017-12-19 06:58
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) , thanks!

**Comment by wenzhixin** [comment] 2017-12-24 15:09
Sorry I don't know what problem. 
PR is welcome.

**Comment by djhvscf** [comment] 2017-12-29 01:07
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR**. Thanks!

**Closed by djhvscf** 2017-12-29 01:07 UTC
Labels: awaiting reply, needs example
