### ISSUE TITLE
How to load data without names of fields

### ISSUE THREAD

**Issue by joefreire** [wenzhixin/bootstrap-table#3110] opened 2017-04-26 20:28 UTC
I have a table that dynamically generates via PHP + MYSQL the names of the rows and columns are dynamic and I was wondering if you have how to use this data in the bootstrap-table

**Comment by wenzhixin** [comment] 2017-04-27 23:58
What is your data format? Please provide an example.

**Comment by djhvscf** [comment] 2017-12-29 01:16
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR**. Thanks!

**Closed by djhvscf** 2017-12-29 01:16 UTC
Labels: awaiting reply
