### ISSUE TITLE
[1.15.2] bootstrap-table.min.js - IE11

### ISSUE THREAD

**Issue by Se7enShawn** [wenzhixin/bootstrap-table#4485] opened 2019-07-09 14:37 UTC
Hi, 
the min version of bootstrap-table.min.js does not work on IE11 and on the Eclipse internal browser, the developer version, bootstrap-table.js, works fine.
There's a script error: SCRIPT5007

Example page: https://examples.bootstrap-table.com/#welcomes/from-data.html

**Comment by UtechtDustin** [comment] 2019-07-09 15:12
Already fixed in our develop Branch, please wait for the newest version.
Duplicate of #4459

**Closed by UtechtDustin** 2019-07-09 15:12 UTC

**Comment by wenzhixin** [comment] 2019-07-11 01:16
1.15.3 released
