### ISSUE TITLE
showMultiSortButton option not working 

### ISSUE THREAD

**Issue by david-ieong** [wenzhixin/bootstrap-table#5343] opened 2020-09-25 09:53 UTC
**Bootstraptable version(s) affected**: 1.18.0

**Description**  
I'm using a lot of table in my app.
I put the multi-sort extension for all the app.
I pass from 1.15.5 to 1.18.0
Now the multisort button showing for every table even if the showMultiSort is false.

When putting showMultiSortButton : false, button still showing

**Example**  
https://live.bootstrap-table.com/code/david-ieong/4924

**Possible  (optional)**  

**Additional context**

**Comment by UtechtDustin** [comment] 2020-09-25 09:58
Duplicate of #5327, fixed in #5329

**Closed by UtechtDustin** 2020-09-25 09:58 UTC
Labels: Bug

**Comment by david-ieong** [comment] 2020-09-25 10:17
Thx didn't saw the previous issue :)
