### ISSUE TITLE
How to get Input Value from data-formatter?

### ISSUE THREAD

**Issue by newcomer123** [wenzhixin/bootstrap-table#3111] opened 2017-04-27 09:16 UTC
I have a "table",  one of the "<th>" is an <input>, which was generated by data-formatter。  Below are  some codes:

  <table id="table" data-toggle="table" 
	   data-url="/WindowList"
	   data-pagination="true" 
            ...........
                            <thead>
                             <tr>
                            <th data-field="evaTime"></th> 
                            <th data-field="evaDistrict"></th> 
                            <th data-formatter="NoteFormatter"  data-events="inputEvents"   data-field="Note"  > </th> 
                            <th data-formatter="UploadFormatter"   data-field="upload" data-events="UploadEvents" ></th> 
                          .........................................

Here are the defination of data-formatter:

function NoteFormatter(value, row, index) {
        return ' <input type="text" class="note" id="note" style="width:100px" name="Note"/> ';
} 

function UploadFormatter(value, row, index) {
    return ' <input type="file" style="width:100px"  id="upload"  th:name="Upload"  th:value="上传"/>';
} 

I tried to get  "note" and "upload"  input value in following "refresh" code. But neither of  $("#note").val(),
or $('#upload').val() has value.    Can anyone help me on this?  Many thanks!

$table.bootstrapTable('refresh',{url:'/DrySourceReport',
        	                         query:{
                           		  SectionCode: row.sectionCode,
                                  Note: $("#note").val(),
                                  DaBiao: row.daBiao,
                                  Upload: $('#upload').val()
                                  }

**Comment by wenzhixin** [comment] 2017-04-27 23:56
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by djhvscf** [comment] 2017-12-29 01:16
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR**. Thanks!

**Closed by djhvscf** 2017-12-29 01:16 UTC
Labels: awaiting reply
