### ISSUE TITLE
When append a new row in subtable, it will be executed 2 times. Pls. fix this bug.

### ISSUE THREAD

**Issue by katrina-engelbrecht** [wenzhixin/bootstrap-table#2335] opened 2016-06-01 12:10 UTC
Hi, 
here is my fiddle: http://jsfiddle.net/Wei_Engelbrecht/e3nk137y/6813/
how to make the bug appear:
1. expand one row. in the column "Item Operate" the "Plus" icon appears
2. click on this "Plus" icon, then in the subtable, it will be insert 2 rows. But in the codes I only write one time to append a new row.
3. an error alert pops up to remind you.
Pls. fix this bug.  Thanks a lot!

Best Regards,
Katrina

**Comment by wenzhixin** [comment] 2016-06-02 06:11
@katrina-engelbrecht , I think this is not a bug. In your case you define the `operateFormatter` like:
```
'<a class="add m110" href="javascript:void(0)" title="neue Unterkategorie" style="float:left;display:none;" >',
                '<i class="glyphicon glyphicon-plus add" ></i>',
            '</a>'
```
There are two `add` class: `a class="add..` and `<i class="... add"`, here is the reason cause 
> be insert 2 rows

Let's use `'<i class="glyphicon glyphicon-plus" ></i>'` instead: http://jsfiddle.net/wenyi/e3nk137y/6821/

**Comment by katrina-engelbrecht** [comment] 2016-06-02 07:12
Thank you wenzhixin, you are so great!!!

**Comment by wenzhixin** [comment] 2016-06-02 07:17
You are welcome, let's close this issue.

**Closed by wenzhixin** 2016-06-02 07:17 UTC
Labels: invalid, js
