### ISSUE TITLE
Header colspan and the table cannot show in card view layout

### ISSUE THREAD

**Issue by LostIndie** [wenzhixin/bootstrap-table#2973] opened 2017-03-06 01:32 UTC
Hi,

I have a table with header column being merged. When resize browser, the table not show in card view layout. How to make the table show in card view layout with the header columns being merged?

**Comment by djhvscf** [comment] 2017-03-06 17:18
@LostIndie please share us an example

**Comment by djhvscf** [comment] 2018-01-29 05:50
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR** with an [example](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports). Thanks!

**Closed by djhvscf** 2018-01-29 05:50 UTC
Labels: needs example
