### ISSUE TITLE
Help ExpandRow and  CollapseRow

### ISSUE THREAD

**Issue by binhoscray** [wenzhixin/bootstrap-table#2420] opened 2016-06-30 19:39 UTC
In metedo expandRow / CollapseRow as I can close an already open line by clicking on another. end result always always leave a Row Visible. In the example that you have, I'm opening and having to close all previous.

**Comment by dabros** [comment] 2016-07-01 04:20
@binhoscray 


If you have code that functions different from official example then please create a [fiddle ](https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports)(examples and guide provided) showing this, included your bootstrap-table.js copy+pasted inside js panel if thats whats needed to show this 

Also please always include links to examples and ect your referring to, there are many that use expand functionality and you only delay the process if everyone looking at this has to individually chase down what they 'think' your referring to

http://issues.wenzhixin.net.cn/bootstrap-table/index.html
http://issues.wenzhixin.net.cn/bootstrap-table/index.html#options/boolean-options.html
http://issues.wenzhixin.net.cn/bootstrap-table/index.html#options/sub-table.html
http://issues.wenzhixin.net.cn/bootstrap-table/index.html#options/detail-view.html
http://issues.wenzhixin.net.cn/bootstrap-table/index.html#methods/expandRow-collapseRow.html

**Comment by djhvscf** [comment] 2017-12-29 08:18
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR**. Thanks!

**Closed by djhvscf** 2017-12-29 08:18 UTC
Labels: awaiting reply, help wanted
