### ISSUE TITLE
Filter Control doesn't work with data formatter

### ISSUE THREAD

**Issue by vhk2018** [wenzhixin/bootstrap-table#3636] opened 2018-03-02 03:36 UTC
When theres is data-formatter, filter result is none when typing 's' in the name column.
https://jsfiddle.net/tmLzkt43/38/

while when removing the data-formatter, filter control will work again.
https://jsfiddle.net/tmLzkt43/36/

Anyone knows what the problem is? Thank you!

**Comment by duncanturk** [comment] 2018-03-08 16:13
This issue may only be related to formatters producing html-output.

**Comment by UtechtDustin** [comment] 2019-06-08 23:57
duplicate of #2655

**Closed by UtechtDustin** 2019-06-08 23:57 UTC
Labels: filter-control
