### ISSUE TITLE
Group-By-v2 collapse 

### ISSUE THREAD

**Issue by VisualSanity** [wenzhixin/bootstrap-table#3773] opened 2018-05-04 10:58 UTC
Group-By-v2 collapse issue

If the result set is greater than the initial number of records in the display (pagination), when you collapse the group  by column, it does not pull the remaining records up into the view. Those records are hidden under the subsequent pages.

[jsfiddle](http://jsfiddle.net/jscripting/k3k5Lyzf/) 

In the fiddle, you can see it doesn't pull in "blog-text" from page two, when "blog" is collapsed. Is this by design?

P.S. I'm not sure if this is the right area to post extension issues.

**Comment by UtechtDustin** [comment] 2019-04-22 03:45
I close this issue because its already very old, also i think this is not a bug.
The group-by extension will help you to organize the table and help you to get a better overview, not to paginate it (for that is the pagination there). If you thin this is a bug please reopen it and explain it more.

**Closed by UtechtDustin** 2019-04-22 03:45 UTC
Labels: group-by
