### ISSUE TITLE
table tools not working in Laravel

### ISSUE THREAD

**Issue by 2000calories** [wenzhixin/bootstrap-table#3309] opened 2017-08-12 04:26 UTC
Only "data-search" is functional. Other table tools like toggle,show-columns and advanced-search are not working in [laravel.]([url](url))

Windows 7  x64
Google Chrome 60
XAMPP V3.2.2
Laravel 5.4

**Comment by 2000calories** [comment] 2017-08-12 04:30
![errors](https://user-images.githubusercontent.com/25191098/29237850-cca6750a-7f59-11e7-97c6-b220cecd418b.PNG)

**Comment by 2000calories** [comment] 2017-08-12 04:31
![capture](https://user-images.githubusercontent.com/25191098/29237860-19745c80-7f5a-11e7-9323-0e8ffae3fd07.PNG)

**Comment by wenzhixin** [comment] 2017-12-17 06:03
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by djhvscf** [comment] 2017-12-29 01:05
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR**. Thanks!

**Closed by djhvscf** 2017-12-29 01:05 UTC
Labels: awaiting reply, needs example
