### ISSUE TITLE
markup bootstrap broken

### ISSUE THREAD

**Issue by ko22009** [wenzhixin/bootstrap-table#5651] opened 2021-03-23 20:43 UTC
version: 1.18.2

![image](https://user-images.githubusercontent.com/11016041/112215322-13a14b80-8c42-11eb-8fa2-21f1c052a112.png)

I fixed by add style css:

.bootstrap-table .fixed-table-container .fixed-table-body .fixed-table-loading {
  display: none;
}

It was because element just set visible: none, but it is not enough. Need remove from document flow.

**Comment by UtechtDustin** [comment] 2021-03-24 16:59
Please provide us an example using our [editor](https://live.bootstrap-table.com/), we have to see an example with your setup.

**Comment by ko22009** [comment] 2021-03-24 19:59
@UtechtDustin, https://live.bootstrap-table.com/code/ko22009/7009

**Comment by UtechtDustin** [comment] 2021-03-24 22:35
Your "fix" don't work proper e.g. the loading text is always hidden.

This is a duplicate of #5439, so i will close this issue.

**Closed by UtechtDustin** 2021-03-24 22:35 UTC
Labels: Bug, needs example
