### ISSUE TITLE
export xlsx whit images possible?

### ISSUE THREAD

**Issue by Immontalis** [wenzhixin/bootstrap-table#3684] opened 2018-03-18 18:19 UTC
Hello,

is there a possibility to export the table in xlsx with images??
can some one help me pls

thanks

**Comment by wenzhixin** [comment] 2018-03-20 16:25
Duplicate of https://github.com/hhurz/tableExport.jquery.plugin/issues/225

**Closed by wenzhixin** 2018-03-20 16:25 UTC
