### ISSUE TITLE
Multiple http request on Refresh if url is changed

### ISSUE THREAD

**Issue by ramons03** [wenzhixin/bootstrap-table#3765] opened 2018-04-27 04:56 UTC
There is an issue when i try to change the url.
If the url is changed before refresh method on refresh options method bootstrap-table requests 2 times the same url.
One of the request is cancelled, the other is ok.
```js
///original url is "/gh/get/response.json/wenzhixin/bootstrap-table/tree/master/docs/data/data1/"
 $('#table').bootstrapTable('refreshOptions',{
    url:"/gh/get/response.json/wenzhixin/bootstrap-table/tree/master/docs/data/data2"
  });
```

Here is a jsfiddle with an example.
Use the select to refresh the table.
https://jsfiddle.net/ramons03/L30kxbmu/3/

To see the requests review the Network tab on chrome developer tools 
Here is a picture of what i want to change.
![image](https://user-images.githubusercontent.com/295830/39348517-d28d7524-49cd-11e8-9a3e-72dbb8793eb6.png)

Is this an expected behavior? Why? How can i change url without the duplication of the request?
Thanks. 
Regards.

**Comment by Falseee** [comment] 2019-04-07 14:17
Cant reproduce your bug, it might that the bug is fixed in the newest version.
If this bug still exists pls reopen this issue.

**Closed by Falseee** 2019-04-07 14:17 UTC
