### ISSUE TITLE
checkbox state (checked/unchecked)

### ISSUE THREAD

**Issue by MajesticGray** [wenzhixin/bootstrap-table#6821] opened 2023-06-08 08:16 UTC
### Description

Hello,
this is my table:

https://live.bootstrap-table.com/code/MajesticGray/15539

The checkbox column is rendered this way (given the user id is 2):
```
<input data-index="0" name="project[users][]" type="checkbox" value="2" checked="checked">
```

Now, that's ok but I want only some checkboxes to be checked on page load, so I took a look at the docs:
https://bootstrap-table.com/docs/api/column-options/#checkbox

and it says that:

> If a value is given, the checkbox is automatically checked. Its also possible to check/uncheck the checkbox by using a formatter (return true to check, return false to uncheck).

But I can't get this working. 
I tried  `data-formatter="() => false;"` on `<td>`, to no avail.

Could you provide a working example, please?

**Comment by MajesticGray** [comment] 2023-06-08 08:29
Sorry, didn't read support guidelines,
here is the StackOverflow link
https://stackoverflow.com/questions/76429967/setting-checkbox-state-in-html-checked-unchecked

**Comment by UtechtDustin** [comment] 2023-06-08 13:47
As you qouted the documentation as soon a value is in the <td> the checkbox is checked. That is the reason why all checkboxes are checked in your example as the td's contains the values 1, 2 and 3.
In this [example](https://live.bootstrap-table.com/code/UtechtDustin/15542) i removed the values 2 and 3, whichr results in two checkboxes which are not checked.

The same happens for an formatter, the formatter is only needed if you want to check the checkbox based on a other column data or on some other external source.
In this [example](https://live.bootstrap-table.com/code/UtechtDustin/15543) the checkbox will be checked randomly.

I hope this helps :)

**Comment by MajesticGray** [comment] 2023-06-08 14:27
Yes, thanks to your example I figured out that `data-formatter` is not accepting anonymous functions, and requires the function to be defined explicitly.

I would be nice, though, to have an additional attribute on `td` (ie: data-checked="true/false") to have more control over the initial state, instead of having it checked default or adding extra logic.

It is required to add the value (`<td>*value*</td>`) for it to add `value="…"` to the rendered checkbox and thus be submitted. Not doing so will result on an empty array (project[users][] in my example) when submitting the form, but can't see how this is related to the initial state.

So my solution ATM is the following:
- add an attribute to the cell, as well as id value `<td data-checked="true/false">ID</td>`
- add a formatter to the header `<th data-field="id" data-checkbox="true" data-formatter="new_project_checkboxes"></th>`
- define the formatter: 
```
function new_project_checkboxes(a,b,c) { return b._id_data.checked == true; }
```

**Comment by UtechtDustin** [comment] 2023-06-08 14:34
Maybe i miss something, but the current behavior is correct in my opinion.   
You have a dataset which is disabled as table, one property of that dataset is displayed as checkbox.   
So you have an initial dataset (rendered with html or loaded via javascript) which contains the initial checkbox state (true/false).   
Why do want/need an additional `data-checked` attribute ?
You already (somehow) got the initial dataset, which means you know the old state and you can get the new state from the table.

**Comment by UtechtDustin** [comment] 2023-06-08 14:54
Okay i understand, so i guess you are searching for the [idField](https://bootstrap-table.com/docs/api/table-options/#idfield) option ?  
Example: https://live.bootstrap-table.com/example/options/id-field.html

The checkboxes was designed to submit/contains the id (- most common - the primary key of the database) of the dataset.

**Comment by MajesticGray** [comment] 2023-06-09 06:11
I'd love to have a pure html solution, but yes, I think that will do it.
Thank you so much 😊

**Closed** 2023-06-09 12:25 UTC
Labels: help-wanted, awaiting reply
