### ISSUE TITLE
**BUG** Radio button click doesnot trigger onRowClick

### ISSUE THREAD

**Issue by cetindogu** [wenzhixin/bootstrap-table#1581] opened 2015-10-20 15:10 UTC
when i clicked directly the radio button. radio and row selected on the page but onRowClick function is not triggered. it must be triggerred because Clicking the radio button selects the row.
Or i need onSelectChanged function.
Or OnCellClick event
i need a SOLUTION.  

my code is here:

 grid = $('#tblSporcuListe').bootstrapTable({
        url: 'SporcuListesi.aspx/SporcuListesiGetir',
        idField: 'SporcuId',
        method: 'post',
        singleSelect: true,
        clickToSelect: true,
        cache: false,
        sidePagination: 'server',
        queryParams: function (params) {
           
            if (!params.search) {
                params.search = $('#txtBoxTCKimlik').val() + ';' +
                                $('#txtBoxSporcuAdi').val() + ';' +
                                $('#txtBoxSporcuSoyadi').val();
            }
            if (!params.sort) {
                params.sort = 'SporcuId';
            }
            if (!params.limit) {
                params.limit = null;
            }
            if (!params.offset) {
                params.offset = 0;
            }
            
            return params;
        },
        pagination: true,
        pageSize: 10,
        pageList: [10, 25, 50, 100],
        smartDisplay: true,
        search: false,
        showColumns: true,
        showRefresh: false,
        showToggle: true,
        searchAlign: 'left',
        maintainSelected: true,
        onClickRow: function (row) {
            document.getElementById(('btnSporcuyaGit')).removeAttribute('disabled');
            $('#hdnTCKimlik').val(row.TcKimlikNo);
        }
    });

**Comment by dabros** [comment] 2015-10-21 00:41
Seems duplicate of basic issue in #964, with other issues linked there too

**Comment by wenzhixin** [comment] 2015-10-23 03:35
@cetindogu, please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports), your code is hard to read.

**Comment by Edirisinghe** [comment] 2015-10-23 04:53
I have same problem, What i want is, when selecting  the radio button,   row should be select as when click on the row,
hear sample code i have written https://jsfiddle.net/eqpL6w0t/4/

**Comment by wenzhixin** [comment] 2015-10-23 05:17
This is not a bug, you can use `check` event instead: https://jsfiddle.net/eqpL6w0t/5/

**Closed by wenzhixin** 2015-10-23 05:17 UTC

**Comment by Edirisinghe** [comment] 2015-10-23 05:20
Yep i tried with checked event , then I cant change color of selected row !

**Comment by cetindogu** [comment] 2015-10-23 05:28
We need 
bootstrapTable('select',indexOfRow) 
Event

**Comment by wenzhixin** [comment] 2015-10-23 05:54
Why don't you use css to custom the color? @Edirisinghe 
https://jsfiddle.net/eqpL6w0t/8/

**Comment by Edirisinghe** [comment] 2015-10-23 06:01
Yep thank you very much . I tried without use CSS and I wanted to do it  though the JS.

**Comment by cetindogu** [comment] 2015-10-23 09:34
thanks for the answers

2015-10-23 9:01 GMT+03:00 Buddhi Edirisnghe <notifications@github.com>:

> Yep thank you very much . I tried without use CSS and I wanted to do it
> though the JS.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wenzhixin/bootstrap-table/issues/1581#issuecomment-150484698>
> .
>



-- 


*-*
*Çetin DOĞU*Kıdemli Yazılım Uzmanı
Gsm   : +90 507 344 00 00 (Avea)

Gsm   : +90 538 481 00 06 (Turkcell)
