### ISSUE TITLE
Boostrap table with codeigniter remote data and angular js to render data (ng-click doesn't work from custom column)

### ISSUE THREAD

**Issue by ste86horus** [wenzhixin/bootstrap-table#1961] opened 2016-02-01 16:23 UTC
Hello, I'm using your bootstrap tables (really great work!) to load data from remote url (from codeigniter controller). I have  a column called ACTION (created from database query) that shows buttons with operation (edit that calls editCostumer($rowId), and delete that calls deleteCostumer($rowId). You can see that in attached image. 

https://cloud.githubusercontent.com/assets/15056873/12723087/33ac34f6-c908-11e5-98d8-e9ca73afcd86.png

We use angular js to render the data, there is a controller with function $scope.deleteCostumer =function(id){...}. At buttons click (ng-click directive) i call the function but it doesn't work, nothing happens at all. (example: ng-click=”deleteCostumer()” in the delete button)

If i call this function outside the table (top 3 buttons in attached image) or if i call a normal function outside angular it works in both cases. 
It seems it doens't “see” the angular context inside table.
Any ideas to fix the problem? 
I hope that my question was clear enough.

Regards and thank you for your attention.
Stefano Bertoli

**Comment by strikerjjb** [comment] 2016-02-14 23:57
@ste86horus I had the same issue and just figured it out today. If you adjust the directive to include compile it will compile the contents of the element so that Angular can see the ng-click.  Working plunkr here: http://plnkr.co/edit/MyeotRj4YMR0zpofm8lf

**Comment by wenzhixin** [comment] 2016-05-16 23:39
@ste86horus have you solved the problem?

**Comment by djhvscf** [comment] 2017-12-29 08:20
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR**. Thanks!

**Closed by djhvscf** 2017-12-29 08:20 UTC
Labels: angular, awaiting reply
