### ISSUE TITLE
Bind an 'Advanced Search' form to the BootstrapTable

### ISSUE THREAD

**Issue by webgodo** [wenzhixin/bootstrap-table#359] opened 2014-12-19 17:13 UTC
Hi, TNX for your nice plugin.
I want to add an 'Advanced Search' Form above the table;
The user fills the form and clicks Submit button. Now the table should load AJAX response. How can we do this?
Note that I want the table to do it's correct job even on pagination and client-side search.

**Comment by maxgrass** [comment] 2015-04-14 14:40
it's not a bug?
has you solved this?

**Comment by webgodo** [comment] 2015-04-15 06:24
I did it using a trick, but not straightforward!

**Comment by maxgrass** [comment] 2015-04-15 06:27
I think the author should close this, as this is not an issue or clearly defined feature.

**Comment by wenzhixin** [comment] 2015-04-15 06:48
OK, close this.

**Closed by wenzhixin** 2015-04-15 06:48 UTC

**Comment by arvmohan** [comment] 2015-08-06 07:33
@webgodo how did you solve this issue? 
@wenzhixin is there any solution for this out of the box?

**Comment by wenzhixin** [comment] 2015-08-06 09:36
@arvmohan , we have added an extension: http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/toolbar.html

**Comment by arvmohan** [comment] 2015-08-06 10:38
@wenzhixin will this work with server side pagination also?
