### ISSUE TITLE
[bug] window.operateEvents returning the wrong "row" data after deleting bottom and top rows from table.

### ISSUE THREAD

**Issue by BinaryVirus01** [wenzhixin/bootstrap-table#2403] opened 2016-06-22 18:24 UTC
After appending rows from one table to another I try to test the delete button located in a column of the 2nd table which was created with the column formatter and uses the window.operateEvents call for the listener. 
After pressing the delete button a few times, once on the bottom row, once on the top row. The data coming back from the event starts to become incorrect and is returning rows that have already been deleted. When i use the "getData" method the rows being returned are no longer in the array. Seems that others are having similar issues.

The code in question below with the "row" parameter being incorrect after a few clicks.

```
   window.operateEvents = {
        'click .remove': function (e, value, row, index) {
                $('#tblBulkUpdateSalesRepHistoryBatch').bootstrapTable('removeByUniqueId', row.Id);
        }
```

**Comment by BinaryVirus01** [comment] 2016-06-27 18:35
seems like this issue was fixed in a previous patch but might have been reverted by accident.
Please let me know the status on this fix.

**Comment by wenzhixin** [comment] 2016-07-03 07:16
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!
Maybe you can try version 1.11.0

**Comment by BinaryVirus01** [comment] 2016-07-05 16:33
I provided the code causing the issue, its the remove method for the
table. you fixed the issue in a previous release but i think the change
might have been reverted, you can easily test it on the new code base by
filling a table with 3 records and deleting the bottom record, then delete
the top record, and trying to delete the last record will not work...

**Comment by BinaryVirus01** [comment] 2016-07-05 16:34
FYI i fixed the issue by refreshing the table after each delete, it seems
that the indexes are not gettin updated when the remove method is used.

**Comment by wenzhixin** [comment] 2016-07-09 02:54
http://issues.wenzhixin.net.cn/bootstrap-table/
I cannot find the problem in this example.

**Comment by amauritgsi** [comment] 2016-10-26 13:06
Good morning, I have the same problem, how to play below.

Go to the last page, select all items, deselect one and remove, after remove the last item using the link on the line, and the problem occurs.

**Comment by amauritgsi** [comment] 2016-10-26 13:21
My temporary solution

`if($('#table').bootstrapTable('getData').length ===0){$('#table').bootstrapTable('prevPage');}`

**Comment by djhvscf** [comment] 2017-12-29 08:18
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR**. Thanks!

**Closed by djhvscf** 2017-12-29 08:18 UTC
Labels: awaiting reply, help wanted

**Comment by danger89** [comment] 2019-01-07 23:20
Took me a while to find the source code actually of this 'Welcome example' could be me..

Check it out: https://github.com/wenzhixin/bootstrap-table-examples/blob/master/welcome.html

**Comment by wenzhixin** [comment] 2019-01-08 15:40
@danger89 Example: https://bootstrap-table-examples.wenzhixin.net.cn/

**Comment by danger89** [comment] 2019-01-08 16:13
@wenzhixin I know.. I said it was hard to find the SOURCE CODE. Since I didn't expect it was hosted on github.com itself as well. And the github link/menu item on that webpage went not to Bootstrap-table source but actually to the bootstrap-table-examples source, that was **unexpected**. Often you see a link above an example with a link, saying "_View source-code"_. Right?

So to be so picky, but that was my experience, I can't change how my experience was.

**Comment by wenzhixin** [comment] 2019-01-08 22:30
OK, I will consider to improving it.
