### ISSUE TITLE
变换视图之后能显示多列吗？

### ISSUE THREAD

**Issue by dzlishen** [wenzhixin/bootstrap-table#2407] opened 2016-06-23 06:05 UTC
变换视图之后能显示多列吗？

**Comment by wenzhixin** [comment] 2016-07-03 07:02
啥意思呢

**Comment by djhvscf** [comment] 2017-12-29 08:18
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR**. Thanks!

**Closed by djhvscf** 2017-12-29 08:18 UTC
Labels: awaiting reply
