### ISSUE TITLE
How can I use this in a react Development environment? 

### ISSUE THREAD

**Issue by JudeAshan98** [wenzhixin/bootstrap-table#5749] opened 2021-05-31 10:39 UTC
**Description**  

I tried to start working with the bootstrap-tables in my react application. But I tried and didn't find a way to get it to work. If it is possible, please share with an example. Thanks!

**Example (optional)**

**Comment by wenzhixin** [comment] 2021-06-06 10:24
Duplicate of #5481

**Closed by wenzhixin** 2021-06-06 10:24 UTC
Labels: help-wanted
