### ISSUE TITLE
Resize Issue

### ISSUE THREAD

**Issue by cgountanis** [wenzhixin/bootstrap-table#3614] opened 2018-02-21 21:20 UTC
When I add a second table and resize the browser window the columns do not line up. Has this been seen before or maybe get fixed with BS4 updates?

![2018-02-21 15_18_31-template sample web site - firefox developer edition](https://user-images.githubusercontent.com/14899817/36505960-c7b5763c-171a-11e8-8f7a-f89f2cba4267.png)

**Comment by cgountanis** [comment] 2018-02-21 21:22
![2018-02-21 15_21_53-template sample web site - firefox developer edition](https://user-images.githubusercontent.com/14899817/36506034-00445de2-171b-11e8-98e9-7445db7c9e70.png)

**Comment by jimgit** [comment] 2018-02-22 03:30
Can you provide a JSFIDDLE example?

**Comment by cgountanis** [comment] 2018-02-22 15:44
Sure.

https://jsfiddle.net/qsapzxnr/10/

**Comment by cgountanis** [comment] 2018-02-22 21:39
Using bower to get the LIB locally. Same issue with the CDN version 1.11.0 > 1.11.1.

![image](https://user-images.githubusercontent.com/14899817/36565612-98f185b2-17e6-11e8-9c19-33936b75909d.png)

**Comment by cgountanis** [comment] 2018-02-23 16:09
Just to be complete in testing, I tried with the new DEVELOP CDN version and the issue persists.

https://jsfiddle.net/qsapzxnr/12/

**Comment by cgountanis** [comment] 2018-03-01 22:03
Anytime you have a multiple tables in a single row, even when they are in their own col-md-6 (one row two cols with tables), it seems to be an issue.

**Comment by cgountanis** [comment] 2018-03-01 22:09
I simplified the demo to help with easy understanding.

https://jsfiddle.net/qsapzxnr/19/

**Comment by cgountanis** [comment] 2018-03-01 22:19
I noticed it is fine without data-height="400", so if you exclude that tag or set to "0" it is fine but sometimes I need to use the height. Is there a work around or does this help get it in the next release as bug fix maybe?

**Comment by cgountanis** [comment] 2018-03-02 22:09
Let me know if I can help in any way.

**Comment by cgountanis** [comment] 2018-03-15 16:02
This is still an issue. Just resize your browser window to see the columns get out of sync.

https://jsfiddle.net/qsapzxnr/39/

**Comment by cgountanis** [comment] 2018-07-26 13:58
Was there anything in the works or a quick fix that I might have missed for this?

**Comment by Falseee** [comment] 2019-04-07 05:20
Looks like that the issue is already fixed, if not pls reopen the issue.
Working example: http://jsfiddle.net/c6x2ng1e/2/

**Comment by cgountanis** [comment] 2019-04-08 14:09
I updated to 1.14.2 and the issue persists. Am I missing something?

https://jsfiddle.net/5szueL6n/2/

**Comment by wenzhixin** [comment] 2019-04-08 14:43
Duplicate of #4203

**Closed** 2019-04-08 14:54 UTC
Labels: update to latest version
