### ISSUE TITLE
 How to remove rows using the data- index

### ISSUE THREAD

**Issue by mcruzm** [wenzhixin/bootstrap-table#2660] opened 2016-09-21 17:38 UTC
You can do the following $ ( "table" ) bootstrapTable ( "remove " data- index { 1 } ) .

**Comment by Falseee** [comment] 2019-03-23 09:55
There is no data-index option, you can assign unique ids and remove the rows with [removebyuniqueid](https://bootstrap-table.com/docs/api/methods/#removebyuniqueid)

**Comment by wenzhixin** [comment] 2019-03-23 10:24
Duplicate of #564

**Closed by wenzhixin** 2019-03-23 10:24 UTC
