### ISSUE TITLE
bootstrap-table-cookie doesn't work with  data-filter-control="true"

### ISSUE THREAD

**Issue by jogo** [wenzhixin/bootstrap-table#1840] opened 2015-12-29 00:00 UTC
when enabling bootstrap-table-cookie  along with  data-filter-control="true", the filter-control data is preserved but the search and page numbers are not.

**Comment by dabros** [comment] 2016-01-04 04:19
@jogo - is it possible to provide a fiddle or example proving this (can include official example that demonstrates this, but any source code mod needs a fiddle so we can replicate and test it)

https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

**Comment by jogo** [comment] 2016-01-05 02:56
jfiddle example: 

http://jsfiddle.net/kptmj1qh/1/

search for something, reload the page and the search box will have the previous value but the table won't be filtered. See screenshot below.

![image](https://cloud.githubusercontent.com/assets/1137168/12106456/8e8ce87a-b314-11e5-9502-05aefecdfffa.png)


Tested in Chrome.

**Comment by dabros** [comment] 2016-01-05 03:43
@jogo - im seeing the opposite

Search box retains content, and results are still filtered on F5 refresh

Doing normal refresh doesnt show what you shared above, BUT i did notice 3 sets of behaivour when clicking 'run' (which is NOT a refresh action, rather recreates content in result panel, and will have quirks where F5 refresh right after might still remember last value of form input on page)

Clicking 'run' (between F5 refreshes and other such activity) varied between:

1. clearing all form inputs and showing all table rows, OR
2. taking 'ss' i typed into main search field, leaving 's' in main search and putting another 's' in last filter-control i cleared before 'run', OR
3. showing what you shared above, main search field still 'ss' but all table rows

Unfortunately this just makes jsfiddle unable to be used to prove this behaivour, except to say DONT click 'run', but use actual refresh (F5). That said, F5 seemed to work for me but im not sure if thats luck and F5 equates to 'run' via `onDomReady` callback when page loaded...

Either way, i cant confirm from fiddle, so please clarify again steps you use to reproduce in production environment.

Notably, please try putting values in all filter controls AND main search, using F5 refresh. Then remove some and repeat.

Then do same and click url bar and hit enter (aka hard refresh), again removing some and repeating again.

For more info, also grab any extension for monitoring cookies (web developer is one example) and use that to monitor cookie changes between each refresh.

Thats basically what i would have done if jsfiddle more reliable for this testing.

**Comment by jogo** [comment] 2016-01-12 03:58
I hope the steps below are clear enough to reproduce the issue. If not let me know.

Using the jfiddle above:

Case 1
=====

Setup:  fill in every value 

![image](https://cloud.githubusercontent.com/assets/1137168/12254099/0c137f86-b89a-11e5-9886-bacbdca97b4c.png)

1. Delete value in search box, press enter
2. Press 'F5' works as expected
3. Reload the page via hard refresh, doesn't work. Search value comes back.


Case 2
======

Make sure all relevant cookies are cleared

Setup: Type boot in search box

![image](https://cloud.githubusercontent.com/assets/1137168/12254319/f8b87570-b89b-11e5-9e75-1465f4eaf116.png)

* pressing F5 should work
* Hard reset should work too
* There should only be one cookie: ```saveId.bs.table.searchText```, value: ```boot```

Without changing anything from the previous setup, type '5' in Stars filter and press F5

Result:

![image](https://cloud.githubusercontent.com/assets/1137168/12254367/82dbe1ce-b89c-11e5-8a41-e19a768870b0.png)

* Search value was replaced
* Start filter of 5 doesn't work
* cookies:
    *  ```saveId.bs.table.filterControl``` , value: ```%5B%7B%22field%22%3A%22stargazers_count%22%2C%22text%22%3A%225%22%7D%5D	```
    *  ```saveId.bs.table.searchText```, value: ```5```

Case 3
======

Make sure all relevant cookies are cleared

Setup: 

![image](https://cloud.githubusercontent.com/assets/1137168/12254422/fc4cdacc-b89c-11e5-958f-fe97466b3d73.png)


Press F5

Results

![image](https://cloud.githubusercontent.com/assets/1137168/12254427/1118f134-b89d-11e5-88f6-9eda71400b68.png)
 

* cookies:
    *  ```saveId.bs.table.filterControl``` , value: ```%5B%7B%22field%22%3A%22name%22%2C%22text%22%3A%22blog%22%7D%5D```
    *  ```saveId.bs.table.searchText```, value: ```z```

**Comment by dabros** [comment] 2016-01-12 04:58
@jogo - as i said, the fiddle produced unreliable results, so can you please confirm you made a local copy of this (local or live server, NOT jsfiddle or similar emulator) and that the above points are all exactly true in that environment as well?

Also, not sure bout you but i have F12 setup so no cache when its open. Best to close that while testing, or at least account for it if true for you too.

**Comment by jogo** [comment] 2016-01-13 02:13
I'll retest this with a local copy and report back, thank you!

**Comment by jogo** [comment] 2016-01-13 03:12
Running the latest develop code locally (http://paste.ubuntu.com/14483575/plain/).

Case 1: No issues
Case 2: No issues
Case 3: Still seeing the same failure condition, where the search Z isn't applied.

**Comment by dabros** [comment] 2016-01-15 00:21
@jogo
`autocomplete="off"`

This last test has narrowed it down to a browser issue, nothing to do with bootstrapTable except in that bootstrap table expects the search param passed explicit to it on init if starting with a query - it wont check existing content in search field, only onChange/keyevents.

If you wanted to apply the search, just call something like `resetSearch` (not in doco atm, but search code and github for it) with the contents of the search field.

Or if you wanted to ignore it, try something like `autocomplete="off"` http://stackoverflow.com/questions/1799899/html-input-value-kept-after-refresh

Though in worst case that fails, first search for more browser related fixes ("stop remembering input after refresh", ect) then consider `onDocumentReady` or other triggers with expliticit calls, though i seriously dont expect that is needed.

**Comment by jogo** [comment] 2016-01-17 23:05
code used: https://gist.github.com/jogo/4ab68e399008fb25478b (same as previous paste link).

I confirmed that in Case 3 both cookies were set but don't appear to be applied correctly. It looks like the search value is there but not applied. (The search value is applied if ```saveId.bs.table.filterControl``` is not set)

Result after pressing F5:

![image](https://cloud.githubusercontent.com/assets/1137168/12380591/358b090c-bd2b-11e5-94e8-8d842a8c23d8.png)


![image](https://cloud.githubusercontent.com/assets/1137168/12380587/20dc5114-bd2b-11e5-9909-62167ffcf2c5.png)

**Comment by dabros** [comment] 2016-01-19 01:31
@jogo @djhvscf 

I assume the fault must then lie in https://github.com/wenzhixin/bootstrap-table/blob/master/src/extensions/cookie/bootstrap-table-cookie.js, but i cant really see it myself.

If global search applied correct when no filtercontrol, and individual column filters working WITH filtercontrol, then has to be that individual column filters set correct

But i just keep see it myself yet:


```javascript
BootstrapTable.prototype.init = function () {
        var timeoutId = 0;
        this.options.filterControls = [];
        this.options.filterControlValuesLoaded = false;


        this.options.cookiesEnabled = typeof this.options.cookiesEnabled === 'string' ?
            this.options.cookiesEnabled.replace('[', '').replace(']', '').replace(/ /g, '').toLowerCase().split(',') : this.options.cookiesEnabled;

        if (this.options.filterControl) {
            var that = this;
            this.$el.on('column-search.bs.table', function (e, field, text) {
                var isNewField = true;

                for (var i = 0; i < that.options.filterControls.length; i++) {
                    if (that.options.filterControls[i].field === field) {
                        that.options.filterControls[i].text = text;
                        isNewField = false;
                        break;
                    }
                }
                if (isNewField) {
                    that.options.filterControls.push({
                        field: field,
                        text: text
                    });
                }

                setCookie(that, cookieIds.filterControl, JSON.stringify(that.options.filterControls));
            }).on('post-body.bs.table', function () {
                setTimeout(function () {
                    if (!that.options.filterControlValuesLoaded) {
                        that.options.filterControlValuesLoaded = true;
                        var filterControl = JSON.parse(getCookie(that, that.options.cookieIdTable, cookieIds.filterControl));
                        if (filterControl) {
                            var field = null,
                                result = [],
                                header = getCurrentHeader(that),
                                searchControls = getCurrentSearchControls(that);

                            header.find(searchControls).each(function (index, ele) {
                                field = $(this).closest('[data-field]').data('field');
                                result = $.grep(filterControl, function (valueObj) {
                                    return valueObj.field === field;
                                });

                                if (result.length > 0) {
                                    $(this).val(result[0].text);
                                    that.onColumnSearch({currentTarget: $(this)});
                                }
                            });
                        }
                    }
                }, 250);
            });
        }
        _init.apply(this, Array.prototype.slice.apply(arguments));
    };

```

**Comment by ioctaptceb** [comment] 2016-01-29 16:34
Hi, I think I know what is going on here, and I can take over if no one else is working on this. I fixed the other two issues that @jogo has mentioned on #1749

**Comment by djhvscf** [comment] 2016-01-29 16:40
@ioctaptceb so go ahead!! thanks

**Comment by jogo** [comment] 2016-01-29 19:40
@ioctaptceb thanks!

**Comment by djhvscf** [comment] 2016-02-11 14:02
@jogo any update here?

**Comment by jogo** [comment] 2016-02-14 02:04
@djhvscf, I was under the impression @ioctaptceb  was going to take this over and work on it.

**Comment by djhvscf** [comment] 2016-02-14 02:43
Yes @jogo my mistake... @ioctaptceb any update here?

**Comment by ioctaptceb** [comment] 2016-02-17 11:40
Hi, sorry -- was away for a bit. Will get back to you guys on this in a bit

**Comment by DustinUtecht** [comment] 2017-04-03 10:12
@ioctaptceb any update here?

**Comment by djhvscf** [comment] 2017-05-10 17:28
@ioctaptceb any update here?

**Comment by djhvscf** [comment] 2017-06-19 06:34
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR**. Thanks!

**Closed by djhvscf** 2017-06-19 06:34 UTC
Labels: awaiting reply, extension

**Comment by colinmoffat** [comment] 2017-07-21 18:53
Currently encountering the same issue. page refreshes, searches remain in the filter control boxes but the table data is not filtered.

**Comment by 365dayes** [comment] 2020-06-19 23:39
I'm still experiencing this issue. See the following. ...https://stackoverflow.com/questions/62456971/bootstrap-table-hard-refresh-remove-some-cookies-but-not-others

**Comment by UtechtDustin** [comment] 2020-06-20 11:00
Hey @365dayes, please provide us an example using our [online editor](live.bootstrap-table.com/).

**Comment by 365dayes** [comment] 2020-06-20 16:01
https://live.bootstrap-table.com/code/365dayes/3521

When I build locally I don't get the two searches not sure why it's doing that on the online editor, but in my local environment, the search cookie is wiped with a hard refresh. Using the refresh button built into the toolbar keeps the cookie. I noticed if I remove data-filter-control="true"
 from my table, the saved search gets populated with a hard refresh.

**Comment by UtechtDustin** [comment] 2020-06-20 17:10
If it works on the editor it should also work on your local machine.
Could you please provide us a example (with data) as upload ?

**Comment by 365dayes** [comment] 2020-06-20 21:20
Sorry, I'm unable to supply the data. It's private. My local machine shows one search. The editor shows two search boxes. The top searchbox replicates the issue. The bottom one doesnt.

**Comment by UtechtDustin** [comment] 2020-06-21 08:08
You can use fake data....

**Comment by djhvscf** [comment] 2020-06-21 15:21
And also please create a new bug
