### ISSUE TITLE
paginationVAlign: 'both' not working in chrome

### ISSUE THREAD

**Issue by cbielich** [wenzhixin/bootstrap-table#3324] opened 2017-08-18 22:50 UTC
When applying the paginationVAlign to my js the pagination still stays on the bottom and does not show on the top as well

I have tested with IE, Firefox and safari (both desktop and mobile) and it works fine. It just does not work in chrome desktop, but it does work in chrome mobile. Any ideas?

**Comment by martinburch** [comment] 2017-08-28 22:16
I'm unable to reproduce this on Chrome Desktop ...
Mac OS X 10.10.5
Chrome Version 60.0.3112.113 (Official Build) (64-bit)

Here's my fiddle: http://jsfiddle.net/e3nk137y/15727/
![image](https://user-images.githubusercontent.com/2335284/29796017-da7a9d10-8c46-11e7-8fda-270283d906bf.png)

**Comment by djhvscf** [comment] 2017-12-08 15:46
Close this issue since we don't have any reply in the last 7 days

**Closed by djhvscf** 2017-12-08 15:46 UTC
