### ISSUE TITLE
I get a second horizontal scroll bar, which scrolls to whitespace. 

### ISSUE THREAD

**Issue by bigbadhamster** [wenzhixin/bootstrap-table#5439] opened 2020-11-14 16:08 UTC
**Bootstrap-table version(s) affected**:
https://unpkg.com/bootstrap-table@1.18.0/dist/bootstrap-table.min.css
with bootstrap-4, bootstrap-5 

**Description**  
I create a table with multiple columns that make the horizontal scrollbar appear. I get two scrollbars, one is the expected below the table and the other at the end of the div that scrolls to white space. This appears also in the online editor, default settings,  

**Example**  
To reproduce:
1)https://live.bootstrap-table.com/example/options/page-size.html
2)create more columns by copy-pasting the 3 th elements
3)click Run
this is what I see. 
(before scroll)
![Screenshot_2020-11-14 Online Editor - Bootstrap Table](https://user-images.githubusercontent.com/74460980/99150814-cadbf380-269f-11eb-89fb-a6e9c05b80f7.png)

(after scroll)
![Screenshot_2020-11-14 Online Editor - Bootstrap Table(1)](https://user-images.githubusercontent.com/74460980/99150813-c9aac680-269f-11eb-8817-5fb54512cadd.png)

**Possible  (optional)**  
I have tried (on my site) every relevant div wrap class I could find.
this is what it looks on my site with table-responsive wrap.
![Screenshot_2020-11-14 with table-responsive](https://user-images.githubusercontent.com/74460980/99151339-2065cf80-26a3-11eb-9252-195de55ccdac.png)

**Additional context**  
Screenshots are from Firefox version 82.0.3 (Latest). I see the same from Chrome, also latest version (Windows OS)
It does not appear If I select settings,theme,bootstrap-3, on the online editor.

**Comment by bigbadhamster** [comment] 2020-11-14 17:55
I have just found that wrapping the table with
<div class="overflow-hidden">
</div>
eliminates the outer scrollbar.
I have a feeling that is is a workaround and not a fix.

**Comment by wenzhixin** [comment] 2021-07-04 15:25
Duplicate of #5348
Fixed in #5779

**Closed by wenzhixin** 2021-07-04 15:25 UTC
Labels: Bug, confirmed

**Comment by bigbadhamster** [comment] 2021-07-04 17:15
cool, I confirm is fixed.
