### ISSUE TITLE
checkbox disappears when cookies are enabled and any columns are hidden

### ISSUE THREAD

**Issue by thirukumaran13** [wenzhixin/bootstrap-table#6556] opened 2022-12-15 03:09 UTC
### Bootstraptable version(s) affected

1.21.2

### Description

Cookies enabled
Show Columns enabled
Checkbox enabled

Everything works under any column is hidden/unhidden. Then on reloading the page the checkbox column disappears. 

### Example(s)

```<script src="https://unpkg.com/bootstrap-table@1.21.2/dist/extensions/cookie/bootstrap-table-cookie.min.js"></script>

<table
  data-toggle="table"
  data-search="true"
        data-cookie="true"
  data-cookie-id-table="saveId"
  data-show-search-clear-button="true"
      data-click-to-select="true"
  data-show-columns="true">
  <thead>
    <tr class="tr-class-1">
      <th data-checkbox="true"></th>
      <th data-field="name" data-valign="middle" >Name</th>
      <th data-field="star">Stars</th>
      <th data-field="forks" >Forks</th>
      <th data-field="description" >Description</th>
    </tr>
  </thead>
  <tbody>
    <tr id="tr-id-1" class="tr-class-1" data-title="bootstrap table" data-object='{"key": "value"}'>
      <td></td>
      <td id="td-id-1" class="td-class-1" data-title="bootstrap table">
        <a href="https://github.com/wenzhixin/bootstrap-table" target="_blank">bootstrap-table</a>
      </td>
      <td data-value="526">8827</td>
      <td data-text="122">3603</td>
      <td data-i18n="Description">An extended Bootstrap table with radio, checkbox, sort, pagination, and other added features. (supports twitter bootstrap v2 and v3)
      </td>
    </tr>
    <tr id="tr-id-2" class="tr-class-2">
      <td></td>
      <td id="td-id-2" class="td-class-2">
        <a href="https://github.com/wenzhixin/multiple-select" target="_blank">multiple-select</a>
      </td>
      <td>1615</td>
      <td>623</td>
      <td>A jQuery plugin to select multiple elements with checkboxes :)
      </td>
    </tr>
    <tr id="tr-id-3" class="tr-class-3">
      <td></td>
      <td id="td-id-3" class="td-class-3">
        <a href="https://github.com/wenzhixin/bootstrap-show-password" target="_blank">bootstrap-show-password</a>
      </td>
      <td>220</td>
      <td>85</td>
      <td>Show/hide password plugin for twitter bootstrap.
      </td>
    </tr>
    <tr id="tr-id-4" class="tr-class-4">
      <td></td>
      <td id="td-id-4" class="td-class-4">
        <a href="https://github.com/wenzhixin/bootstrap-table-examples" target="_blank">bootstrap-table-examples</a>
      </td>
      <td>1734</td>
      <td>1532</td>
      <td>Bootstrap Table Examples</td>
    </tr>
    <tr id="tr-id-5" class="tr-class-5">
      <td></td>
      <td id="td-id-5" class="td-class-5">
        <a href="https://github.com/wenzhixin/scutech-redmine" target="_blank">scutech-redmine</a>
      <td>24</td>
      <td>18</td>
      <td>Redmine notification tools for chrome extension.</td>
    </tr>
  </tbody>
</table>
```
Try hide/unhide any column and reload the page. The checkbox will disappear.

**Comment by svinsightdata** [comment] 2022-12-20 10:10
This bug also affects radio buttons.
As such we had to remove the cookie extension until the bug is resolved.

**Comment by yeezy69** [comment] 2023-01-02 19:51
Duplicate of #6423

**Closed** 2023-01-03 02:08 UTC
Labels: Bug
