### ISSUE TITLE
Sorting doesn't work with stickyHeader

### ISSUE THREAD

**Issue by docholiday** [wenzhixin/bootstrap-table#1929] opened 2016-01-22 21:39 UTC
When stickyHeader is activated, as long as the table header is visible "the regular way", sorting works. But as soon as you scroll down, so that the header is "floating", the sorting function doesn't work anymore and the icon showing which column you used for sorting is back to the two grey up and down arrows.
Apart from that, stickyHeader works like a charm (even in Internet Explorer 11), so thank you very much :-)
You should however mention in the readme, that you can activate it in the HTML part via data-sticky-header="true" and data-sticky-header-offset-y="SOMEOFFSETpx".

**Comment by djhvscf** [comment] 2016-01-26 13:56
Please provide a fiddle with your issue

**Comment by dabros** [comment] 2016-01-26 23:55
@docholiday 

https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports

Fork and tweak an example fiddle to suit your purpose.

**Comment by charettes** [comment] 2016-03-09 00:16
I'm also affected by this issue. I couldn't reproduce on jsFiddle as the iframe [https://jsfiddle.net/d7t8uj0b/3/ might be too small] but the actual plugin example [exhibit the same problem](http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/sticky-header.html).

Simply try sorting a column when the header is "sticked" and you'll manage to reproduce. From a quick look at the source it looks like the plugin clones the header instead of "grafting" it to the correct parent in order to keep all the attached event listener.

**Comment by charettes** [comment] 2016-03-09 06:50
This looks like a duplicate of #2001

**Comment by dabros** [comment] 2016-03-09 08:04
@charettes - i was going to say the same, though only had a few minutes to glance at this earlier.

If anyone wants to help with this or #2001 please do so

I had thought changing it to `clone(true,true)` would have worked in fixed-columns question as well as here, but it didnt work there and using chrome F12 + breakpoint (to pause code before it performed clone) and changing source code for example shown above to use `clone(true,true)` didnt appear to work here either.

**Comment by djhvscf** [comment] 2016-04-16 07:22
See #2180

**Closed** 2016-04-22 06:01 UTC
Labels: confirmed, extension, fixed
