### ISSUE TITLE
Table doesn't get updated when refresh method is called from a popup window

### ISSUE THREAD

**Issue by Juniornativa** [wenzhixin/bootstrap-table#2539] opened 2016-08-03 19:07 UTC
$table = $("#table", opener.document);  
$table.bootstrapTable('refresh', {
       url: $("#dataUrl").val()
});

This snippet is inside a popup window

Could somebody help me please?

**Comment by dabros** [comment] 2016-08-03 23:27
Please provide a Fiddle and we can help you more, dummy data from js array is fine (just needs to replicate core issue). For data-url use them from examples provided, if you need more custom server side then see http://stackoverflow.com/questions/7194408/how-can-i-use-the-jsfiddle-echo-feature-with-jquery

Examples and guide provided below:
- https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports
- #1765

You need to replicate the core issue else we cant help at all, also be sure to hit F12 and keep eye on console when testing anything, it will almost definetly be printing an error there for you that could help you solve this yourself (likely $table not set correctly for whatever reason)

**Comment by djhvscf** [comment] 2017-12-29 08:17
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR**. Thanks!

**Closed by djhvscf** 2017-12-29 08:17 UTC
Labels: awaiting reply, help wanted
