### ISSUE TITLE
Missing event for when the loading of all table rows is done

### ISSUE THREAD

**Issue by Crusader2010** [wenzhixin/bootstrap-table#5445] opened 2020-11-16 18:24 UTC
Hi,

I'm currently loading about 2000 rows inside a bootstrap table, using Razor/ASP.NET.
Current table attributes are:

- class="table table-bordered table-hover"
- data-toggle="table"
- data-search="false"
- data-filter-control="true"
- data-click-to-select="true"

After some quick debugging, I found out what events are being triggered while the table is loading its rows.
As you can see, this is a repeatable list (of the bold-ed events).

So, 3 questions:

1. How can I know when the table is done loading/displaying **all** the rows?? From the list below, there is NOTHING specific for this. Why do I need this? because I want to show a wait dialog until the table is finished loading. Obviously, "**onLoadSuccess**" isn't working since I'm not using remote data.
2. Is there a way to trigger all of these events only ONCE, when first loading the table rows?
3. Why are the *page-change*, *search*, *column-search* events firing even if I'm not using pagination nor the search feature?

* [....]
* page-change.bs.table
* pre-body.bs.table
* post-header.bs.table
* reset-view.bs.table
* post-body.bs.table
* created-controls.bs.table
* search.bs.table
* column-search.bs.table
* **page-change.bs.table**
* **pre-body.bs.table**
* **post-header.bs.table**
* **reset-view.bs.table**
* **post-body.bs.table**
* **created-controls.bs.table**
* **search.bs.table**
* **column-search.bs.table**
* [....]

**Comment by djhvscf** [comment] 2020-11-16 19:51
Do you mean that on post body event is firing before the body is drawn?

**Comment by Crusader2010** [comment] 2020-11-16 20:01
> 
> 
> Do you mean that on post body event is firing before the body is drawn?

That I am not sure of, and I don't think it's relevant to my issue.
I simply need an event that triggers after the whole body of the table is drawn (and all rows are loaded). 
Currently, it seems the table is loaded in chunks, each chunk triggering the sequence of events from the list. My problem is finding out a way to identify (and run some custom code after) the last iteration of this cycle.

**Comment by wenzhixin** [comment] 2020-11-20 02:41
> I'm not using remote data

I think the `showLoading` and `hideLoading` methods can solve your problem: https://live.bootstrap-table.com/code/wenzhixin/5468

**Comment by Crusader2010** [comment] 2020-11-20 10:08
How do I know when to call "hideLoading", since I am not loading the table from a JSON? 
Like I asked before, which is the **single** event that signals the fact that the table finished loading all of its rows? I need one event, not a repeating list of events. Something like 'onLoadSuccess', but working for all types of data loading (not just remote).

Also, is there an event that signals the table started to load its rows and controls (maybe even before being drawn on the screen)?

Thanks

**Comment by atomkind** [comment] 2020-12-30 16:23
I (still) try and search the same like Crusader2010.

There is no event to be fired (once) when bootstrap-table is "ready" or finished drawing the table.
_Similar to jQuery's document.ready._

I tryed `post-header.bs.table`, `post-body.bs.table` and `all.bs-table`
even `all.bs.table` doesnt fire when the table is drawn to user, what means (in my opinion) there is no such event.

See fiddle:
[https://jsfiddle.net/98w52zn4/](https://jsfiddle.net/98w52zn4/)

`....on( 'all.bs.table', function(name, args){
   console.log( 'all' );
} )....`

**Comment by MrGurns** [comment] 2021-02-05 23:21
I'm also experiencing this issue.
With Server Side,
```
	var $table = $('table');
	var checkAll = false;
	var selectAll = function() {
		checkAll = true;
		$table.bootstrapTable('togglePagination');
		$table.bootstrapTable('getData').forEach(function (item) {
			batchIds.push(item.id)
		});
		$table.bootstrapTable('checkAll');
		//still need to add all items in all pages to the batchIds
		$table.bootstrapTable('togglePagination'); //this should get to this point and wait, but for some reason it doesn't
		console.log('batchIds: ', batchIds);
	};
	var tableResponseHandler = function(res) {
		res.rows.forEach(function (item) {
                        if (checkAll) {
				item.selected = true
				batchIds.push(item.id);
			}
		});
		return res;
	};

                     <table data-page-list="[25, 50, 100]"
				data-page-size="25"
				data-pagination="true"
				data-side-pagination="server"
                                data-response-handler="tableResponseHandler"
				>	...			
```
The issue is, toggle pagination and getting the data back from the table doesn't happen syncronosly it seems, as it toggles the pagination back off before it adds everything to batchIds

**Comment by UtechtDustin** [comment] 2022-07-09 15:34
The events should work fine (https://live.bootstrap-table.com/code/UtechtDustin/12069).
I will close this issue because it's quite old and maybe we fixed it already in the newest version.

If someone still need help with that and thinks he can't use a existing event please provide us an exampek using our [online editor](https://live.bootstrap-table.com/).
We will reopen the issue if needed.

**Closed by UtechtDustin** 2022-07-09 15:34 UTC
Labels: help-wanted, awaiting reply

**Comment by ductridev** [comment] 2024-04-26 02:34
IMO still need different events for this problem. The solution of @UtechtDustin is good only for loading first-time data, if we refresh or add more data, it will call many times.
