### ISSUE TITLE
Filter control extension issue

### ISSUE THREAD

**Issue by jonathangreco** [wenzhixin/bootstrap-table#2258] opened 2016-05-11 07:29 UTC
Hi,

I use jquery 1.11.2 with bootstrap 3.3.5, and with filter control I have an issue that I can't reproduce with a fiddle (not the same context I guess).

My issue is about this code :

``` JS
$.each(header.children().children(), function (i, tr) {
                tr = $(tr);
                if (tr.data('field') === column.field) {
                    tr.find('.fht-cell').append(html.join(''));
                    return false;
                }
            });
```

I don't understand this code because header is the thead element, so the childrens of its children are "th" element not "tr" :

``` HTML
<thead>
     <tr> <! -- header.children()-->
         <th></th><! -- header.children().children()-->
</tr> 
</thead>
```

And in my code I have the same DOM as your example, and this code duplicates the filters in the fht-cell 's div.

As explained, i tried to remove one `.children()` call an it works.

Is this a bug ?

**Comment by djhvscf** [comment] 2016-05-13 15:03
We need an example in order to see your case... but anyway I will try to reproduce in my side

**Comment by wenzhixin** [comment] 2016-07-12 05:01
Any update?

**Comment by jonathangreco** [comment] 2016-07-12 13:21
No updates at this time, I've fixed this on my local copy and it worked, it's running on production for me. But I don't know if you'll consider this as a bug.

**Comment by wenzhixin** [comment] 2016-07-12 13:49
Can you help to provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!
BTW, any pull request is welcome.

**Comment by djhvscf** [comment] 2018-01-29 05:56
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR** with an [example](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports). Thanks!

**Closed by djhvscf** 2018-01-29 05:56 UTC
Labels: filter-control, needs example
