### ISSUE TITLE
Problem with Search and "Display all Line"

### ISSUE THREAD

**Issue by support-whiteweb** [wenzhixin/bootstrap-table#5748] opened 2021-05-31 09:57 UTC
**Bootstraptable version(s) affected**:
Version : 1.18.3

**Description**  
When we want to search something, we click on the search bar and then we display all the lines. At this moment, it shows "X" lines of results.

If we change the research, afterwards, it will show only the first "X" lines and not all the lines as wanted.

**Example**  
https://live.bootstrap-table.com/code/support-whiteweb/7892

1. Write "11" in the search field and display all the lines, it displays 17 results
2. Empty the search field, it displays the 17 first results instead of 800 results

**Additional context**  
Chrome : 91.0.4472.77
Microsoft EDGE : 91.0.864.37 
Firefox : 85

**Comment by wenzhixin** [comment] 2021-06-04 07:31
I can't reproduce this bug.

**Comment by UtechtDustin** [comment] 2021-06-04 19:50
@wenzhixin i can reproduce the bug, maybe you are confused as I was about "display all the lines".
It's quite easy to reproduce:
- Search for `11`
- Change the page size to `all`
- Empty the search

**Comment by djhvscf** [comment] 2021-11-25 17:23
This is fixed with the latest version: https://live.bootstrap-table.com/code/djhvscf/9728

**Closed by djhvscf** 2021-11-25 17:23 UTC
Labels: confirmed, Bug
