### ISSUE TITLE
Change table page display error when table has fixed columns and sticky header

### ISSUE THREAD

**Issue by victorlks** [wenzhixin/bootstrap-table#6016] opened 2022-01-04 07:00 UTC
### Bootstraptable version(s) affected

1.19.1

### Description

When I change the number of pages in the table when there is a sticky header in the drop-down list, the sticky header of the fixed column on the right will change to the header of the non-fixed column on the left.

But it will resume after I scroll the page

you can try it on the online Editor.

1. enter the online editor
![image](https://user-images.githubusercontent.com/38172287/147551284-efe82049-2c79-4757-b02f-04438bd6887b.png)

2. click the libraries.
![image](https://user-images.githubusercontent.com/38172287/147551338-ae471992-5bf0-4785-8636-62ad471b48da.png)

3. select the extensions. (note: sticky header need before fixed columns)

4. click run, then do like the picture.
![image](https://user-images.githubusercontent.com/38172287/147553128-334f379e-92be-430d-b09a-665b4b09f867.png)

5. the right value "Cell 19"
![image](https://user-images.githubusercontent.com/38172287/147553313-295ffb24-99ac-4730-99a7-921e0593904f.png)

6. but when you scroll, the right value "Cell 19" will change to the wrong value "Cell 12".
![image](https://user-images.githubusercontent.com/38172287/147553458-ec1d2531-a0a0-4a65-843b-5a51a4dd246f.png)

**Comment by wenzhixin** [comment] 2022-05-09 00:34
Duplicate of #6002

**Closed by wenzhixin** 2022-05-09 00:34 UTC
Labels: Bug
