### ISSUE TITLE
有 Group Columns 时, Cookie 加载的标头会混乱, 该隐藏的父级标头没有隐藏

### ISSUE THREAD

**Issue by shenyubao** [wenzhixin/bootstrap-table#2333] opened 2016-06-01 09:34 UTC

**Comment by wenzhixin** [comment] 2016-06-01 11:49
提供下 jsfiddle 例子，
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by djhvscf** [comment] 2017-12-29 08:24
@
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR**. Thanks!

**Closed by djhvscf** 2017-12-29 08:24 UTC
Labels: awaiting reply, needs example
