### ISSUE TITLE
Undale to send parameter with custom json

### ISSUE THREAD

**Issue by DevNeeraj** [wenzhixin/bootstrap-table#2504] opened 2016-07-26 10:51 UTC
**When i am trying to send custom parameter, it is missing id parameter on sever side.**

```
gridParam: {
                    SearchText: $("#SearchText").val(),
                    Id: 1
                }

```

**But when i changed id with element then, server method receive the parameter**

```
gridParam: {
                    SearchText: $("#SearchText").val(),
                    Id: $("#Id").val()
                }

```

Is this limitation of bootstrap-table or i am missing something

**Comment by wenzhixin** [comment] 2016-07-29 00:07
I don't think so.
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by dabros** [comment] 2016-08-01 05:24
Please provide a Fiddle and we can help you more, dummy data from js array is fine (just needs to replicate core issue). If you need data url then see http://stackoverflow.com/questions/7194408/how-can-i-use-the-jsfiddle-echo-feature-with-jquery

Examples and guide provided below:
- https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports
- #1765

**Comment by djhvscf** [comment] 2017-12-29 08:16
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR**. Thanks!

**Closed by djhvscf** 2017-12-29 08:16 UTC
Labels: awaiting reply, help wanted
