### ISSUE TITLE
Fix can not read property 'field' of null based on master-dev 1.11.1

### ISSUE THREAD

**Issue by godcheese** [wenzhixin/bootstrap-table#3102] opened 2017-04-22 03:02 UTC
![bootstrap-table-bug](https://cloud.githubusercontent.com/assets/4585378/25300824/b76722be-274a-11e7-9d49-76bbbc96dceb.png)

Windows 7 sp1 x64 
Google Chrome 57
WAMPSERVER 3.0.6 64Bit
Laravel 5.4

jsfiddle fixed demo : https://jsfiddle.net/godcheese/xtwod2w1/
line numbers: 1274
```
// -
// value = value[props[prop_index]];

// +
value = value && value[props[prop_index]];
```

**Comment by martinburch** [comment] 2017-04-22 09:28
Could you post a fiddle showing the problem and include steps to reproduce?

I don't understand the bug.

**Comment by djhvscf** [comment] 2017-04-23 07:29
I'm not sure about the issue, can you do the things that @martinburch said? @godcheese

**Comment by shumacer** [comment] 2017-05-04 14:17
Hi.
It happened to me too.
I made a simple example: http://jsfiddle.net/shumacer/zwud0mqu/2/

When searching for "multiple-select" does not return anything (happens the error that the @godcheese  described)

**Comment by djhvscf** [comment] 2017-12-29 08:25
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR**. Thanks!

**Closed by djhvscf** 2017-12-29 08:25 UTC
Labels: awaiting reply
