### ISSUE TITLE
table appears to not respect theme from bootstrap.min.css

### ISSUE THREAD

**Issue by evanrich** [wenzhixin/bootstrap-table#868] opened 2015-05-12 22:17 UTC
I'd first like to say, thank you very much for providing this component, it was extremely easy to integrate into an internal tools page I'm working on for our support team.   I found what appears to be a problem though, although it could be entirely my fault in doing something wrong.

JSFiddle: http://jsfiddle.net/arm3bk2a/1/

The actual data source is a php file, but you get the idea.   The resulting table looks like this:
![table-cods](https://cloud.githubusercontent.com/assets/518320/7599759/b945d902-f8b9-11e4-9110-d5b89ed78bcd.png)

When I use a regular bootstrap table, it looks like this with the slate theme applied:
![table-bootstrap](https://cloud.githubusercontent.com/assets/518320/7599769/c9a83cae-f8b9-11e4-918c-dd09b88bfb22.PNG)

I'm using the slate theme from bootswatch.com

If i hit "refresh", the background behind the table flashes white as well, and I can see "Loading Data..." momentarily.

I've tried assigning different classes to the table to see if that fixes it, but nothing seems to change.  Am I doing something wrong?

**Comment by evanrich** [comment] 2015-05-13 15:14
Also, for what it's worth, I've already tried changing the order of the css includes, thinking that maybe the table one was taking precedence over the bootstrap one.  didn't make a difference

**Comment by djhvscf** [comment] 2015-05-13 15:45
Ok.. I'm checking it

**Comment by nicosalto** [comment] 2015-05-27 00:40
I have the same exact issue, did you found a solution for this ?

**Comment by evanrich** [comment] 2015-05-28 19:45
no solution  yet... I believe the issue is in the css for the table, looks like wenzhixin confirmed it.

**Comment by djhvscf** [comment] 2015-05-28 19:57
@evanrich see this: http://jsfiddle.net/djhvscf/arm3bk2a/2/

**Comment by djhvscf** [comment] 2015-05-28 20:01
if this is not a solution, reopen this issue again

**Comment by evanrich** [comment] 2015-05-28 20:09
that looks the same to me 

I sort of got around this by changing your css:

.fixed-table-container {
    position: relative;
    clear: both;
    border: 1px solid #dddddd;
    border-radius: 4px;
    -webkit-border-radius: 4px;
    -moz-border-radius: 4px;

to 

.fixed-table-container {
    position: relative;
    clear: both;
    border: 1px solid #000000;
    border-radius: 4px;
    -webkit-border-radius: 4px;
    -moz-border-radius: 4px;

That got  at least as far as the  border being black:
![image](https://cloud.githubusercontent.com/assets/518320/7869960/ca63551a-053a-11e5-961a-9fca10bd41ae.png)

**Comment by evanrich** [comment] 2015-05-28 20:14
Changing all #ddd's to #1c1e22 (the color code from the slate theme, using a CSS inspector) results in the correct look:
![image](https://cloud.githubusercontent.com/assets/518320/7870060/8182db58-053b-11e5-8c2d-2a51ffd6763b.png)

**Comment by djhvscf** [comment] 2015-05-28 20:28
The problem is that the boostrap.css  overwrite your changes

**Comment by evanrich** [comment] 2015-05-28 20:55
My order in code is as follows though:

        <link rel="stylesheet" href="../css/font-awesome.min.css">
        
        <link rel="stylesheet" href="../css/bootstrap-select.min.css">

        
        <link rel="stylesheet" href="../css/bootstrap-table.min.css">
        <link rel="stylesheet" href="../css/bootstrap.min.css">


shouldn't the bootstrap.min.css (the slate theme) take precidence over the bootstra-table.min.css though, since it's loaded last?

it looks like your .js file is referencing  '<div class="fixed-table-container">',, which is overriding the table format i specify.   I will fix this in additional css in my file to prevent future updates to bootstrap-table from messing this up.


^^ bootstrap-table.js  line 426

**Comment by evanrich** [comment] 2015-05-28 21:07
My solution: 

        <style>
            .fixed-table-container {
                border: 1px solid #1c1e22;
            }
            .fixed-table-header {
                border-bottom: 1px solid #1c1e22;
            }

            .fixed-table-footer {
                border-top: 1px solid #1c1e22;
            }

            .fixed-table-container thead th {
               border-left: 1px solid #1c1e22;
            }

            .fixed-table-container tbody td {
               border-left: 1px solid #1c1e22;
            }

            .bootstrap-table .table > thead > tr > th {
                border-bottom: 2px solid #1c1e22;
            }
        </style>

this formats the table as expected

**Comment by djhvscf** [comment] 2015-05-28 21:12
Ok, close this issue

**Closed by djhvscf** 2015-05-28 21:12 UTC
Labels: confirmed, css

**Comment by wenzhixin** [comment] 2015-05-28 22:51
Can add this problem to example repo, can you help to do a pull request @evanrich ?
