### ISSUE TITLE
BUG提交

### ISSUE THREAD

**Issue by 1103184133** [wenzhixin/bootstrap-table#2132] opened 2016-03-31 20:18 UTC
当detailView和reorderableColumns一起用的时候，拖动列后，表头会出现偏移，
chrome console log：
bootstrap-table.js:2256 Uncaught TypeError: Cannot read property 'visible' of undefined

**Comment by djhvscf** [comment] 2016-03-31 21:44
Can you translate this issue to english?

**Comment by 1103184133** [comment] 2016-04-01 05:42
I used both detailView and reorderableColumns at the same time,and some problem occured.
when i   draged the column,the table heading occured some wrong offset.
And the chrome console printed some message in red:
bootstrap-table.js:2256 Uncaught TypeError: Cannot read property 'visible' of undefined

Well,my english is poor.

**Comment by 1103184133** [comment] 2016-04-01 05:51
@djhvscf

**Comment by 1103184133** [comment] 2016-04-01 06:00
I‘ve tried my best to handle this problem with my low skill level with jquery but failed.
Do you have some advise for my jquery learning?? Thx.

**Comment by wenzhixin** [comment] 2016-04-06 14:09
能否提供 jsfiddle？

**Comment by wenzhixin** [comment] 2016-05-17 07:45
Close this issue because there is no any response in 7 days, if the problem exists reopen it and provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports), thanks!

**Comment by javieerrubio11** [comment] 2016-06-23 11:04
Hi,

I have the same error, when you use reorderableColumns and detailView, It produces errors.

[Example jsfiddle](https://jsfiddle.net/javierIntegra/gn78ozxh/11/)

In order to reproduce the error, you have to reorder some column and after that, you tray to order one column asc or desc.

Furthermore, I opened this issue some days ago, [issue](https://github.com/wenzhixin/bootstrap-table/issues/2383), and I try to explain the issue better with the example.I want that you can't reorder the first column for example, I don't know if it's is possible.

Thanks for all.

**Comment by camj256** [comment] 2016-11-09 23:41
Yeah, I get the same issue. Anyone ever figure this out.

**Comment by pozuelog** [comment] 2017-02-10 12:49
Issue is affecting me also. I'm trying to solve it by changing the way that reorder-columns extension reset data-field, but I'm not having success.

Did you find any solution?

**Comment by djhvscf** [comment] 2017-02-10 18:33
Same as #2132

**Comment by pozuelog** [comment] 2017-02-13 07:47
@djhvscf : @javieerrubio11  has put a link to an example here:

[Example jsfiddle](https://jsfiddle.net/javierIntegra/gn78ozxh/11/)

**Comment by UtechtDustin** [comment] 2019-04-26 00:42
I close this issue because its already 2 Years old, if the issue is still not fixed please reopen the issue.

**Closed by UtechtDustin** 2019-04-26 00:42 UTC
Labels: js, reorder-columns
