### ISSUE TITLE
while using fixed columns check box not working..

### ISSUE THREAD

**Issue by skumarfaruk** [wenzhixin/bootstrap-table#2001] opened 2016-02-17 10:56 UTC
While using fixed columns checkbox click event check.bs.table not working..
Please tell me how to fix it..
https://jsfiddle.net/e211v99k/12/

**Comment by dabros** [comment] 2016-02-17 23:35
@skumarfaruk - very easy to see when you look at generated html

Hit F12 then inspect elements, you will see that original "#table" is now inside `fixed-table-body`, but your fixed columns are inside a DIFFERENT table in `fixed-table-body-columns`.

This may seem odd, but the extension code itself accounts for this quite well.

I will look into this more when i get chance, likely just overriding/extending handler similar to how it handles similar cases.

https://github.com/wenzhixin/bootstrap-table-fixed-columns/blob/master/bootstrap-table-fixed-columns.js

Feel free to have a go at it yourself though, shouldnt be difficult

Take a look at #1952, which stalled atm so maybe can help create fiddle there for me to proceed (and rule out possible bug with table from html + fixed-columns)

**Comment by dabros** [comment] 2016-02-19 04:00
Not much time to look at it myself, but as a starter i tried something like this: 

```javascript

<div id="wrap">
... other html from fiddle ...
</div>

...

$(function () {
    console.log($("#wrap table"))
    $("#wrap table").each(function(ind,table){
			console.log(table)
    	$(table).on('check.bs.table', function (e, row) {
         alert('test');
      });
    });
});
```

The failure of that leads me to think that handler to trigger check event never attatched to fixed-table-columns, which appears to be this or something similar: https://github.com/wenzhixin/bootstrap-table/blob/master/src/bootstrap-table.js#L1706


`initBody` does have an override/extension in fixed table extension (https://github.com/wenzhixin/bootstrap-table-fixed-columns/blob/master/bootstrap-table-fixed-columns.js#L61) so the solution would seem to be adding comparable code that calls simliar or same code, substituting `this.$body` for `that.$fixedBody`.

Might be a more elegant solution that just replacing, but fixed-table seems to force this duplication with its overall approach - not first issue related to it.

Makes change overhead harder, unless someone can think of elegant way to segment out code to avoid over-duplication.

Not much time atm to solve this, but this should be more than enough for anyone else to follow up on

**Comment by skumarfaruk** [comment] 2016-02-19 10:01
i didn't get you unable to fix the issue, can any one please help me.

**Comment by dabros** [comment] 2016-02-25 03:59
@wenzhixin @djhvscf - any comment or thoughts on why the code reads like it should be working?

maybe we just need a deep copy, but i would have thought it actually everything plus handlers, the way it read.

**Comment by djhvscf** [comment] 2016-02-25 04:45
@dabros the problem is that in the source code we are not binding the click event to the fixed columns so because of that we can't fired the check event.. See this example and I hope you can help us to create a **PR** with a solution.. I think it is not complicated.

https://jsfiddle.net/djhvscf/e211v99k/14/

**Comment by djhvscf** [comment] 2016-02-25 04:45
Let me know if you need more explanation @dabros

**Comment by skumarfaruk** [comment] 2016-02-25 06:23
ok, but how to get row data using this?

**Comment by djhvscf** [comment] 2016-02-25 06:44
In this way https://jsfiddle.net/djhvscf/e211v99k/15/ but @skumarfaruk remember that this approach is not an official solution

**Comment by dabros** [comment] 2016-02-26 05:22
@djhvscf - that was my first thought, but i dont think thats right.

See my ommited/strikethrough text above

```

**Comment by dabros** [comment] 2016-02-26 05:27
@djhvscf - that was my first thought, but i dont think thats right.

See my ommited/strikethrough text above.

The reason i changed my thoughts is the following line:

```javascript
BootstrapTable.prototype.initBody = function () {
    _initBody.apply(this, Array.prototype.slice.apply(arguments));
```

That is around https://github.com/wenzhixin/bootstrap-table-fixed-columns/blob/master/bootstrap-table-fixed-columns.js#L61

Yet we already saw that the selectevent was added to the checkbox, my console.log and breakpoints in proved that: https://github.com/wenzhixin/bootstrap-table/blob/master/src/bootstrap-table.js#L1706

So if the base `initBody` is called and finishes executing first, THEN fixed-columns `initBody`, the select handler should be already set.

So when we do this: https://github.com/wenzhixin/bootstrap-table-fixed-columns/blob/master/bootstrap-table-fixed-columns.js#L82, my thought is that the `.clone()` issnt cloning event handlers for that.

And if we look at https://api.jquery.com/clone/ we see it does state deep copy, but also has an optional param:

> withDataAndEvents (default: false)
> Type: Boolean
> A Boolean indicating whether event handlers should be copied along with the elements. As of jQuery 1.4, element data will be copied as well.

So that is most likely the issue.

I will do up fiddle later showing this, but late in day so post yourself if you want and nothing from me yet.

**Comment by djhvscf** [comment] 2016-02-26 05:52
@dabros it sounds like a solution.. can you provide a example with that modification??

**Comment by dabros** [comment] 2016-02-26 05:55
So that didnt get anywhere

I still think my reading was correct, but just changing clone param wasnt enough.

I made this fiddle and in comments referanced lines to look for my debug or changes

`this.$selectItem` does stay set, see console in my fiddle, but events still dont seem to trigger.

Maybe im missing something simple, or the clone with events just isnt enough.

In any case, you could prob get it working by keeping simple clone and reapllying events

In this case id make the click handler function a util or similar inside boostrap table, and assign it again with a variation of https://github.com/wenzhixin/bootstrap-table/blob/master/src/bootstrap-table.js#L1706 inside fixed-columns `initBody`, substituting `this.$body` with `this.$fixedBody`

Im still not happy though, as logically the event handler should have been copied across...

https://jsfiddle.net/dabros/f79k6ob2/1/

**Comment by dabros** [comment] 2016-02-26 08:40
Tried debugging to list all attached event listeners, doesnt seem to want to show any though

https://jsfiddle.net/dabros/f79k6ob2/3/

gone for weekend, anyone else pls follow up if thoughts

**Comment by jonathangreco** [comment] 2018-02-06 11:41
+1 this problem is annoying.

**Comment by wenzhixin** [comment] 2019-03-13 01:06
Added new version fixed-columns extension: https://github.com/wenzhixin/bootstrap-table/commit/91977960a5705cd074067b2670483b5e9d5c1f44
Develop example: http://dev.bootstrap-table.com/examples/#extensions/fixed-columns.html

**Closed by wenzhixin** 2019-03-13 01:06 UTC
Labels: confirmed, fixed-columns, js

**Comment by jsilverio** [comment] 2020-05-08 01:25
Here's a quick and effective way to fix this. Add a click listener for the fixed columns body cell similar to what initBody has. Once you get the cell clicked find the cell using the row and cell index and trigger the same event.  This code block is on the initColumnsFixed or wherever you initialize it.

            this.$fixedBody = $fixedColumns.find('.fixed-table-body');

            this.$fixedBody.find('table > tbody > tr[data-index] > td').off('click dblclick').on('click dblclick', function (e) {
                var $td = $(this);
                var $tr = $td.parent();
                //find the cell in the main table and trigger the same event
                var $tr2 = $(that.$body.find('> tr[data-index]')[$tr.data('index')]);
                var $td2 = $($tr2.children()[$td.index()]);
                $td2.trigger(e);  
            });

**Comment by wenzhixin** [comment] 2020-05-14 14:36
@jsilverio Can you provide an [Online Example](https://live.bootstrap-table.com) to show your problem?
