### ISSUE TITLE
V1.13.3 - Error Show/Hide column with Cookie extension: Cannot set property 'visible' of undefined

### ISSUE THREAD

**Issue by manukieli** [wenzhixin/bootstrap-table#4145] opened 2019-01-29 08:54 UTC
I'm using the version 1.13.3
And I'm using the Cookie extension because in some table I need it, but in other no.
If I try to hide some column into the table, it return me this error:
![image](https://user-images.githubusercontent.com/14294794/51895585-d109be80-23aa-11e9-8728-f74de588eeb5.png)

You can see it here:
![error_cookie_extension](https://user-images.githubusercontent.com/14294794/51896009-d4517a00-23ab-11e9-870f-c9f26f8a28fd.gif)

The link of the example is here:
https://jsfiddle.net/7ofnd1s2/9

Thank you for your help.

**Comment by wenzhixin** [comment] 2019-01-29 09:41
Duplicate of #4141

**Closed by wenzhixin** 2019-01-29 09:41 UTC
