### ISSUE TITLE
cell selector

### ISSUE THREAD

**Issue by 4meck** [wenzhixin/bootstrap-table#3232] opened 2017-06-27 13:21 UTC
Hi,

file bootstrap-table.js

BootstrapTable.prototype.initTable = function () {

please change line 698
$(this).find('>td').each(function (x) {
to 
$(this).find('>td,th').each(function (x) {

Nice work!

**Comment by djhvscf** [comment] 2017-06-28 06:34
Can you explain us why that change?

**Comment by 4meck** [comment] 2017-06-28 11:23
<tr><th>Label</th>
<td>Value</td>
</tr>

without find th column Label not show

**Comment by djhvscf** [comment] 2017-12-29 01:14
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by djhvscf** [comment] 2018-01-29 05:45
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR** with an [example](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports). Thanks!

**Closed by djhvscf** 2018-01-29 05:45 UTC
Labels: awaiting reply, needs example
