### ISSUE TITLE
updateRow with active filter

### ISSUE THREAD

**Issue by filipesrosa** [wenzhixin/bootstrap-table#2723] opened 2016-10-21 03:41 UTC
An error is thrown when I update a row and apply a filter. `Cannot read property _data of undefined`.

On `initBody()` function, line 1584, we have `data = this.getData();` 
By changing to `data = this.getOptions().data;` no error is thrown.

Is there any other way to solve the problem?

**Comment by filipesrosa** [comment] 2016-10-21 10:45
@wenzhixin Usually the question is "Can I keep this way? Is it supported?" Thanks!

**Comment by wenzhixin** [comment] 2017-02-21 15:54
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by djhvscf** [comment] 2018-01-29 05:53
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR** with an [example](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports). Thanks!

**Closed by djhvscf** 2018-01-29 05:53 UTC
Labels: needs example
