### ISSUE TITLE
Filter Control: search mix filters from one table into the other

### ISSUE THREAD

**Issue by francogp** [wenzhixin/bootstrap-table#6269] opened 2022-07-14 16:25 UTC
### Bootstraptable version(s) affected

1.20.2

### Description

If you use 2 tables, trying to filter one table affects the other table, with lots of glitches.

### Example(s)

https://live.bootstrap-table.com/code/francogp/12312

### Possible Solutions

contain the search to a single table, not all tables

**Comment by djhvscf** [comment] 2022-08-02 22:42
It works as expected for me. I can't reproduce the problem @francogp

**Comment by francogp** [comment] 2022-08-02 22:47
> It works as expected for me. I can't reproduce the problem @francogp

they seems to patch the online editor, now it seems to work online, but not in the released version 1.20.2

**Comment by djhvscf** [comment] 2022-08-02 22:55
Oh! Got it! I was able to reproduce it.

**Comment by UtechtDustin** [comment] 2022-08-03 07:22
Could be fixed with PR #6300.
I can't reproduce it in the develop branch, couold please test it @francogp ?
Example: https://live.bootstrap-table.com/code/UtechtDustin/12315

**Comment by UtechtDustin** [comment] 2022-08-03 09:59
Strange, i can't reproduce 1.   
I canload the page and/or run the example as often i want, both tables load the correct data from the cookies.
Maybe a cache issue ? @wenzhixin could you try to fix the cache issues with older commit's ?

2. I have to write really really quick to reproduce it.

**Comment by francogp** [comment] 2022-08-03 10:03
> I canload the page and/or run the example as often i want, both tables load the correct data from the cookies. Maybe a cache issue ? @wenzhixin could you try to fix the cache issues with older commit's ?
> 
> 2.I have to write really really quick to reproduce it.

1. If I open the example on a Incognito mode, it seems to load fine. Maybe It's a cache issue

**Comment by francogp** [comment] 2022-09-28 21:48
seems to be fixed

**Comment by UtechtDustin** [comment] 2022-09-29 07:16
Good to know, thanks!

**Closed by UtechtDustin** 2022-09-29 07:16 UTC
Labels: confirmed, cookie, Bug
