### ISSUE TITLE
Clicking on pagenumber '...' and then '<' or '>' results in no result and Nan in pagenumber

### ISSUE THREAD

**Issue by GeertsBart** [wenzhixin/bootstrap-table#4096] opened 2019-01-02 13:53 UTC
if you have multiple pages a button '..'. appears in the horizontal pagenumber list

Clicking on pagenumber '...' and then '<' or '>' results in no result and Nan in pagenumber

after this, you need to refresh the page to get the contents and pagination back

the pagenumber '...' is still clickable this need to be changes in onPageNumber event

**Comment by djhvscf** [comment] 2019-01-02 15:15
This is resolved in this pull request https://github.com/wenzhixin/bootstrap-table/pull/4094

**Comment by jsvptf** [comment] 2019-03-13 14:50
this problem is present on 2019-03-13  v1.13.5

**Comment by Falseee** [comment] 2019-03-26 19:12
Cant reproduce the error on 1.14.2 ([demo](http://jsfiddle.net/nvm45s3w/2/)).
But i nevertheless removed the binding for the page seperator (PR).

**Comment by wenzhixin** [comment] 2019-03-26 22:55
Merged.

**Closed by wenzhixin** 2019-03-26 22:55 UTC
