### ISSUE TITLE
Data-filter-default is always reset to the default value after selection

### ISSUE THREAD

**Issue by sdespont** [wenzhixin/bootstrap-table#6110] opened 2022-04-25 06:29 UTC
### Bootstraptable version(s) affected

1.20.0

### Description

When the data comes from `server side` and using plugin `bootstrap-table-filter-control` with `data-filter-control="select"`,  the `data-filter-default="Item 0"` is always reset to the default value after any options selection.

![screen-recording-2022-04-25-08 3A26](https://user-images.githubusercontent.com/646632/165032811-1e9a02a7-8170-4ce9-a684-b9e9dfe03b46.gif)

### Example(s)

https://live.bootstrap-table.com/code/sdespont/11312

### Additional Context

_No response_[](url)

**Comment by sdespont** [comment] 2022-04-25 06:36
@djhvscf I didn't see this issue before upgrading this morning... really sorry

**Comment by coshlo** [comment] 2022-04-28 10:08
I have a similar issue on my table. When an option is selected in the dropdown, the table filters correctly and updates but then the selected option disappears from the select control box.

I am using server side data as above.

I traced the error to the `createControls(this, getControlContainer(this))` call from the `load(data)` function in file `bootstrap-table-filter-control.js - line 2829`. 

In the `createControls()` function line 2473, the method call `$th.find('.filter-control').remove()` removes the control input and `$th.find('.fht-cell').html(html.join(''))` shows it again but without the user selected option.

This bug appears with or without the `data-filter-default` option included in the above posted example.

**Comment by djhvscf** [comment] 2022-04-29 03:57
Thanks @sdespont . @coshlo can you create a new issue and provide an example?

**Comment by sdespont** [comment] 2022-04-29 05:57
@coshlo I can't reproduce your problem too

**Comment by coshlo** [comment] 2022-05-01 15:01
> Thanks @sdespont . @coshlo can you create a new issue and provide an example?

> @coshlo I can't reproduce your problem too

New issue and example opened... [#6125](https://github.com/wenzhixin/bootstrap-table/issues/6125)

**Comment by sdespont** [comment] 2022-06-28 18:44
@djhvscf any idea about this one? I would try to provide a PR if you give me a hint where to find the bug

The bug is still present in the develop branch : https://live.bootstrap-table.com/code/sdespont/11872

**Comment by UtechtDustin** [comment] 2022-07-30 13:44
@sdespont 
Could you create a video/gif or provide us some more information ?
I can't reproduce it with your example/with the develop branch.
If i select `Item 1` for the `Item Name` column it will not be resettet to `Item 0`.
Is this issue maybe already fixed ? :-)

**Comment by UtechtDustin** [comment] 2022-07-30 13:46
Seems fixed by #6203, if someone think this bug is not fixed in the develop branch please provide us some information and we will reopen the issue.

**Closed by UtechtDustin** 2022-07-30 13:46 UTC
Labels: confirmed, filter-control, Bug

**Comment by sdespont** [comment] 2022-08-09 07:48
@UtechtDustin Sorry for the late answer, I was in vacation.

In the develop branch, the value is now not reseted as discussed above, but the behavior is not correct.


There is 2 bugs you can view in this example https://live.bootstrap-table.com/code/sdespont/12381

1. When selecting "Item 1", the first line is containing "Item 2" and should not be filtered. I suspect that this problem comes from the select choice identifier in the JSON array `2: "Item 1"`. In fact, sometimes the value "type" in the URL is containing the text and sometimes the value, i.e. "2" or "Item 1"
2. After selecting "Item 1", selecting "Item 0" is displaying wrong results containing "Item 1". Cache problem?

![screen-recording-2022-08-09-09_37](https://user-images.githubusercontent.com/646632/183592826-0ff6b932-245f-4510-bade-815f9dad473c.gif)

Let me know if you need more details or examples

**Comment by UtechtDustin** [comment] 2022-08-09 07:53
Thank you for the answer.
But for me your example works as designed.
The example uses the option `filterData` which modifies the select data in this case 
```
{
    1: "Item 0",
    2: "Item 1"
}
```
Which means we show option `Item 0` and `Item 1` with the search data of `1` and `2`.
That is the reason why you see `Item 1` if you select `Item 0`, the table will search for `1`.
If you fix the choices e.g.:
```
{
    "Item 0": "Item 0",
    "Item 1": "Item 1"
}
```

It works fine, here is an example: https://live.bootstrap-table.com/code/UtechtDustin/12382

**Comment by sdespont** [comment] 2022-08-09 08:00
@UtechtDustin Thanks for the quick answer.

It makes sense and I have updated my example. https://live.bootstrap-table.com/code/sdespont/12383

The second problem is that the rows are not filtered when the value in the select boy in not the defaulte one and another field is used like this

![screen-recording-2022-08-09-09_37 (1)](https://user-images.githubusercontent.com/646632/183596208-f4f11be8-5309-4333-a50e-7315ba96d1a9.gif)

**Comment by UtechtDustin** [comment] 2022-08-09 08:32
You're right it's a bug (related to. `filterDefault`), could you please open a new issue for that ?

**Comment by sdespont** [comment] 2022-08-09 08:44
New issue : https://github.com/wenzhixin/bootstrap-table/issues/6324
