### ISSUE TITLE
Add extra attribute to be sent in filter

### ISSUE THREAD

**Issue by anujism** [wenzhixin/bootstrap-table#2425] opened 2016-07-03 08:50 UTC
Please add a extra attribute to be sent to filter. For e.g. `data-filter-name`.

`<th data-field='abc' data-filter-name='abc_contains'>`

Currently when the server is hit a parameter is passed with the dictionary of filter fields.
`filter={"abc":"value"}`

I would like to send `filter={"abc_contains":"value"}` if `data-filter-name` exists otherwise it should work as it is.

Thanks,
Anuj

**Comment by wenzhixin** [comment] 2016-07-03 09:15
Can you use `queryParams`?

**Comment by anujism** [comment] 2016-07-03 10:53
`queryParams` is in addition to extra filters so if I use `queryParams`, it will still be there in filter fields.

BTW, I have changed the code to make it work. Can you please check if this can be included?

```
BootstrapTable.prototype.onColumnSearch = function (event) {
        var valid =
        (event.keyCode > 47 && event.keyCode < 58)   || // number keys
        event.keyCode == 32 || event.keyCode == 13   ||  // spacebar & return key(s) (if you want to allow carriage returns) also backspace
        event.keyCode == 8 || event.keyCode == 46   ||  // backspace and delete
        (event.keyCode > 64 && event.keyCode < 91)   || // letter keys
        (event.keyCode > 95 && event.keyCode < 112)  || // numpad keys
        (event.keyCode > 185 && event.keyCode < 193) || // ;=,-./` (in order)
        (event.keyCode > 218 && event.keyCode < 223);

        if ($.inArray(event.keyCode, [37, 38, 39, 40]) > -1 || !valid) {
            return;
        }

        copyValues(this);
        var text = $.trim($(event.currentTarget).val());
        var $fieldTh = $(event.currentTarget).closest('[data-field]');
        var $field = $fieldTh.data('filter-name');
        if(!$field) {
            $field = $fieldTh.data('field');
        }

        if ($.isEmptyObject(this.filterColumnsPartial)) {
            this.filterColumnsPartial = {};
        }
        if (text) {
            this.filterColumnsPartial[$field] = text;
        } else {
            delete this.filterColumnsPartial[$field];
        }

        // if the searchText is the same as the previously selected column value,
        // bootstrapTable will not try searching again (even though the selected column
        // may be different from the previous search).  As a work around
        // we're manually appending some text to bootrap's searchText field
        // to guarantee that it will perform a search again when we call this.onSearch(event)
        this.searchText += "randomText";

        this.options.pageNumber = 1;
        this.onSearch(event);
        this.trigger('column-search', $field, text);
    };
```

**Comment by djhvscf** [comment] 2016-07-10 18:11
@anujism Can you create a new PR with an example? Please

**Comment by djhvscf** [comment] 2018-01-29 05:55
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR** with an [example](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports). Thanks!

**Closed by djhvscf** 2018-01-29 05:55 UTC
Labels: filter-control, needs example
