### ISSUE TITLE
Converting circular structure to JSON

### ISSUE THREAD

**Issue by zsf513** [wenzhixin/bootstrap-table#4265] opened 2019-04-01 10:29 UTC
![image](https://user-images.githubusercontent.com/4221354/55321379-1716f780-54ac-11e9-97e5-ea71da8c368e.png)

**Comment by zsf513** [comment] 2019-04-01 10:34
delete options.data;
var options = JSON.parse(JSON.stringify(this.options));

**Comment by wenzhixin** [comment] 2019-04-02 00:25
Duplicate of #4254

**Closed by wenzhixin** 2019-04-02 00:25 UTC
