### ISSUE TITLE
any event is triggered after all rows are added to the table?

### ISSUE THREAD

**Issue by mehere** [wenzhixin/bootstrap-table#832] opened 2015-05-02 16:15 UTC
I see 'onPostBody' event is triggered after the table is added to the DOM but not rows inside the table. Can we have event to be triggered after all rows are added to the table?

The reason why we need this event is for lazy load. Please advise if there is any existing way to load data later after the whole table and rows are rendered. Thanks.

**Comment by djhvscf** [comment] 2015-05-09 01:58
You can use the onAll event to do that.. or the pre-rows /post-rows events (these events will be include in the next release..

see this: http://jsfiddle.net/djhvscf/e3nk137y/1487/

**Comment by mehere** [comment] 2015-05-13 15:23
Cool thanks

**Closed** 2015-05-17 23:47 UTC
Labels: feature

**Comment by wenzhixin** [comment] 2015-05-21 03:04
This event seems unnecessary, `onPostBody` event is fired after this event.

**Comment by mehere** [comment] 2015-05-24 07:28
@wenzhixin in the previous release, 'onPostBody' is fired after data is loaded but before rows are added to the table. 'onPostRows' is necessary

**Comment by wenzhixin** [comment] 2015-05-24 14:43
Can you show a jsFiddle @mehere ?

**Comment by mehere** [comment] 2015-05-26 14:35
@wenzhixin here we go:
http://jsfiddle.net/mehere/92626nav/1/

you can see that 'post-body' is triggered multiple times and none of events show that rows are added to the table: in the alert, only has table header but no table body

**Comment by wenzhixin** [comment] 2015-05-26 15:51
You use with a wrong way @mehere :

1. `$(this).find('tr')` return an jQuery array, `$(this).find('tr').html()` just show the first element's html.
2. `on('post-body.bs.table')` is the same width `onPostBody` option.
3. The jsFiddle alert twice and the first time return `no macthing records found` is because there are two request(OPTIONS + GET, not a bug) in jsFiddle.

Updated: http://jsfiddle.net/92626nav/2/

**Comment by mehere** [comment] 2015-05-28 12:42
@wenzhixin 
thanks for explaining point 3
so how to restrict to one request? i have the same issue on my local host

**Comment by joefreire** [comment] 2017-01-18 14:32
I need use this after $table.bootstrapTable('append', data); how i can do that?
