### ISSUE TITLE
in 'events' column option the event name must contain space

### ISSUE THREAD

**Issue by seggev319** [wenzhixin/bootstrap-table#3097] opened 2017-04-20 17:25 UTC
In dist/bootstrap-table.js @ line 1942 (under the `BootstrapTable.prototype.initBody` function), each event from the 'events' column option is broken down into a jQuery event name and a selector based on the space seperating them.

The problem is if I dont want to include a selector.
So, if my 'events' option looks like this: `events: { click: function (evt, value, row, index) { ... } }`,
the event name will be considered an empty string and the selector will be 'click', so I have to include an unnecessary space and quotes:  `events: { 'click ': ... }`.

This isnt a problem to get around, but it did take me a good while to find the reason.
Please look into this.

**Comment by seggev319** [comment] 2017-04-21 11:00
There's actually a whole different issue.
Because of the 'find' function on line 1946:
```javascript
$td.find(el).off(name).on(name, function (e) { //...
```
I can never apply an event to the cell itself, only some descendant elements of it.
So, I suggest the following:
Replace
```javascript
for (var key in events) {
    that.$body.find('>tr:not(.no-records-found)').each(function () {
        var $tr = $(this),
            $td = $tr.find(that.options.cardView ? '.card-view' : 'td').eq(fieldIndex),
            index = key.indexOf(' '),
            name = key.substring(0, index),
            el = key.substring(index + 1),
            func = events[key];

        $td.find(el).off(name).on(name, function (e) {
            var index = $tr.data('index'),
                row = that.data[index],
                value = row[field];

            func.apply(this, [e, value, row, index]);
        });
    });
}
```
with
```javascript
for (var key in events) {
    that.$body.find('>tr:not(.no-records-found)').each(function () {
        var $tr = $(this),
        $td = $tr.find(that.options.cardView ? '.card-view' : 'td').eq(fieldIndex),
            keyParts = key.split(' '),
            name = keyParts.shift(),
            el = keyParts.join(' '),
            func = events[key];

        // use 'el' to filter the cell and its descendant elements
        // ONLY if it contains more than just spaces.
        // Otherwise, attach event to the cell itself.
        (el.match(/[^\s]+/g) !== null ? $td.find(el).addBack(el) : $td).off(name).on(name, function (e) {
            var index = $tr.data('index'),
                row = that.data[index],
                value = row[field];

            func.apply(this, [e, value, row, index]);
        });
    });
}
```

**Comment by djhvscf** [comment] 2017-04-23 07:44
@seggev319 can you create a fiddle in order to see your code?

**Comment by djhvscf** [comment] 2018-01-29 05:47
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR** with an [example](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports). Thanks!

**Closed by djhvscf** 2018-01-29 05:47 UTC
Labels: needs example
