### ISSUE TITLE
切换显示列，导出export等功能时，按钮点击失效

### ISSUE THREAD

**Issue by apple5702** [wenzhixin/bootstrap-table#3060] opened 2017-03-31 10:15 UTC
相同界面采用<div class="main"/>,$(".main").empty().load(URL),动态渲染div内容时，多次执行该代码之后，会出现新渲染的表格，显示隐藏列功能不可点击，导出export点击之后，页面整个被遮罩，很久没有响应。需要作者帮助

**Comment by wenzhixin** [comment] 2018-01-07 14:48
请提供 [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports)，谢谢!

**Comment by djhvscf** [comment] 2018-01-29 05:47
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR** with an [example](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports). Thanks!

**Closed by djhvscf** 2018-01-29 05:47 UTC
Labels: awaiting reply, needs example
