### ISSUE TITLE
Filtering (if we delete one filtering column and it isn't confirmed by enter -> filter conditions are not changed)

### ISSUE THREAD

**Issue by doupov** [wenzhixin/bootstrap-table#5987] opened 2021-12-08 21:42 UTC
https://user-images.githubusercontent.com/9618521/146459819-eab5d7c1-59b6-4de0-9749-860ccda1b41c.mov

### Description

Filtering (if we delete one filtering column and it isn't confirmed by enter -> filter conditions are not changed)
I using table-filter-control
My configuration
data-side-pagination="server"
data-search-on-enter-key="true"
Is possible send request to server on enter key all filters?

**Comment by wenzhixin** [comment] 2022-03-13 01:02
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem. Thanks!

**Comment by UtechtDustin** [comment] 2022-05-13 21:07
I'm closing this issue, because we got no example from you.
Also i can't reproduce the issue, its working fine for me (see the video).
If you still need help with this, please let us know.

https://user-images.githubusercontent.com/13292481/168389652-463c8356-0d84-4189-85ef-56e080605343.mp4

**Closed by UtechtDustin** 2022-05-13 21:07 UTC
Labels: help-wanted, needs example
