### ISSUE TITLE
How to use data-ajax-options with using the ajaxRequest 

### ISSUE THREAD

**Issue by emclab** [wenzhixin/bootstrap-table#3101] opened 2017-04-21 12:54 UTC
This is more about how I can use the "data-ajax-options" with ajaxRequest call. Below is what I tried, but on the ajaxRequest javascript function, I see this ajax-options as an array of single character (like "[","o","p","t",","i","o","n","1",",","o","p","t","i","o","n","2",]"  ) . Below is my example.  Thanks for your help

<table id="table"  data-toggle="table" data-ajax="ajaxTableRequest" data-url="<url>", 
                              data-ajax-options="**[option1, option2]**">
          <thead>
              <tr>
                   <th data-field="1">Status</th>
                   <th data-field="2">Total</th>
              </tr>
           </thead>
</table>

function ajaxTableRequest(params) {
    var data = [];
    var url = params.data-url;
    options = params.ajax-options
    jQuery.getJSON(url, (function(options) {
      ......
        }(options) 
    );

**Comment by djhvscf** [comment] 2017-04-23 07:38
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by wenzhixin** [comment] 2017-12-22 00:34
Duplicate of #3483

**Closed by wenzhixin** 2017-12-22 00:34 UTC
Labels: awaiting reply, needs example
