### ISSUE TITLE
Wrap the bigger text inside the column

### ISSUE THREAD

**Issue by rajeshbtlit** [wenzhixin/bootstrap-table#2419] opened 2016-06-30 14:11 UTC
Hi,
Thanks for the framework, really appreciate it.

When the value inside column is very big , need a way to wrap the text inside the column, could you please help with this ?

I tried date formatter but no luck 

Thanks,

**Comment by dabros** [comment] 2016-07-01 04:28
@rajeshbtlit - try searching more next time and taking a step back first. Is simple table css, nothing to do with bootstrap-table itself, so remove that from your mind and always focus on simplest solution first

Also already been answered here: #2281 

https://github.com/wenzhixin/bootstrap-table/issues?utf8=%E2%9C%93&q=is%3Aissue%20wrap

**Comment by rajeshbtlit** [comment] 2016-07-04 14:08
Thanks dabros,

i tired that but looks like am not able to format it.

my table column is defined as below:
 
`<th data-field="wfdName" data-sortable="true" data-class="tdclass">Workflow Name</th>`

and i have a css defined as `tdclass {
    word-break: break-word;
}`

**Comment by dabros** [comment] 2016-07-04 23:30
@rajeshbtlit - what is "is not formatting"?

Please provide a Fiddle and we can help you more, examples and guide provided below

https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports
#1765

**Comment by djhvscf** [comment] 2017-12-29 08:18
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR**. Thanks!

**Closed by djhvscf** 2017-12-29 08:18 UTC
Labels: awaiting reply, help wanted
