### ISSUE TITLE
Header and footer duplicated when going back a page when using rails turbolink

### ISSUE THREAD

**Issue by rssluca** [wenzhixin/bootstrap-table#3307] opened 2017-08-10 08:35 UTC
Hello,
I was having a lot of fun until I hit this one up:). 

This happens on my rails app only when I go back to the table's page. 

Turbolinks seems to be the problem.

![image](https://user-images.githubusercontent.com/11591556/29161065-1f62138e-7df8-11e7-805a-b1e8449d5db0.png)

Both header (search row) and footer (pagination links row) keep multiplying (see below) each time I go forth and then again back, until I actually either refresh or access the table page via its link.

![image](https://user-images.githubusercontent.com/11591556/29161908-40fa9d74-7dfb-11e7-85fc-ce50ff464e67.png)

Thank you so much for this fantastic work!!!

Luca

**Comment by rssluca** [comment] 2017-08-10 11:42
Did the testing. Turns out rails turbolinks is messing with it :(

**Comment by wenzhixin** [comment] 2017-12-17 06:10
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by djhvscf** [comment] 2017-12-29 01:06
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR**. Thanks!

**Closed by djhvscf** 2017-12-29 01:06 UTC
Labels: awaiting reply, needs example

**Comment by Bighamster** [comment] 2018-02-20 12:51
Don't forget to destroy BT before caching:

```
$(document).on("turbolinks:before-cache", function() {

    $('[data-toggle="table"]').bootstrapTable('destroy');

});
```

**Comment by martinbarilik** [comment] 2020-10-01 11:21
@Bighamster The trigger won't be fired if you press F5 :-/ or if you redirect_to in controller to the same page
