### ISSUE TITLE
datetimepicker pre set value

### ISSUE THREAD

**Issue by soni88** [wenzhixin/bootstrap-table#3096] opened 2017-04-20 08:49 UTC
Hello ,
 I have two table that take the Date as input ( designed with bootstrap datetimepicker , the two date input are linked with each other ) and then load the data from a remote server when the second datetimepicker change.

My question is this , how can I take the choosen first and second Date when I click on a cell/row link on the first table from the first table and put them as input Date automatically on the second table so the data can be loaded ??

**Comment by djhvscf** [comment] 2017-04-23 07:58
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by djhvscf** [comment] 2017-12-29 08:24
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR**. Thanks!

**Closed by djhvscf** 2017-12-29 08:24 UTC
Labels: awaiting reply, needs example
