### ISSUE TITLE
stop search on filtering

### ISSUE THREAD

**Issue by Megido6** [wenzhixin/bootstrap-table#2873] opened 2017-01-22 19:56 UTC
i have filter

```
<select class="m form-control" style="width: 100%; visibility: visible">
    <option value=""></option>
   <option value="1">--- Count>0 ---</option
   <option value="0">--- count = 0 ---</option></select>

```
table:

```
id|name|images_count
1|xxxxxx| 1
2|xxxxxx| 56
3|xxxxxx| 46
4|xxxxxx| 89
5|xxxxxx| 0
```

if i select option Count>0  i see  only row with  count = 1.
and if i select option Count=0  i see  only row with count = 0

server return me correct filtered json
WTF?

**Comment by djhvscf** [comment] 2017-02-02 21:03
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by djhvscf** [comment] 2017-06-19 06:17
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR**. Thanks!

**Closed by djhvscf** 2017-06-19 06:17 UTC
Labels: awaiting reply, needs example
