### ISSUE TITLE
Server Side - Row insertion followed by cell/row click returns the next row

### ISSUE THREAD

**Issue by mhaque02** [wenzhixin/bootstrap-table#5376] opened 2020-10-11 19:48 UTC
Bootstraptable version: 1.17.0+

When using server side pagination with Insert Row button, after the new row is inserted and the user clicks on a cell or row the returned cell/row is the next row - not the one that was selected. 

This is happening with version 1.17.0 and above. When testing in 1.16.0 the issue is not there.

https://live.bootstrap-table.com/code/mhaque02/5069

Image attached. I've clicked on Item 1 but it is returning Item 2. If 2 rows were inserted at the top, it would return Item 3... and so on. 

![image](https://user-images.githubusercontent.com/1075631/95688678-db4d0a00-0bd9-11eb-8ff1-df53351b8645.png)

**Comment by wenzhixin** [comment] 2022-05-14 09:58
After confirming, I think this is not a bug. 
If it is server-side pagination, the correct process for adding a row should be:
1. post to add API to server.
2. refresh the table to update the new data.

I will close this issue. If you still need help, reopen it. Thanks!

**Closed by wenzhixin** 2022-05-14 09:58 UTC
Labels: confirmed, Bug
