### ISSUE TITLE
columns headers not aligned  correctly 

### ISSUE THREAD

**Issue by bet-proj** [wenzhixin/bootstrap-table#4622] opened 2019-10-03 08:10 UTC
hi, 
i have a problem of columns miss aligned correctly 
when i'm using more 15 header in table the header not aligned with body of table and the arrange of columns become not correct  as below image is there any help for this issue 

![Capture](https://user-images.githubusercontent.com/45256377/66109973-0b74cc80-e5c6-11e9-8aa9-7feedf53552c.PNG)

**Comment by UtechtDustin** [comment] 2019-10-03 10:19
I cant reproduce it ([Example](https://live.bootstrap-table.com/code/UtechtDustin/843)), please provid us an example of the issue (using our [editor](https://live.bootstrap-table.com/)).

Do you maybe use a extension which cause the issue ?

**Comment by bet-proj** [comment] 2019-10-07 09:07
there is no extension in my browser  and the style worked in old version of bootstrap-table , so what is the expected issue that causes that ??!!

**Comment by bet-proj** [comment] 2019-10-07 12:10
dear , 
i found that when the no of records is less than 5 records the header become un aligned and the responsive become wrong , but when the no of records more than 5 and pagination occuer the design become correct and header become aligned ??!!! 
is there any idea

**Comment by wenzhixin** [comment] 2019-10-07 15:52
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem, thanks!

**Comment by bet-proj** [comment] 2019-10-08 10:02
you can find example here 
https://live.bootstrap-table.com/code/bet-proj/862
and please scroll to the right to find the issue

**Comment by bet-proj** [comment] 2019-10-10 12:15
dear , 

kindly be informed that in the old version V 1.8.1 of bootstrap-table it is worked well with no problem ,
but in the new version its not worked good ?? why that ?? 
i need to update to new version so please i need the solution ASAP 
thanks in advance

**Comment by wenzhixin** [comment] 2019-10-16 16:02
Fixed in #4640: https://live.bootstrap-table.com/code/wenzhixin/904

Because our plugin do not support duplicate fields, we need to change the duplicate `adminStatus` and `operStatus` to `adminStatus1` and `operStatus1`.

**Closed** 2019-10-16 17:08 UTC
Labels: confirmed, has PR, js

**Comment by bet-proj** [comment] 2019-10-22 07:21
thanks its worked now
