### ISSUE TITLE
FilterControl inputs are disable after print table

### ISSUE THREAD

**Issue by Federico-Luna** [wenzhixin/bootstrap-table#5686] opened 2021-04-18 21:50 UTC
**Bootstraptable version(s) affected**:
v1.18.3

**Description**  
The focus of the current page is lost.

The sequence is as follows:
1.- click the print button.
2.- The print page opens.
3.- Close the print page (do not cancel printing).
4.- You have to close the current page and reopen it or click on another page that is open and then click on the current page to regain focus.
5,. Then everything works fine again.

**Example**  
https://live.bootstrap-table.com/code/Federico-Luna/7421

**Comment by UtechtDustin** [comment] 2021-04-18 22:34
Im not sure what do you mean.
In the title you wrote "disabled inputs", in the description you wrote something about focus ?

I followed your step by step description, but i can't figure out the issue. But i'm also not sure what do you mean with `Close the print pag do not cancel printing`, do you mean print the page ?
Because this has the same effect for me as cancel the print.

Could you explain it further ?

**Comment by Federico-Luna** [comment] 2021-04-19 09:06
Excuse me, the title is a mistake.

It was the first impression it gave me, but then I continued testing and realized that it was not that but what I explain in the steps.

Please follow the steps below:
1.- Open link in a new tab.
2.- Click on the print button.
3.- Close the print page tab (do not cancel printing)
4.- Try to write something in the input box (Item name) .

Note: I just realized that the select (Item price) does work.

Thank you, very much.

**Comment by UtechtDustin** [comment] 2021-04-19 15:16
For me both (input and select) works fine after closing the print page tab (without printing or canceling).
Which Browser (version) do you use ?

**Comment by djhvscf** [comment] 2021-04-19 16:23
@Federico-Luna you mean that it doesn't work because you expect that the input control has the focus after the printing is cancelled?

**Comment by Federico-Luna** [comment] 2021-04-22 07:30
Sorry for my delay.

No, it is not that, it is simply that after closing the print window and clicking on the input, I cannot write because it is disabled.

Is there a way to send a video?

**Comment by codmdu** [comment] 2021-04-22 07:33
@Federico-Luna sure you can upload (mp4) here on github.

**Comment by UtechtDustin** [comment] 2021-04-22 11:50
@Federico-Luna yes, you can upload a mp4 here on github.

**Comment by Federico-Luna** [comment] 2021-04-23 14:59
OK, thanks.

Here is a video.

In Firefox the clear button does not appear.

Chrome video:
https://user-images.githubusercontent.com/46276855/115889186-013e4b80-a454-11eb-8a3e-83800ec70555.mp4

Firefox video:
https://user-images.githubusercontent.com/46276855/115890393-2f705b00-a455-11eb-802e-76c8c248f211.mp4

**Comment by UtechtDustin** [comment] 2021-04-23 15:40
Thanks for the video, i can reproduce it with chrome.

> In Firefox the clear button does not appear.

If you mean the clear button within the input, this is a feature of chrome not of the bootstrap-table :-)

**Comment by UtechtDustin** [comment] 2021-04-23 16:07
It seems this is a Bug of chrom(ium), so we have to wait that the chrom(ium) team will fix that!
https://bugs.chromium.org/p/chromium/issues/detail?id=1201623

**Closed by UtechtDustin** 2021-04-23 16:07 UTC
Labels: Bug, browser dependent, confirmed
