### ISSUE TITLE
fixed-table-toolbar toggle问题，checkbox美化问题

### ISSUE THREAD

**Issue by flicker85** [wenzhixin/bootstrap-table#643] opened 2015-03-20 01:51 UTC
问题1：
 如果用1.6版，toggle行列转换时，如果有checkbox列，转换后报错，checkbox不显示，按钮列里的按钮无效。
如果用master里的脚本，点击toggle按钮，toolbar里的按钮被清空，怎么解？
如：http://issues.wenzhixin.net.cn/bootstrap-table/

问题2：
我想对checkbox列做美化，代码修改checkbox状态通过change事件是捕获不到的，无法在checkbxo change事件中根据checkbox状态动态修改显示的checkbxo美化图片，如果用css3中的":checked"属性捕获change没问题，但是有低版本IE不支持，有什么好的解决办法么？

**Comment by djhvscf** [comment] 2015-03-20 14:08
Can you translate it to english, please? @flicker85

**Comment by flicker85** [comment] 2015-03-23 02:25
Q1:
use the version 1.6,if click on the ‘toggle’ button in tollbar,then checkbox button disappear.
use the master code, click on the toggle button, the toolbar of the content is empty.
Q2:
I would like to beautify the checkbox button in the bootstrap-table.
switching the checkbox button image in the checkbox change event, but unable the change event when the bootstrap-table use code change chengbox selected state.
there is no good method for checkbox button beautify?

**Comment by djhvscf** [comment] 2015-04-05 05:22
For the Q1 the issue is already fixed but for the Q2 I don't know if @wenzhixin  can help us :)

**Comment by wenzhixin** [comment] 2015-04-07 07:02
Q2 I recomment to use CSS3 to do that, for example: http://issues.wenzhixin.net.cn/bootstrap-table/#383.html, but there is no good way to what don't support the low version of the IE browser. Close this issue.

**Closed by wenzhixin** 2015-04-07 07:02 UTC
