### ISSUE TITLE
How To mergeCells footer

### ISSUE THREAD

**Issue by a40234023** [wenzhixin/bootstrap-table#2039] opened 2016-02-28 03:57 UTC
Ask how to mergeCells footer??
THX

**Comment by Falseee** [comment] 2016-02-28 04:41
I think it is not supported yet...

**Comment by djhvscf** [comment] 2016-02-28 07:49
@a40234023 this feature is not supported yet but remember any **PR** is welcome

**Comment by a40234023** [comment] 2016-02-28 14:02
Thank you

**Comment by dabros** [comment] 2016-02-28 23:37
https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#pull-requests

**Comment by wenzhixin** [comment] 2019-04-04 15:37
Duplicate of #2276, close this one.

**Closed by wenzhixin** 2019-04-04 15:37 UTC
Labels: feature
