### ISSUE TITLE
How to select several checkboxes without using ctrl using Multiple Select Row?

### ISSUE THREAD

**Issue by AlexByte** [wenzhixin/bootstrap-table#6026] opened 2022-01-13 11:07 UTC
### Description

I want to select checkboxes just by clinking on them, as usual, i only want shift+click functionality from multipleSelectRow option.

**Comment by wenzhixin** [comment] 2022-01-31 09:19
Does the `multipleSelectRow` option maybe solve your problem?
https://examples.bootstrap-table.com/index.html#options/multiple-select-row.html

**Comment by AlexByte** [comment] 2022-01-31 09:27
I wrote that I want to select multiple rows without the ctrl key.

**Comment by UtechtDustin** [comment] 2022-01-31 09:29
Duplicate of  #5389.

**Closed by UtechtDustin** 2022-01-31 09:29 UTC
Labels: help-wanted, awaiting reply
