### ISSUE TITLE
insertRow after sorting

### ISSUE THREAD

**Issue by hmane** [wenzhixin/bootstrap-table#2343] opened 2016-06-02 19:46 UTC
I am trying to insert new row. It work fine if sorting is not applied on the table. But if i apply the sorting and execute insertRow code, it will not go to specific index. After adding new record, sorting functionality is executing and changing the new row index.

I have created [jsfiddle ](http://jsfiddle.net/e3nk137y/6836/). 
insertRow without sorting will work fine and add the record @ index 1.
After sorting name desc it adds the row to the last position.

Is there any way to not apply sorting on added record?

**Comment by wenzhixin** [comment] 2016-07-09 13:36
I think this is not a bug.

**Comment by djhvscf** [comment] 2016-07-12 01:36
I also think this is not a bug

**Comment by NestorLeone** [comment] 2016-08-09 14:34
Bug or not, I have the same problem. After sorting, insertrow ignores the Index where it's suposed to insert the row into. It just inserts it at the end of the table. 
This ONLY happens after sorting the table by any of the columns. Is there any workaround ?

**Comment by neksu** [comment] 2017-04-20 19:34
i think its bug, in my case if i sort and then insert row it doesnt appear even on end of the table, its appear until after refresh, i tried this on table with about 3000 rows

**Comment by djhvscf** [comment] 2017-04-23 07:58
@neksu but when you insert the row it should be at first position of the table?

**Comment by neksu** [comment] 2017-04-23 11:44
@djhvscf yes, i tried for index set to 0, 1 and -1, row doesnt appear in every case, i saw its only problem with table where i have about 3000 rows, on second table with about 200 rows all is good

**Comment by lowegreg** [comment] 2018-01-26 12:43
I'm also experiencing this issue.  Was wondering if there was a re-index call we could make after sort/filter/search?

**Comment by djhvscf** [comment] 2018-09-09 19:54
Close this issue because there is no any response in 7 days, if the problem exists reopen it, thanks!

**Closed** 2019-01-11 15:38 UTC
Labels: awaiting reply, js
