### ISSUE TITLE
search + detailView : get wrong row data 

### ISSUE THREAD

**Issue by reedgz** [wenzhixin/bootstrap-table#1210] opened 2015-07-24 04:15 UTC
This could be a bug:
- bootstrap-table 1.8.1
- client side pagination & search

When I use `search`, `expand-row` gets wrong  `row` data.
(screenshot attached)

```
$callLogTable.bootstrapTable({
  data: reportData,
  detailView : true,
  pagination: true,
  sidePagination: 'client',
  pageList: [10, 50],
  search: true,
});

$callLogTable.on('expand-row.bs.table', function (e, index, row, $detail){
    console.log(e, index, row, $detail);
    // when search is used, row data is in-correct
}
```
Without search condition(correct)
![bs-table-bug01](https://cloud.githubusercontent.com/assets/1428027/8867563/c6284c28-3198-11e5-90db-518ccbdc95ed.png)

With search condition (bug)
![bs-table-bug02](https://cloud.githubusercontent.com/assets/1428027/8867564/c8697a66-3198-11e5-80f7-3d7e995626f9.png)

**Comment by bmcbride** [comment] 2015-07-24 14:17
Duplicate of #980. I recently ran into this as well! Looks like it's fixed in master.

**Comment by wenzhixin** [comment] 2015-07-27 02:49
You are right @bmcbride , we have fixed this bug, you can use src file until next version release.

**Closed by wenzhixin** 2015-07-27 02:49 UTC

**Comment by Gsrinu** [comment] 2016-04-30 06:29
i am also having same problem please help me

**Comment by wenzhixin** [comment] 2016-07-12 03:28
@Gsrinu please use the latest version, if the problem exists please create a new issue and provide jsfiddle to show your problem.
