### ISSUE TITLE
After deleting the selected row, the deleted row can be found when querying the selected row

### ISSUE THREAD

**Issue by RichMoster** [wenzhixin/bootstrap-table#5278] opened 2020-08-30 09:03 UTC
Check the source code and find that the operation is this.options.data When getselections, the query is this.data Is this a bug or does it need special treatment?

**Comment by djhvscf** [comment] 2020-09-05 17:26
I think this is a bug since we use this.options.data to keep the original data safe and we use this.data to apply the corresponding filters/sorting etc.. So I think we need to kind of syncronize the addition, update and deletion of row in these two arrays.

@wenzhixin @UtechtDustin what do you think? In the meantime marked as bug

**Comment by UtechtDustin** [comment] 2020-09-05 17:27
Yes, its a bug.

**Comment by RichMoster** [comment] 2020-09-06 01:27
> Yes, its a bug.

Thank you for your reply.Mainly insert rows and delete rows

**Comment by RichMoster** [comment] 2020-09-06 01:28
> I think this is a bug since we use this.options.data to keep the original data safe and we use this.data to apply the corresponding filters/sorting etc.. So I think we need to kind of syncronize the addition, update and deletion of rows in these two arrays.
> 
> @wenzhixin @UtechtDustin what do you think? In the meantime marked as bug

Thank you for your reply.

**Comment by UtechtDustin** [comment] 2020-09-11 10:40
@RichMoster could you provide us an example ?
I can't reproduce it with mine [example](https://live.bootstrap-table.com/code/UtechtDustin/4596).
I checked some rows, use the getSelections buttons and see the selected rows.
After that i clicked on the remove button which removes the rows, if i press the getSelections button again the array is empty.

**Comment by fangmanlu** [comment] 2020-09-14 02:58
I met the same scene. 
https://live.bootstrap-table.com/example/welcome.html
When I checked Item ID 0, and then click 'delete' button, it works find. But now if I check Item ID 1, and then click 'delete' button, 'Item ID 1' will not be removed. It do nothing, since 'getSelections' store the 'Item ID 0' not 'Item ID 1'.
Please check it.

**Comment by RichMoster** [comment] 2020-09-14 05:34
> @RichMoster could you provide us an example ?
> I can't reproduce it with mine [example](https://live.bootstrap-table.com/code/UtechtDustin/4596).
> I checked some rows, use the getSelections buttons and see the selected rows.
> After that i clicked on the remove button which removes the rows, if i press the getSelections button again the array is empty.
Sorry, I forgot to provide an example
example：https://live.bootstrap-table.com/code/RichMoster/4625
Step 1: Select data with ID 0 and 1
Step 2: Click the Delete button
Step 3: Click the getSelections button.The result is  0 and 1
Step 4: Select data with ID 2 and 3
Step 5: Click the getSelections button.The result is  0 and 1
Step 5: Click the Delete button.Unable to delete

**Comment by RichMoster** [comment] 2020-09-14 05:35
> I met the same scene.
> https://live.bootstrap-table.com/example/welcome.html
> When I checked Item ID 0, and then click 'delete' button, it works find. But now if I check Item ID 1, and then click 'delete' button, 'Item ID 1' will not be removed. It do nothing, since 'getSelections' store the 'Item ID 0' not 'Item ID 1'.
> Please check it.

Yes, the same as my question

**Comment by UtechtDustin** [comment] 2020-09-14 16:37
Thanks for the example, i could figure out that `sidePagination="server"` is the problem,  which also explains why i cant reproduce the issue.
We will check that!

**Closed** 2020-09-16 06:58 UTC
Labels: Bug, has PR, needs example
