### ISSUE TITLE
Options, Methods without jQuery

### ISSUE THREAD

**Issue by vzlabiom** [wenzhixin/bootstrap-table#6747] opened 2023-04-15 09:06 UTC
### Description

All methods defned for JQuery object, i.e. it must be used $(#table).bootstrapTable('method', parameter).
Its it possible to exclude JQuery and use merhods for NodeElement (i.e. element which is defined with document.querySelector(...)).

**Comment by marceloverdijk** [comment] 2023-04-27 10:54
Related to https://github.com/wenzhixin/bootstrap-table/issues/6717
I think more people are interested in this.

**Comment by UtechtDustin** [comment] 2023-06-08 15:17
Duplicate of #4796   
We also want to remove jQuery, but other issues have a higher priority.   
Pull requests are welcome :)

**Closed by UtechtDustin** 2023-06-08 15:17 UTC
Labels: help-wanted
