### ISSUE TITLE
Checkbox colum disappears when using cookies

### ISSUE THREAD

**Issue by UselessGuru** [wenzhixin/bootstrap-table#6579] opened 2022-12-23 17:56 UTC
### Bootstraptable version(s) affected

1.21.2

### Description

Checkbox colums disappears after visible columns have been changed.

Steps to reproduce:
1. Click 'Columns' icon (top right)
2. Deselect a column
3. Run example again or refreach page -> Checkbox is hidden

### Example(s)

https://live.bootstrap-table.com/code/UselessGuru/13880

**Comment by UtechtDustin** [comment] 2022-12-23 22:08
Duplicate of #6556

**Closed by UtechtDustin** 2022-12-23 22:08 UTC
Labels: Bug
