### ISSUE TITLE
Datepicker and other control inside detail view

### ISSUE THREAD

**Issue by startovernow** [wenzhixin/bootstrap-table#2921] opened 2017-02-19 18:30 UTC
Hello!

I am trying to use a bootstrap datepicker inside detail view of bootstrap-table when detail view is expanded, the calendar control is not popup when field is clicked. Another input field with mask and formatting function for currency format also is not working.

The following div1 works fine by itself, but not when loaded into detail view

Any suggestions what needs to be done to make this work inside detail view?

Here are some simplified code and screenshots:
html:

        <div>
            // Bootstrap-table goes here
            <table id="table1">
            </table>
        </div>
        <div id="div1">
            <div id="div2">
                <div class="form-group">
                    <label class="control-label">Date: </label>
                    <div>@Html.TextBoxFor(m => m.Date)</div>
                </div>
                <div class="form-group">
                    <label class="control-label">Approved Amount $: </label>
                    <div>@Html.TextBoxFor(m => m.Amount)</div>
                </div>
            </div> //end of div2
        </div> //end of div1
        <script>
            $(function () {
                var $Date = $('#Date'),
                    $Amount = $('#Amount'),
                    $table1 = $('#table1');
        
                $Date.datepicker({autoclose: true, todayHighlight: true});
                $Amount.mask("$###,###,###,###.00", {reverse: true});
        
                $table1.on('expand-row.bs.table', function (e, index, row, $detail) 
                {            
                    $detail.html($div1.html());
                });
        
             });
    
    </script>
![inside detailview](https://cloud.githubusercontent.com/assets/18681747/23129875/ee82e430-f749-11e6-925b-da181a648a6a.png)

![outside detailview](https://cloud.githubusercontent.com/assets/18681747/23129880/f6b1036c-f749-11e6-9afb-cd345c06ef7a.png)

**Comment by wenzhixin** [comment] 2017-02-22 00:08
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your problem, thanks!

**Comment by djhvscf** [comment] 2018-01-29 05:51
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR** with an [example](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports). Thanks!

**Closed by djhvscf** 2018-01-29 05:51 UTC
Labels: needs example
