### ISSUE TITLE
Improve search

### ISSUE THREAD

**Issue by sanjibpramanick** [wenzhixin/bootstrap-table#2502] opened 2016-07-25 12:35 UTC
Search should be based on column and value pair which will be provided by user. 

Here is a sample table data. [https://jsfiddle.net/agowqrhu/](url)

Sample input : 
'First Name':lara,Berry 

Expected output :
127 Lara        Dutta
133 Berry   Alen

**Comment by dabros** [comment] 2016-07-26 00:45
@sanjibpramanick

**Via UI or via Code?**

You need to be more explicit in your current output vs desired output and exactly the scope of what you need. 

If you want the core search field to handle your custom input, first take a step back and look at options provided then think best approach, dont get too fixed on any specific point and always examples and doco.



**There are many ways to search, including with explicit columns**

`filterBy` is designed for client side, does exactly that, always very specific searches. 

For server side you let your server code be whatever you want, its actually EASIER in server side as then your server code can have whatever 'smart search' you want, bootstrapTable js code just sends off request and handles response.

http://bootstrap-table.wenzhixin.net.cn/documentation/#methods

Several approaches also exist with advanced search UI, such as [Filter Control](https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/filter-control), advanced toolbars, ect. Checkout the list and follow links and examples, very easy to use.

http://bootstrap-table.wenzhixin.net.cn/extensions/


**Also, your fiddle is broken:**

Always check your fiddle and its link, as both are broken above (fiddle not setup, just a barebones html table, would taken just as little time to set it up properly). JS array for data is easiest to setup and tweak if needed, and you can use an echo function provided by jsfiddle for server side (or server side urls presented in examples).

Examples and guide provided below:
- https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#bug-reports
- #1765

**Comment by wenzhixin** [comment] 2016-07-29 00:13
Have you solved your problem?

**Comment by sanjibpramanick** [comment] 2016-08-01 13:47
I have no idea what happen to the fiddle link.
Anyway, I'm looking for a search functionality where the search will be based on multiple column values.

like id=(127 or 133) and name='abcd'

**Comment by dabros** [comment] 2016-08-02 23:17
@sanjibpramanick - read above posts again, solutions are provided.

**Comment by djhvscf** [comment] 2017-12-29 08:16
Hi! We don't have any reply in that case we are going to close this issue. If the issue is still present please open a new **Issue** or **PR**. Thanks!

**Closed by djhvscf** 2017-12-29 08:16 UTC
Labels: awaiting reply, help wanted
