### ISSUE TITLE
Can't recieve the params on server side - POST method

### ISSUE THREAD

**Issue by vallaveen** [wenzhixin/bootstrap-table#3308] opened 2017-08-11 22:39 UTC
My HTML Code

```
<table	id="table"
		data-toggle="table"
		data-ajax="ajaxRequest" 
		data-side-pagination="server"
		data-pagination="true">
		<thead>
			<tr>
				<th row here .... >
			</tr>
		</thead>
</table>
```
The jQuery ajax method is as below,
```
function ajaxRequest(params) {
		
		$.ajax({ 
			url     : "/app/entry/scripts/data.php",
			type    : 'POST',
		queryParams	: function (p) {
						return {
						        date : '2017-08-03',
							lot : 'newlot3',
							}
					 },
			success : function (response){
				
				alert(response);
				
				params.success(	response );
				

			}
		});
		
    }
```

then, when I try to access the date posted in queryParams in data.php using code,
`$dateposted = $_POST['date'];`
I am getting the error, `Undefined index: date in file ....`

How to access the variables passed into the php file ?

Sorry if this question is so noob. I am not from programming background.
Any help is much appreciated.

P.S. If the question is already asked, kindly point me to it. I searched my best before posting.

**Comment by wenzhixin** [comment] 2017-12-17 06:08
You are using ajax in wrong way, you can use like this:
```
<table	id="table"
		data-toggle="table"
                data-url="/app/entry/scripts/data.php",
                data-type="post",
		data-query-params="queryParams" 
		data-side-pagination="server"
		data-pagination="true">
		<thead>
			<tr>
				<th row here .... >
			</tr>
		</thead>
</table>
```
Duplicate of #152

**Closed by wenzhixin** 2017-12-17 06:08 UTC
